### DISCUSSION TITLE
run_every vs realert and other questions too -- Please help

### DISCUSSION THREAD

**Discussion by the-arcade-01** [jertel/elastalert2#1043] [Q&A] [answered]
whats the difference between run_every vs realert? and how often does elastalert query elasticsearch and how to change that querying as i have lots of logs coming in a second (approx 10k in every second) and dont want to hinder the performance?
also using metric_agg. I'm ok with getting alerts with delays and these alerts are not urgent but important. Thanks
```
type: spike
spike_height: 2
spike_type: "up"

threshold_ref: 5000
threshold_cur: 10000

timeframe:
 seconds : 1

query_key: ['<field_name>']

metric_agg_key: <field_name>
metric_agg_type: value_count

doc_type: doc

filter:
- query:
   query_string:
    query: <query_filters>
```
