### DISCUSSION TITLE
`percentage_match` - percentage calculation - wrong values?

### DISCUSSION THREAD

**Discussion by ddziaduch** [jertel/elastalert2#1049] [Q&A] [answered]
Heya, I have a setup like this:

```yaml
  alert: |-
    ---
    name: Alert
    type: percentage_match
    index: xxx
    doc_type: _doc
    max_percentage: 3 # trigger alarm when more than 3%
    buffer_time:
      hours: 1 # check data from last 1 hour
    filter:
    - terms:
        message.context.value: [1,2]
    - terms:
        message.context.key.keyword: ["SuccessEvent", "FailedEvent"]
    query_key: message.context.value
    match_bucket_filter:
    - term:
        message.context.key.keyword: "FailedEvent" # trigger alarm only for failures
    alert:
    - "slack"
    slack_emoji_override: ":fire:"
    slack_webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
    slack_title: "Kibana Dashboard"
    slack_title_link: "xxx"
```
And the alert looks like this:
```
[Kibana Dashboard](xxx)
Alert
Percentage violation, value: 3.0434782608695654 (min: None max : 3) of 230 items
@timestamp: 2022-12-10T08:11:28.859043Z
denominator: 230
message: {
   "context": {
      "value": 2
   }
}
num_hits: 1578
num_matches: 1
percentage: 3.0434782608695654
```
Looks like something is off here.
According to what I have found in the source code the logic is this: `(1*1.0) / (230 * 1.0) * 100 = 3.0434782608695654` but this is not true 🙄

Is this a bug or am I doing something wrong?

Thanks in advance
