### DISCUSSION TITLE
Having issues with summary_table_fields

### DISCUSSION THREAD

**Discussion by dakotacody** [jertel/elastalert2#1060] [Q&A] [answered]
I'm trying to get one rule to create one alert that includes the summary of all the matches during that aggregation period.  I've read through the documentation a lot.  I originally started with `frequency` type rule but have now switched to `any`.  No matter what I've tried I can only get the summary_fields table to show one value.  However, top_count_keys does display the individual values for the keys I've specified, it's just not what I really want/need. 

```
Aggregation resulted in the following data for summary_table_fields ==> ['syslog_hostname', 'syslog_program', 'count']:

+---------------------+----------------+-------+
|   syslog_hostname   | syslog_program | count |
+=====================+================+=======+
| alertmanager-1 | sshd           | 1     |
+---------------------+----------------+-------+

alert-errors

syslog_hostname:
alertmanager-1: 40
alertmanager-2: 40
alertmanager-3: 40

syslog_program:
sshd: 120
```

You can see I tried to force it to aggregate by the syslog_program so all alerts would bucket together thinking that what the issue with the summary table.   You can also see below the that the top_count items all add up and are counted individually. 

Basically, this is a rudimentary POC  I'm trying to get this simple case working so I can understand how to actually do it with other interesting data. 

What I'm expecting the table to look like in this case is this, but I only ever get one line and the count is always 1. 
```
+---------------------+----------------+-------+
|   syslog_hostname   | syslog_program | count |
+=====================+================+=======+
| alertmanager-1 | sshd           | 40     |
| alertmanager-2 | sshd           | 40     |
| alertmanager-3 | sshd           | 40     |
+---------------------+----------------+-------+

```

I've tried using the attach_related etc.. but I only ever get the one column and the "related" matches are always only for the one one host.

Here's the current iteration I'm working with which has been changed and modified so many times that I'm finally reaching out.   I'll leave the commented lines in to give some indication of what I've tried. 
```
#type: frequency
type: any 
index: "syslog-*"
num_events: 1 
timeframe:
    minutes: 10
realert:
    minutes: 0
#use_terms_query: true
#aggregation_key:
#- syslog_program

#query_key:
#- syslog_hostname
#- syslog_program

aggregation: 
  minutes: 2

#scan_entire_timeframe: true
filter:
- term: 
    syslog_program: "sshd"
- query:
    wildcard:
      syslog_hostname: "alertmanager-*"

#attach_related: true
#include:
 #- syslog_hostname
 #- syslog_program

summary_table_fields:
  - syslog_hostname
  - syslog_program

top_count_number: 5
raw_count_keys: false
top_count_keys: 
  - syslog_hostname
  - syslog_program

```
