### DISCUSSION TITLE
host.ip <Missing Value>

### DISCUSSION THREAD

**Discussion by sucremad** [jertel/elastalert2#1070] [Q&A] [answered]
Hi,

I'm trying to write alert text with arguments, I cannot use `host.ip[0]` even though I can use `host.hostname`.  It says "\<MISSING VALUE\>"

```yaml
alert_text: |-
    - Date/Time: {0}
    - Host: {1}
    - IP: {2}
alert_text_args:
  - "@timestamp"
  - host.hostname
  - host.ip[1]
```
OUTPUT:

```
- Host: computer
- IP: <MISSING VALUE>
```

the data:

```json
 "host": {
      "hostname": "computer",
      "os": {
        "build": "value",
        "kernel": "value",
        "name": "value",
        "type": "windows",
        "family": "value",
        "version": "10.0",
        "platform": "value"
      },
      "ip": [
        "ipv6",
        "ipv4"
      ],
```

How can I output the IP?

thanks in advance
