### DISCUSSION TITLE
Custom fields + args in the same rule

### DISCUSSION THREAD

**Discussion by albertoCrego** [jertel/elastalert2#1087] [Q&A] [answered]
Hello, 

I already have in my alert some args from the alert: 

```
    alert_text: |-
      *Alert:*  {}
      *Kibana:* <{}|Search>
      *Description:* {} 
        
    alert_text_args:
      - alert_subject
      - kibana_discover_url  
      - description
```

But now I need to add key-value info inside the alert. Something like: 

```
text: example
text1: example1

alert_text: |-
  Alert:  {}
  Kibana: <{}|Search>
  Description: {} 
  text: {}                        ## the value would be example
  text1: {}                      ## the value would be example1
alert_text_args:
  - alert_subject
  - kibana_discover_url  
  - description
  - text
  - text1
```

Do you know how I can do it? I tested `alert_text_kw` but I cannot configure it properly in the code seems that it is not possible to use `alert_text_args` and `alert_text_kw` at the same time. 

Thank you!

**Comment by jertel** [comment, marked as answer]
`alert_text_kw` is used for renaming the field names in the alert message. From your post above that does not appear to be what you want to do. You are asking to add additional, hardcoded values to the alert message, right? If so, you should be able to continue using `alert_text_args` as you have it written above. You do have a typo with `text1` vs `text2` but otherwise it looks correct. If the Elasticsearch record happens to contain that field name `text` or `text2` then that value will override the hard-coded values in your rule file.

**Reply by albertoCrego** [reply]
Typo edited! 

But I need to get the field from the rule, not from the Elasticsearch field. 
For example (this is the use case), I want to add a Link with the documentation in the rule. Something like: 

```
documentation: "https://hostname.com"

alert_text: |-
  Alert:  {}
  Kibana: <{}|Search>
  Description: {} 
  Documentation: {}                        ## the value would be https://hostname.com
alert_text_args:
  - alert_subject
  - kibana_discover_url  
  - description
  - documentation
```
