### DISCUSSION TITLE
query_string list doesn't work

### DISCUSSION THREAD

**Discussion by mccok** [jertel/elastalert2#1103] [Q&A] [answered]
elastalert-test-rule rules/rule_2.yaml doesn't match anything if I set it like this
```
     filter:
     - query:
         query_string:
           query: "message: \"Starting service\""
     - query:
         query_string:
           query: "message: error"
```
 
esAlert works fine if I set it like this

```
     filter:
     - query:
         query_string:
           query: "message: \"Starting service\" OR error"
```

So, I want to know, can't the filter set multiple queries?
