### DISCUSSION TITLE
How to get the respective number of groups after grouping by query_key?

### DISCUSSION THREAD

**Discussion by 1998729** [jertel/elastalert2#1114] [Q&A] [answered]
How to get the respective number of groups after grouping by query_key?
```
example:
run_every:
  minutes: 1
buffer_time:
  minutes: 3
timeframe:
  minutes: 1
realert:
  minutes: 3
num_events: 10
filter:
- query:
    query_string:
      query: 'business: "base" AND  whitelist.keyword: 0 NOT uri: websocket NOT uri: ws NOT uri: socket.io AND status: >=500'
query_key:
- status
- uri

# query_result:
num_hits: 50 

# query_key result
status: 502 uri: /abc  
status: 503 uri: /abc
```
How to get the respective quantities after the above two aggregations?
