### DISCUSSION TITLE
RDP wildcard not picking up hits

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#1121] [Q&A] [answered]
Tried these three but none work:

```
filter:
- query:
    wildcard:
      dst: "*.*.*.*:3389"

filter:
- query:
    wildcard:
      dst: "*:3389"

filter:
- query:
    wildcard:
      dst: "*:3389:*"
```
This is a sample dst field: 

`dst: 10.100.10.112:3389:X0`

Any advice?

**Comment by jertel** [comment, marked as answer]
I suggest using Kibana, or cURL if you prefer using the command line, to find the working query outside of ElastAlert 2, and then once you are confident it works as intended, transfer it to your rule .yaml file. You might get more knowledgeable help on Elasticsearch queries by contacting that community/forum. 

Also, the Elasticsearch docs state the following, which you will want to double check on your ES server configuration:

```
Notes[edit](https://github.com/elastic/elasticsearch/edit/8.6/docs/reference/query-dsl/wildcard-query.asciidoc)
Allow expensive queries[edit](https://github.com/elastic/elasticsearch/edit/8.6/docs/reference/query-dsl/wildcard-query.asciidoc)
Wildcard queries will not be executed if [search.allow_expensive_queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html#query-dsl-allow-expensive-queries) is set to false.
```

**Reply by roman-tasi** [reply]
I figured out that it just doesn't work with a colon (`:`)
This works however:

```
filter:
- query:
    wildcard:
      dst: "*3389*"
```

However it would still be ideal to incorporate the colon, because as of now there is no other way to distinguish the 3389 as port (this wildcard search can pick up other results with 3389 not as the port because it needs `:`s surrounding it)
