### DISCUSSION TITLE
Support env var substitution in all config.

### DISCUSSION THREAD

**Discussion by archfz** [jertel/elastalert2#114] [Ideas]
I would like to use env vars in any yaml:

```yaml
name: API Error
type: any
index: filebeat-*
filter:
    - query:
          query_string:
              query: 'event.dataset: "dotnet" AND log.level: "Error"'
alert:
    - "discord"
discord_webhook_url: $ELAST_ALERT_DISCORD_URL
```

This seems to not work currently. Am I missing something?
