### DISCUSSION TITLE
realert parameter ignored from config

### DISCUSSION THREAD

**Discussion by georgestack** [jertel/elastalert2#1146] [Q&A] [answered]
Hello,

i have deployed elastalert2 with helm chart and have used `realertIntervalMins` value which is added in configmap config. The value is passed in configuration within the container:

```
---
rules_folder: /opt/elastalert/rules
scan_subdirectories: true
run_every:
  minutes: 1
realert:
  minutes: 3
buffer_time:
  minutes: 15
es_host: xxx
es_port: xxx
writeback_index: elastalert
use_ssl: True
verify_certs: True
alert_time_limit:
  minutes: 2880
generate_kibana_discover_url: true
kibana_discover_app_url: app/discover#/
kibana_discover_version: "8.5"
kibana_url: xxx
logging:
  disable_existing_loggers: false
  incremental: false
  loggers:
    elasticsearch:
      handlers: []
      level: DEBUG
      propagate: true
  version: 1
rules_index_name: es-custom-rules
rules_loader: elastalert_modules.es_rule_loader.ElasticRulesLoader
```

but is ignored, silence is used with 1 minute default time. `realert` is respected only when added in the alert rule.

According to Helm Chart `realertIntervalMins` or according to documentation `realert` parameter can be set in config level.
