### DISCUSSION TITLE
Error: "query malformed" in regards to filter

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#1151] [Q&A] [answered]
I believe I am getting this error in regard to my filter formatting:

`2023-03-31 01:12:04,427    DEBUG        elasticsearch < {"error":{"root_cause":[{"type":"parsing_exception","reason":"[and] query malformed, no start_object after query name","line":1,"col":286}],"type":"x_content_parse_exception","reason":"[1:286] [bool] failed to parse field [filter]","caused_by":{"type":"x_content_parse_exception","reason":"[1:286] [bool] failed to parse field [must]","caused_by":{"type":"parsing_exception","reason":"[and] query malformed, no start_object after query name","line":1,"col":286}}},"status":400}
2023-03-31 01:12:04,427    ERROR           elastalert Error running query: RequestError(400, 'x_content_parse_exception', '[and] query malformed, no start_object after query name')`

The filter is the section I changed and I believe the formatting might be incorrect:

```
name: Windows Login (Slack) Rules File
type: any
filter:
- bool:
   must:
    - exists:
       field: host.hostname
   must_not:
    - term:
       host.hostname: ""
- term:
    winlog.event_id: "4624"
- and:
    - not:
        term:
          winlog.event_data.TargetUserName: "SYSTEM"
- and:
    - not:
        term:
          winlog.event_data.TargetUserName: "ANALYTICS1-PC$"
- and:
    - not:
        term:
          winlog.event_data.TargetUserName: "IUSR"
- and:
    - not:
        term:
          winlog.event_data.TargetUserName: "DWM-1"
```

If you can tell me how to fix this, it would be appreciated.

**Comment by jertel** [comment]
Please review the [documentation](https://elastalert2.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or) on writing filters. An example is provided which includes negated terms.

**Reply by roman-tasi** [reply]
Hi, after reading that link, I tried this:

```
filter:
- bool:
   must:
    - exists:
       field: host.hostname
   must_not:
    - term:
       host.hostname: ""
- term:
    winlog.event_id: "4624"
- bool:
    must_not:
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "SYSTEM"}} ]
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "ANALYTICS1-PC"}} ]
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "IUSR"}} ]
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "DWM-1"}} ]
```

However this section does not appear to be working (meaning excluding those `winlog.event_data.TargetUserName`s):

```
- bool:
    must_not:
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "SYSTEM"}} ]
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "ANALYTICS1-PC"}} ]
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "IUSR"}} ]
        - bool:
            must: [ {term: {winlog.event_data.TargetUserName: "DWM-1"}} ]
```
Sorry if this seems like an elementary question to you, but I just can't figure it out.

**Reply by roman-tasi** [reply]
I am trying this but back to a `query malformed` type of error:

```
filter:
- term:
    winlog.event_id: "4624"
- exists:
    field: host.hostname
- query:
    bool:
      must:
        - exists:
            field: winlog.event_data.TargetUserName
        - bool:
            must_not:
              - terms:
                  winlog.event_data.TargetUserName:[SYSTEM, ANALYTICS1-PC, IUSR, AD-OPTIPLEX-06$, AD-05-OPTIPLEX$, 713E-OPTIPLEX01$, SQLSERVERAGENT, SSISTELEMETRY160, SSASTELEMETRY, SQLTELEMETRY, MSSQLSERVER, MsDtsServer160, NETWORK SERVICE, LOCAL SERVICE, TASI-LATITUDE$, MSSQLServerOLAPService, TASI-MONITOR1$, AD-04-OPTIPLEX$]
              - wildcard:
                  winlog.event_data.TargetUserName: "DWM-*"
              - wildcard:
                  winlog.event_data.TargetUserName: "UMFD-*"

```
