### DISCUSSION TITLE
Has kibana_link been deprecated with elastalert2

### DISCUSSION THREAD

**Discussion by viralmutant** [jertel/elastalert2#1152] [Q&A] [answered]
I have following rule in YAML

```yaml
      use_kibana4_dashboard: <kibana-dashboard-url>
      include:
        ...
        - "message"
        - "kibana_link"
      alert:
      - command:
          command: curl ... "kibanaLink":"%(kibana_link)s"
```

Basically, we are heavily using the generated `kibana_link`. But now I see `<MISSING VALUE>` in the `curl` command

I think my org recently moved to `elastalert2`

**Comment by jertel** [comment]
Yes, please see #442 for the reasoning, and #447 for how links to Kibana discover work in ElastAlert 2. The last comment suggests dashboards may also work. If you try this and confirm it, please update us.

**Reply by nsano-rururu** [reply]
The dashboard function that has stopped working has been removed from the source code when elasticsearch8 is supported.
https://github.com/jertel/elastalert2/pull/744
https://github.com/jertel/elastalert2/pull/740

**Reply by nsano-rururu** [reply]
Kibana_link is also included from the source codeKibana_link is also included from the source code
https://github.com/jertel/elastalert2/pull/744/commits/39c600125fd93ed564f4c5270a4f7edeb7a7edf1

**Comment by viralmutant** [comment, marked as answer]
Oh, what is the alternate now ?

**Reply by nsano-rururu** [reply]
kibana_discover
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#generate-kibana-discover-url

**Comment by viralmutant** [comment]
Ah ok

One question, why does the documentation says this

> kibana_discover_app_url
> 
> ``kibana_discover_app_url``: The url of the Kibana Discover application used to generate the ``kibana_discover_url`` variable.
> This value can use `$VAR` and `${VAR}` references to expand environment variables.
> This value should be relative to the base kibana url defined by ``kibana_url`` and will vary depending on your installation.
> 
> ``kibana_discover_app_url: app/discover#/``

But then the example contains full URL

**Reply by nsano-rururu** [reply]
take a closer look
![image](https://user-images.githubusercontent.com/22293449/229181800-14a325e4-215e-428a-8cdb-d57c24129558.png)

**Comment by viralmutant** [comment]
Should not `kibana_discover_app_url` be just `app/discover#/`, relative to `kibana_url` ?

**Reply by jertel** [reply]
The docs explain this. If it's relative (starts with a slash) it uses the kibana_url. Otherwise, it is treated as the full URL.

![image](https://user-images.githubusercontent.com/16639611/229191585-731f30d6-8426-4dbb-9c4e-1d3eb605ace1.png)

**Reply by viralmutant** [reply]
Looking at the code it seems it should either be:
- `kibana_url` and relative `kibana_discover_app_url`
- Or, `kibana_discover_app_url` should be full URL and `kibana_url` should not be specified

If `kibana_url` is specified, it will always be used. So `kibana_discover_app_url` should be relative in that case

**Reply by jertel** [reply]
It's certainly possible the docs are wrong. You can add a unit test in `kibana_discover_test.py` to prove it, if you're interested.

**Reply by nsano-rururu** [reply]
@viralmutant 

It seems that the number of ways to specify kibana_url and kibana_discover_app_url in pull requests for shorten_kibana_discover_url has increased.
Before that, I remember only specifying the full path to kibana_discover_app_url.
https://github.com/jertel/elastalert2/pull/512

example

**kibana_discover_app_url only**

```yaml
generate_kibana_discover_url: true
kibana_discover_app_url: "http://localhost:5601/app/discover#/"
kibana_discover_index_pattern_id: "mariadb"
kibana_discover_version: "8.6"
```

**kibana_url + kibana_discover_app_url**

```yaml
generate_kibana_discover_url: true
kibana_url: "http://localhost:5601/"
kibana_discover_app_url: "app/discover#/"
kibana_discover_index_pattern_id: "mariadb"
kibana_discover_version: "8.6"
```

**Reply by viralmutant** [reply]
Thanks for checking that.
I was also testing this further and I stand corrected. If both `kibana_url` and `kibana_discover_app_url` have full URL, the `urljoin` method will just pick the latter.

So the behavior would be:

1. No `kibana_url` specified and `kibana_discover_app_url` is a full url : `kibana_discover_url` would the full value defined under app_url
2. `kibana_url` is specified and `kibana_discover_app_url` is relative: `kibana_discover_url` will be generated from both the values
3. `kibana_url` is specifed and `kibana_discover_app_url` is a full url: `kibana_discover_url` would the full value defined by the latter. `kibana_url` value would be ignored

**Comment by viralmutant** [comment]
Based on our discussion and suggestions, I have now changed the YAML to this:
```YAML
rules:
    monitor_crash:
        generate_kibana_discover_url: True
        kibana_discover_app_url: "https://my_url/app/discover#/"
        kibana_discover_version: "7.17"
        kibana_discover_index_pattern_id: "9f138770-cfb9-11ed-94b9-571acd95b6c3"
        alert:
             command: "curl ... "kibanaLink": "%(kibana_discover_url)s"
```

However, I am still receiving `<MISSING VALUE>` in `kibanaLink`
