### DISCUSSION TITLE
Aggregation Mode and Email Alerts

### DISCUSSION THREAD

**Discussion by rpdeo** [jertel/elastalert2#1154] [Q&A]
Hello,

I am facing an issue with elastalert2 version 2.2.3.

I have an aggregation rule which summarizes firewall log data for attacks seen by the firewall device.

This rule has e-mail alerter configured.

The aggregation is configured for with

```yaml
...
type: any
...

query_key:
   - device_id

aggregation_key: device_id

aggregation:
  schedule: '0 * * * *'

filter:
- query:
    query_string:
      query: (...)

```

While for the most part rule works OK and e-mails are sent every hour. There are times when the rule mis-behaves and emails start to be sent every minute rather than at zeroth minute only.

can you suggest if this is mis-configuration of the rule from my side or could be a bug ?
