### DISCUSSION TITLE
wildcard, query_string together elastalert - need help

### DISCUSSION THREAD

**Discussion by the-arcade-01** [jertel/elastalert2#1156] [Q&A] [answered]
i want alert to get triggered when count of event based on the filters is less than threshold. filter condition is json.msg have string starting with '5000*' and also string having 'sending notification' present, but this is giving me count zero
```
name: <name>

index: <index>
doc_type: _doc

type: flatline
threshold: 10

realert:
 seconds: 60

timeframe:
 seconds: 60

use_count_query: true

filter:
 - wildcard:
    json.msg: "5000*"
    json.msg: "sending notification*"

alert:
 - slack

slack_webhook_url: <url>
slack_username_override: <name>
slack_channel_override: <channel>

alert_text: "Alert \n time: {0}\n"
alert_text_args: ["@timestamp"]
```
and i tried using wildcard with query_string this is the syntax, but it didnt worked
```
filter:
 - query:
    query_string:
     query: json.msg: "sending notification"
    wildcard:
     json.msg: "5000*"
```
this is the json.msg
```
"json": {
"msg": "sending notification {\"id\":\"<user_id>",\"event_id\":\"500001010\",\"alert_enabled\":true} for event"
}
```
how can i convert this query into filter for elastalert?
```
{
  "bool": {
    "must": [
      {
        "match_phrase": {
          "json.msg": {
            "query": "\"sending notification\""
          }
        }
      },
      {
        "wildcard": {
          "json.msg": {
            "value": "5000*"
          }
        }
      }
    ],
    "filter": [
      {
        "match_all": {}
      },
      {
        "match_all": {}
      }
    ],
    "should": [],
    "must_not": []
  }
}
```

**Comment by jertel** [comment, marked as answer]
Could you simplify it with a single wildcard query? Example:
```
filter:
- query:
    wildcard:
      json.msg: "sending notification*5000*"
```
