### DISCUSSION TITLE
Fix 'NoneType' object is not iterable

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#1160] [Q&A] [answered]
This is the filter in my rule:

```
filter:
- query:
   query_string:
     query: "message:(\"authentication failed\" AND auth_zimbra)"
```

This is the full error in the docker logs:

```
2023-04-12 10:00:54,087    ERROR           elastalert Traceback (most recent call last):
2023-04-12 10:00:54,088    ERROR           elastalert Uncaught exception running rule Zimbra SASL Auth Failure (Corresponding Users) (Discord): 'NoneType' object is not iterable
```

Do  you know the solution?
