### DISCUSSION TITLE
Unable to get alerts in jinja format only for CPU and Memory

### DISCUSSION THREAD

**Discussion by ramippala** [jertel/elastalert2#1162] [Q&A] [answered]
Hi, i created a rules for CPU, Memory and error logs, and they are working in fine text format, recently changed the alert text to jinja, able to get alerts for Logs, uptime monitoring, 40x and 50x errors, but unable to get same format alerts for CPU and Memory. Attaching rules for reference.

Rule with alert_text format

```
name: High CPU Usage
type: metric_aggregation
index: metrics-*
metric_agg_type: avg
metric_agg_key: system.cpu.total.norm.pct
query_key: host.name
timeframe:
  minutes: 5
max_threshold: 0.10
alert:
- "email"
email:
  - "ram@example.com"

realert:
  minutes: 5
alert_subject_args:
  - host.name
  - "@timestamp"
alert_subject: High CPU usage on {0}
alert_text_type: alert_text_only
alert_text_args: ["host.name", "metric_system.cpu.total.norm.pct_avg", "@timestamp"]
alert_text: "High CPU usage detected on {0} at time {2}. Current value is {1}"
```

Rule with alert_text_jinja format

```
name: CPU Monitoring
type: metric_aggregation
index: metrics-*
metric_agg_type: avg
metric_agg_key: system.cpu.total.norm.pct
query_key: host.name
timeframe:
  minutes: 5
max_threshold: 0.10
alert:
- "email"
email:
  - "ram@example.com"
realert:
  minutes: 10
alert_subject_args:
  - host.name
  - "@timestamp"
alert_subject: High - CPU Monitoring Alert in {0}
alert_text_type: alert_text_jinja
alert_text_args: ["host.name", "metric_system.cpu.total.norm.pct_avg", "priority", "@timestamp", "data_stream.namespace"]
alert_text: |
  Hi Team,

  Alert for CPU monitoring in {{host.name}} is triggered. Details are as follows
  {% set priority_str = 'High' if priority == 1 else 'Normal' if priority == 2 else 'Low' %}
  Priority: {{ priority_str }}
  Host: {{host.name}}
  CPU: {{_data['metric_system.cpu.total.norm.pct_avg']}}
  Environment: {{data_stream.namespace}}
  Alert generated time: {{_data['@timestamp']}}

  Thanks & Regards,
  ELK Team.
priority: 1

```

Output for 1st rule: High CPU usage detected on hsn-nonprod at time 2023-04-17T07:26:28.074243Z. Current value is 0.4455
Expected Output for 2nd rule (same output format from logs rule): 

Hi Team,

Alert for 40x-50x monitoring in hsn is triggered. Details are as follows

Priority: High
Host: hsn
Environment: default
Message: error when check request status for getting IMDSv2 token: http request status 400. No token in the metadata request will be used.
Alert generated time: 2023-04-17T06:52:35.578Z

Thanks & Regards,
ELK Team.

the jinja format is working for every other rule, except cpu and memory, does anyone have any idea, help would be appreciated.

Thanks & regards,
Ram
