### DISCUSSION TITLE
frequency rule triggers even though threshold hasn't been reached

### DISCUSSION THREAD

**Discussion by tomfotherby** [jertel/elastalert2#1163] [Q&A] [answered]
Is anyone else having issues with `frequency` rules with ElastAlert v2.10.1?

I have a rule that triggers even when `num_events` isn't reached.

My rule:

```yaml
  filebeat_errors.yaml: |-
    ---
    # Get a notification if we start having more than 25 filebeat errors within 1 hour
    # The frequency rule type alerts when num_events events occur with timeframe time
    #
    name: "Filebeat Errors"
    alert_subject: "ElastAlert: {0} [{1}]"
    alert_subject_args:
    - name
    - stage
    type: frequency
    num_events: 25
    timeframe:
        hours: 1
    realert:
        hours: 1
    index: logstash-*
    filter:
    - query:
        query_string:
            query: "kubernetes.container.name:filebeat AND message:ERROR"
    alert:
    - "sns"
    sns_topic_arn: "arn:aws:sns:us-east-1:REDACTED:ElastAlert"
```

I'm getting alerts that are confusing me. Here's an example:

```
Filebeat Errors

At least 25 events occurred between 2023-04-17 05:54 UTC and 2023-04-17 06:54 UTC
num_hits: 5
num_matches: 1
```

I verified via a manual Kibana query that there were only `num_hits: 5`. So I'm not-understanding why the alert triggers given that I have required `num_events: 25`.

If I do the same search in Kibana, you can see the errors are not frequent enough to trigger the `num_events: 25` threshold:

![Selection_650](https://user-images.githubusercontent.com/140179/233057132-8d97ad06-9cff-4e73-99d2-b4a0a02d0192.png)

---

The same rule works fine with a (much) older version on ElastAlert, e.g. `jertel/elastalert-docker:0.2.4`

---

This discussion seems similar to my issue: https://github.com/jertel/elastalert2/discussions/138

**Comment by jertel** [comment]
I've not seen this and without access to your Elastic data I can't offer much help. But some background information may help you get to the bottom of this: While your `timeframe` is 1h, ElastAlert 2 typically runs much more frequently than that. It accumulates matches into a memory buffer and on each run it looks at the buffer to see if there are enough accumulated matches over the specified `timerange` that exceeds the `num_events` threshold. So while the log line shows only `1` match, I would expect that the previous runs had already found 24 matches and so it now has enough to trigger the alert.

**Comment by fberrez** [comment]
I have the same issue. Here is my rule:
```yml
name: myRule
description: Sends alerts on flatline
index: myIndex
type: flatline
use_count_query: true
timeframe:
  minutes: 5
threshold: 1

filter:
  - query:
      query_string:
        query: 'fields.metadata.entity: myEntity AND fields.metadata.code: myCode'

# Sets a time interval between two alerts of a same entity
realert:
  minutes: 1
```

And my kibana result: 
![image](https://github.com/jertel/elastalert2/assets/25006376/d5a73ec0-d1ed-425d-b1d4-ac008494ce6b)

We can see that I have one log every single minute. Meanwhile, the alert is triggered (flatline less than 1 in a timeframe of 5 minutes). The interesting thing is the alert is triggered when I set my elastalert config as:

```yml
run_every:
  minutes: 1

buffer_time:
  minutes: 10
```

But the alert will be triggered only if the flatline is confirmed (i.e no log at all in the last 5 minutes, the rule works as expected), when I change it to:

```yml
run_every:
  minutes: 3

buffer_time:
  minutes: 10
```

So I'm wondering if it's related to the bug found by @tomfotherby.
By the way, I'm not sure to fully understand what you mean when you've written your last sentence: `So while the log line shows only 1 match, I would expect that the previous runs had already found 24 matches and so it now has enough to trigger the alert.`. If you could take some time to explain it, that would be awesome. Thanks!
