### DISCUSSION TITLE
Elastalert Regular Expression Syntax

### DISCUSSION THREAD

**Discussion by BeeruxBash** [jertel/elastalert2#1164] [Q&A] [answered]
Hi Folks, Hope you are doing well!

I have created the following Elastalert rule to detect Powershell Launch using Regex pattern enclosed within / / to escape the slashes and match the keyword Powershell if it appears anywhere in the following fields:
```

name: PowerShell Launch
type: any
index: wazuh-archives-4.*
filter:
- query:
    query_string:
      query: "data.win.system.eventID: 1 AND (data.win.eventdata.processName: /\\\\powershell/ OR data.win.eventdata.image:  /\\\\powershell/ OR data.win.eventdata.parentImage: /\\\\powershell/)" 

alert:
- slack

slack:
slack_webhook_url: https://hooks.slack.com/services/fvZpoKuyr52IMq8h8SjH3ySK

```

The fields contain data in the following format:

<html>
<body>

data.win.eventdata.image | C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe
-- | --

</body>
</html>

But whenever I run the rule it is loaded perfectly fine but no hits are being generated for it even though alerts of Powershell being launched are available even in today's date. Kindly suggest a solution to this if the query is wrong as I have a number of other rules in which I am trying to match Regex pattern to the fields in the same way.
Thanks for you time
