### DISCUSSION TITLE
Help: My wildcard filter doesn't seem to be working and not sure why

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#1172] [Q&A] [answered]
This is my filter:

```
filter:
- query:
    bool:
      must:
        - match:
            winlog.event_id: 4624
        - terms:
            winlog.event_data.LogonType: ["2", "7", "10"]
      must_not:
        - wildcard:
            winlog.event_data.TargetUserName: "DWM-*"
        - wildcard:
            winlog.event_data.TargetUserName: "UMFD-*"
```

It's working as intended except for the fact the undesired wildcard values are getting alerted on (for instance DWM-2 or UMFD-10). Any idea how to change the filter to drop these wildcard values?
