### DISCUSSION TITLE
rule type spike_aggregation script doesn't work as expect

### DISCUSSION THREAD

**Discussion by bakerLecter** [jertel/elastalert2#1173] [Q&A] [answered]
I trying to calculate two metrics values in one rules in order to alert the problem between the gateway and backend. 

I have some customize modules for elastalert to sent alert but I don't think that is the problem comes from.

This is the most important part of my alert.

rule yaml:
```
type: spike_aggregation

timeframe:
  minutes: 5

metric_agg_key: realtime
metric_agg_script:
    script: doc['upstreamtime'].value * 1000000 / doc['responsetime'].value
metric_agg_type: 'avg'
spike_height: 1
spike_type: "up"
threshold_cur: 1.5
```

And this rules trigger some error and the elastalert disable it automatically.

Errorlog:
```
10:23:25.262Z ERROR elastalert: elastalert:  Traceback (most recent call last):  File "/opt/elastalert/elastalert/elastalert.py", line 1235, in handle_rule_execution  num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))  File "/opt/elastalert/elastalert/elastalert.py", line 860, in run_rule  if not self.run_query(rule, tmp_endtime, endtime):  File "/opt/elastalert/elastalert/elastalert.py", line 614, in run_query  rule_inst.add_aggregation_data(data)  File "/opt/elastalert/elastalert/ruletypes.py", line 1198, in add_aggregation_data  self.handle_event(event, agg_value, 'all')  File "/opt/elastalert/elastalert/ruletypes.py", line 473, in handle_event  self.cur_windows[qk].append((event, count))  File "/opt/elastalert/elastalert/ruletypes.py", line 313, in append  self.running_count += event[1] TypeError: unsupported operand type(s) for +=: 'int' and 'str'
10:23:25.262Z ERROR elastalert: elastalert:  Uncaught exception running rule gateway_upstream_response_time_spike_test: unsupported operand type(s) for +=: 'int' and 'str'
```

I read some discussion but some of them is bug and fixed in latest version elastalert2. 
The elastalert2 version of my is 2.11.0.
I run this elastalert2 by docker and build it with dockerfile from https://github.com/Karql/elastalert2-server
Maybe I using the script in the wrong way? Any answer will thankful.

**Comment by jertel** [comment, marked as answer]
Turn on debug logging for ElastAlert 2 and check on the response from Elasticsearch for the rule query. Since it's complaining about trying to add a string value to an integer value, it leads me to believe that your inline script math may be failing (perhaps a document's field is missing) and instead of returning a number, it is returning an error string.

**Reply by bakerLecter** [reply]
your guessing is right. It return NaN so error pop out.

```
2023-05-04 14:28:11,969     INFO        elasticsearch POST {data}/_search?ignore_unavailable=true&size=0 [status:200 request:0.305s]
2023-05-04 14:28:11,969    DEBUG        elasticsearch > {"query":{"bool":{"filter":{"bool":{"must":[{"range":{"@timestamp":{"gt":"2023-05-04T06:22:11.132846Z","lte":"2023-05-04T06:27:11.132846Z"}}},{"query_string":{"query":"{data}"}}]}}}},"aggs":{"metric_realtime_avg":{"avg":{"script":"doc['upstreamtime'].value * 1000000 / doc['responsetime'].value"}}}}
2023-05-04 14:28:11,969    DEBUG        elasticsearch < {"took":283,"timed_out":false,"_shards":{"total":2240,"successful":2240,"skipped":2202,"failed":0},"hits":{"total":{"value":10000,"relation":"gte"},"max_score":null,"hits":[]},"aggregations":{"metric_realtime_avg":{"value":"NaN"}}}
```

And I found some data from es sometimes will be zero. Could I use such script like this? 
`doc['upstreamtime'].value != 0 ?  doc['responsetime'].value / (1000000 * doc['upstreamtime'].value) : 1
`

**Reply by bakerLecter** [reply]
Is is correct that the alert should be trigger by the value of 'metric_agg_key' after it was calculated by script field?

```
type: spike_aggregation

timeframe:
  minutes: 5

metric_agg_key: realtime
metric_agg_script:
    script: "doc['upstreamtime'].value != 0 ? doc['responsetime'].value / (1000000 * doc['upstreamtime'].value) : 1;"
metric_agg_type: 'avg'
spike_height: 1
spike_type: "up"
threshold_cur: 0.7
threshold_ref: 1.5
```
