### DISCUSSION TITLE
`metric_agg_type: percentiles` and `min_doc_count` to only alert when at least `min_doc_count` records in bucket

### DISCUSSION THREAD

**Discussion by BlakeSearlSonocent** [jertel/elastalert2#1175] [Q&A] [answered]
Hi, I'm trying to build a set of alerts for some performance metrics. I've built them so that you can configure a threshold per metric (this could be an endpoint timing, for example). However, I'd like them to only alert if there have been `> x` records for the metric in a given time. 

I've tried to do this by setting a `min_doc_count: x`, combined with a `query_key` but as soon as I do this, the alert is not triggered.

Here is a stripped down version of the config that I've been using for testing (using terraform `templatefile` to inject the variables for the various metrics). If I remove the `query_key`, then the alerts are triggered, but it doesn't seem to obey the `min_doc_count`.

```
name: Performance - ${METRIC_NAME}
type: metric_aggregation
index: filebeat-*
metric_agg_type: percentiles
metric_agg_key: duration
percentile_range: 90
bucket_interval:
  minutes: 1
buffer_time:
  minutes: 1
sync_bucket_interval: true
max_threshold: ${METRIC_THRESHOLD}
query_key: metricType
min_doc_count: 1
filter:
  - query:
      query_string:
        query: "metricType: ${METRIC_TYPE}"
alert:
  ...<alert that sends to slack>
```

Wondering if I'm missing something here.

This is `elastalert2:2.10.1` deployed with helm

Thanks in advance!
