### DISCUSSION TITLE
After editing my filter, doesn't seem to be picking up hits

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#1177] [Q&A] [answered]
This is my new filter:

```
filter:
- query:
    bool:
      must:
      - match:
          winlog.event_id: '4624'
        terms:
          winlog.event_data.LogonType: ['2', '7', '10']
      must_not:
        terms:
          winlog.event_data.TargetUserName: ['DWM-1', 'DWM-2', 'DWM-3', 'DWM-4', 'DWM-5']
```
Not sure what's wrong with it if you can help!
