### DISCUSSION TITLE
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_time] of type [date]

### DISCUSSION THREAD

**Discussion by SadCasual** [jertel/elastalert2#1202] [Q&A] [answered]
hi,@jertel
I can't writing alert info to Elasticsearch,error:
`ERROR:elastalert:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_time] of type [date] in document with id 'm1SBrogBtnTvAA3RT-Yj'. Preview of field's value: '2023-06-12 15:24 CST'")
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_time] of type [date] in document with id 'm1SBrogBtnTvAA3RT-Yj'. Preview of field's value: '2023-06-12 15:24 CST'")`

![企业微信截图_16865552688271](https://github.com/jertel/elastalert2/assets/96720269/b9a59de2-b792-4901-b77d-9fbe0e4201a0)

index elastalert_status  mappings:
![企业微信截图_16865553139910](https://github.com/jertel/elastalert2/assets/96720269/775926e4-d469-4748-bcae-35da23fa995c)

please help me!thinks!!!

**Comment by SadCasual** [comment]
my config,yaml:
```yaml
rules_folder: /opt/elastalert2/elastalert2-2.11.0/examples/rules
run_every:
  seconds: 30
buffer_time:
  minutes: 15
es_host: 
es_port: 9200
use_ssl: True
verify_certs: True
ca_certs: /etc/kibana/certs/ca/ca.crt
ssl_show_warn: False
es_username: 
es_password:
writeback_index: elastalert_status
alert_time_limit:
  days: 2
custom_pretty_ts_format: '%Y-%m-%d %H:%M'
use_local_time: true
```
