### DISCUSSION TITLE
Best way to add smtp settings to config.yaml when using helm chart

### DISCUSSION THREAD

**Discussion by pboushy** [jertel/elastalert2#1213] [Q&A]
The documentation and values.yaml have some good data on how to add the smtp auth info, but I don't see any info about how to actually add the smtp_host, smtp_port, smtp_tls, and from_addr into config.yaml

It looks to me like the easiest way to add it under extraConfigOptions in the answers.yaml:
```
extraConfigOptions:
  smtp_host: smtp.example.com
  smtp_port: 587
  smtp_tls: "true"
  from_addr: "donotreply@example.com"
```

Is that the current easiest method?
