### DISCUSSION TITLE
Frequency of certain doc_type and num_hits

### DISCUSSION THREAD

**Discussion by niek1992** [jertel/elastalert2#1217] [Q&A] [answered]
Hi all,

I'm trying to get a frequency rule working whilst also using `use_count_query` but haven't managed to create a proper rule that works for me. Have Googled for a couple of days now but nothing that helped me achieve what i want. Found some links [num_hits vs num_matches](https://github.com/Yelp/elastalert/issues/1261) and [confused by num_hits] 
 (https://github.com/jertel/elastalert2/discussions/579) but weren't helpfull.

Below is my ElastAlert config:

```
---
rules_folder: /opt/elastalert/rules

run_every:
  seconds: 30
timeframe:
  seconds: 30

buffer_time:
  minutes: 5

writeback_index: elastalert_status
writeback_alias: elastalert_alerts

alert_time_limit:
  seconds: 120

max_query_size: 1000

es_host: <REDACTED IP>
es_port: 9200
es_username: "elastic"
es_password: "<REDACTED>"
```

The rule i currently have that works for what i want to do:

```
---
name: frequency-documents
type: frequency

timeframe:
  minutes: 60

buffer_time:
  minutes: 60

use_count_query: false
doc_type: _doc

num_events: 1

index: logstash-*-log-*

alert:
  - command
command:
  - "python"
  - "/opt/elastalert/scripts/write-textfile-metrics-python2.py"
  - "arg2"
  - "arg3"
  - "arg4"
  - "frequency-documents"
  - " %(num_hits)s"
```

As the result of `elastalert-test-rule` is the following:

```
...
num_hits: 2400
num_matches: 2400
...
```

And while this works for the test environment i've setup (2000 _doc count), i'm planning to use this in production where there are usually 50K _doc count per 60 minutes. Therefore i'd like to use `use_count_query` as i'm only interested in the count of the docs, not the fields of them.

But when i configure `use_count_query` like i want to and use the following rule:

```
---
name: frequency-documents
type: frequency

timeframe:
  minutes: 60

use_count_query: true
doc_type: _doc

num_events: 1

index: logstash-*-log-*

alert:
  - command
command:
 - "python"
  - "/opt/elastalert/scripts/write-textfile-metrics-python2.py"
  - "arg2"
  - "arg3"
  - "arg4"
  - "frequency-documents"
  - " %(num_hits)s"

```

I get:

```
...
At least 1 events occurred between 2023-07-13 09:36 UTC and 2023-07-13 10:36 UTC

@timestamp: 2023-07-13T10:36:07.587155Z
num_hits: 2135
num_matches: 121
...
```

So while i understand that matches are the actual documents that matches my rule, i don't understand that when i access num_hits i get a rather low number. That number stays the same if i use `use_count_query: false` and do not set buffer_time to 60. Meaning it'll only look to the last 5 minutes (for which 121 seems reasonable). 

Unfortunately setting buffer_time does not seem to work here, e.g. it does not yield the same amount of `num_matches` as `num_hits`. I also tried to configure `realert: minutes: 0` but that just means it'll run the alert multiple times, which isn't something i want to achieve. I want it to run every 30 seconds (or 1 minute, as that's the scrape interval configured by Prometheus) and report the _doc count in that index.

Could someone give me some pointers on how to properly configure this? Do i need `type: metric_aggregation` in combination with value_count? Which value should i then pass to my Python script?

Thanks in advance,

Niek
