### DISCUSSION TITLE
rule can not hit the field

### DISCUSSION THREAD

**Discussion by j66321** [jertel/elastalert2#1225] [Q&A] [answered]
Hello, i'm newbe to the elastalert2.
Using elasticsearch 8.7.1, and docker jertel/elastalert2:latest for these days.
Write down the rule below.
```
name: "hash-prd-abc-user-count-alert"
type: "any"
index: "hash-prd-abc*"
timestamp_field: "@timestamp"
timestamp_type: "iso"
use_strftime_index: false
query_timezone: Asia/Taipei
filter:
  - range:
      game_user_count:
        from: 15
        to: 1799
realert:
  minutes: 5
alert:
  - "slack"
alert_subject: "WARN : {} {} user count alert"
alert_subject_args:
  - fields.production
  - fields.role
alert_text_type: alert_text_only
alert_text: |
  Production: {}
  Game: {}
  User Count: {}
alert_text_args:
  - fields.production
  - fields.role
  - game_user_count
slack_webhook_url: 'https://hooks.slack.com/services/ccc/666/abc'
slack_msg_color: "warning"
slack_username_override: "elastalert2"
slack_channel_override: "@JimPan"
slack_emoji_override: ":scream:"
``` 

With above rule, elastalert still no hit and send the slack to me.
I try to use "elastalert-test-rule" in docker to find out the root cause.
And it show me the list do not contain the "game_user_count"
<img width="506" alt="image" src="https://github.com/jertel/elastalert2/assets/61723194/e202d8bc-9fa3-4a47-a7a8-da46d1bd59d7">

From kibana dataview, i can find the field "game_user_count"
<img width="730" alt="image" src="https://github.com/jertel/elastalert2/assets/61723194/ed40f575-eaff-482d-944e-d562e743cc13">

And with dev tools.
```
{
"_index": "hash-prd-abc-2023.07.27",
"_id": "oO0dsfsdf2RF",
"_score": 2.273698,
"_source": {
"fields": {
"env": "prd",
"role": "msdf",
"production": "hash"
},
"@timestamp": "2023-07-27T02:04:39.029Z",
"log": {
"offset": 61704549,
"file": {
"path": "/var/log/Minsdferver1/Minessdfver.log"
}
},
"msg": "[Table] [桌台 [M01] 第 [] 局 狀態 [下注]] process done 目前桌台連線人數: 10 / 9",
"level": "info",
"time": "2023-07-27 10:04:38:158",
"caller": "task/task_table_process.go:72",
"agent": {
"id": "39e5c65sdfsf3275c4be4",
"name": "9e01sdf355",
"type": "filebeat",
"version": "8.7.1",
"ephemeral_id": "92e7141sdfsdf022fbe0b"
},
"host": {
"name": "9e0193675355"
},
"game_user_count": "10",
"tags": [
"beats_input_codec_json_applied",
"_geoip_lookup_failure"
],
"event": {
"original": """{"level":"info","time":"2023-07-27 10:04:38:158","caller":"task/task_table_process.go:72","msg":"[Table] [桌台 [M01] 第 [] 局 狀態 [下注]] process done 目前桌台連線人數: 10 / 9"}"""
},
"@version": "1",
"ecs": {
"version": "8.0.0"
}
}
}
``` 

Since "game_user_count" was parse from "msg" by logstash.
I'm not sure this customize field will interfere the search by elastalert2.
Looks like the rule i wrote can not find the field "game_user_count".
Is there any solution i could solve this? 
Thank you.
