### DISCUSSION TITLE
Automated Alert Based on keywords match from message field failed

### DISCUSSION THREAD

**Discussion by zibuyule** [jertel/elastalert2#1229] [Q&A] [answered]
Hi,

1.  Manually execute the command to trigger the email alarm successfully.
2. Automated Alert Based on keywords match from message field failed.

Post the yaml of the generated rules here
```
apiVersion: v1
kind: Secret
metadata:
  name: elastalert-rules-secret
type: Opaque
stringData:
   rule_1: |-
     name: Rule 1
     type: frequency
     index: filebeat-*
     num_events: 1
     timeframe:
       minutes: 1
     realert:
        minutes: 0
     filter:
     - query:
         wildcard:
           message: "*test.jpg*"
     alert:
     - "email"
     smtp_auth_file: "/opt/elastalert/config-smtp/smtp_auth.yaml"
     email:
     - "willsunny3@163.com"
     smtp_host: "smtp.163.com" 
     smtp_port: 465
     smtp_ssl: true
     email_reply_to: "willsunny3@163.com"
     from_addr: "willsunny3@163.com"
     notify_email: "willsunny3@163.com"
     run_every:
       minutes: 1
     disable_rules_on_error: true
```

![test](https://github.com/jertel/elastalert2/assets/5792519/9d209744-4f83-4a35-b01e-e83d939f15e6)

When I add the _--alert_ parameter, it will send an email matching the message of test.jpg to my mailbox willsunny3@163.com.
`elastalert-test-rule rules/rule_1.yaml --config config.yaml  --alert`

But when a new log containing test.jpg is generated, it will not automatically send an alarm email, no matter how long it takes, unless I execute the command above manually.

**Comment by jertel** [comment]
You will need to enable debug logging and review the outcome of each rule run to determine why it's not triggering the alert.

**Reply by zibuyule** [reply]
Hello. I used the helm chart to install it. There is no elastalert2 startup command in the entire chart, and there is no debug configuration item.
Can you tell me how to configure debug mode?

**Reply by jertel** [reply, marked as answer]
Two methods: 

1. Add `args` parameter to your value overrides as discussed in #1086.

2. Add extraConfigOptions parameter to your value overrides:
```
extraConfigOptions: |
  logging:
   version: 1
   incremental: false
   disable_existing_loggers: false
   formatters:
     logline:
       format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'
  
   handlers:
     console:
       class: logging.StreamHandler
       formatter: logline
       level: DEBUG
       stream: ext://sys.stderr
    
   loggers:
     elastalert:
       level: DEBUG
       handlers: []
       propagate: true
  
     elasticsearch:
       level: DEBUG
       handlers: []
       propagate: true
  
     elasticsearch.trace:
       level: DEBUG
       handlers: []
       propagate: true
  
     '':  # root logger
       level: DEBUG
       handlers:
         - console
       propagate: false
```
