### DISCUSSION TITLE
[HELP Elastalert2] How to get the alert email notification address from an external file

### DISCUSSION THREAD

**Discussion by yuuta8821** [jertel/elastalert2#1230] [Q&A] [answered]
Hello from Japan.
I am an inexperienced Japanese engineer with Elastalert.
I have a question for all you respected engineers.

I am using Elastalert2 to build a mechanism to send an alert email when a specified phrase is detected in the index collected by ElasticSearch.
Right now, I'm specifying the e-mail address of the destination of the alert e-mail by writing it directly in the rule file.
In the future, we would like to build a mechanism to acquire this e-mail address from an external file.

Is it possible to use Elastalert2 to handle the email address of the alert email destination as an arbitrary variable?
In addition, I would appreciate it if you could tell me the location of the external file, the file format, the setting method, etc.

I am attaching my Elastalert2 rule file for the sample.
I need your help.
thank you

```
name: nofitication.yml

type: any

index: winlogbeat-7.6.2-*

filter:
- query:
   query_string:
    query: "message:"

alert:
- "email"
email:
- "example@email.com"

# (required, email specific)
# a list of email addresses to send alerts to
from_addr: "nofitication@email.com"
smtp_host: **
smtp_port:  **
smtp_ssl: true
alert_subject: "alert email"
alert_text_type: alert_text_jinja
alert_text: 

```
