### DISCUSSION TITLE
Use secrets to store wehbook urls [ Kubernetes ]

### DISCUSSION THREAD

**Discussion by mehrdad-khojastefar** [jertel/elastalert2#1241] [Ideas]
For security reasons I want to store my webhook urls in a secret. Is it possible now ? I've read through the chart and it seems like it is not. 
So are there any points to consider for this feature because  if not I would be happy to develop it.
And it would be great if you share your ideas too.

**Comment by jertel** [comment]
If you're asking about a method of storing most of the rule content in configMaps but then having some sensitive data omitted from the rule configMap and instead placed in a secret, the answer is no, it's not supported. If you'd like to store the entire rule in a k8s secret then that is supported via the `secretRulesName` configuration value.

As I don't know what you're trying to protect I can't offer ideas on improvement. 

For example, your recent PR suggests you are storing rules locally in your chart subdirectory. And then at deploy time you are now reading those local rules and generating a large configMap which is then stored in the k8s cluster. So if you're wanting to keep the webhooks out of the local rule files but you're ok with having the webhook be in the k8s configMap then that requires a specific solution that is more suited for the Helm template syntax.

However, if you are not concerned with webhooks being in your local rule files prior to deployment, but instead are more concerned with not having webhooks be stored in a configMap inside the k8s cluster, then that requires a different solution. You could store the entire rule in a secret, instead of a configMap, to solve that.

**Comment by mehrdad-khojastefar** [comment]
```
name: ADMIN_LOGIN_FAILED
type: any
index: aduit
timestamp_field: timestamp
realert:
  minutes: 0
filter:
  - term:
      event.keyword: "ADMIN_FAILED"
alert:
- "rocketchat"
alert_text_type: alert_text_only
alert_subject: "admin login failure - #{}"
alert_subject_args:
  - username
alert_text: |-
  {{ "username": "{}" "timestamp": "{}", "rule_key": "ADMIN_FAILED" }}
alert_text_args:
  - username
  - timestamp
```

this is one of our rules, now in the alert section we defined rocketchat and I would like to store this rocket chat webhook in a secret. 
the webhook is defined in the values.yaml now and it is a security concern for us at the moment.
```
extraConfigOptions:
  discord_webhook_url: https://discord.com/api/webhooks/...
  rocket_chat_webhook_url: https://chat.rocket.com/hooks/...
  ```
  and then in the config.yaml we have 
  ```
...
{{- if .Values.extraConfigOptions }}
{{ toYaml .Values.extraConfigOptions | indent 4 }}
{{- end }}
...
```
It would be very convenient I guess to store each webhook in a secret 
I am aware that we can create a secret config but the problem with that method is that we have more than one tool that need the rocket chat webhook. so we are trying to use vault and store each webhook in a secret and have our applications read from the vault.
