### DISCUSSION TITLE
Please help with blacklist.yml not bootable state

### DISCUSSION THREAD

**Discussion by yuuta8821** [jertel/elastalert2#1246] [Q&A] [answered]
Hello from Japan
I am an inexperienced Japanese engineer at Elastalert.
I would appreciate it if you could share your wisdom regarding rule files.
https://readthedocs.org/projects/elastalert/downloads/pdf/latest/

I created the following Blacklist rule file with reference to the official document of Elastalert.
I created a rule file that sends an alert email when Elastalert finds a specific sentence in Elasticsearch index data.

The specific rule file is below

```
# Rule name, must be unique
name: Blacklist rule
type: blacklist
index: my-elasticsearch-index
compare_key: message
filter:
- query:
    query_string:
      query: "message:*ERROR*"
```

However, Elastalert will not start if this blacklist.yml is read.
*※I am ready to provide error messages at startup, but the error messages starting with Traceback are so huge that it is difficult to share them here. 
I need help with this situation.
Please help me.
