### DISCUSSION TITLE
Most effeciant aggregation.

### DISCUSSION THREAD

**Discussion by alicemara** [jertel/elastalert2#1267] [Q&A] [answered]
I was curious if anyone had suggestions for streamlining a rule I created!

I have this rule that I created with the goals of querying overnight and sending an alert in the morning.
Ideally it looks over the data from the last week, and takes advantage of elastalert's result silencing to only alert on new results.
The goal is to have some resiliency so if it goes down for a day or two we don't miss anything.

My config is set to run once a day:
```
run_every:
  days: 1

buffer_time:
  days: 1
```
And my rule looks like this:
```
name: example
type: any
index: 123*
num_events: 1
limit_execution: "* 5-12 * * *"
timeframe:
  days: 7
aggregation:
  schedule: '0 16 * * *'
```
Thank you for any/all suggestions and advice!
