### DISCUSSION TITLE
Sending Alert to Microsoft Teams

### DISCUSSION THREAD

**Discussion by ghost** [jertel/elastalert2#1269] [Q&A] [answered]
Hello everyone 

I tried integrating Ms teams with elastalert of metricbeat data i have made it successfull but having issue in posting messae even thou i have added parameters only to post but whole wuery got from metricbeat is posted in mty teams 

here by i am attaching the files and output i got TIA

<img width="520" alt="Screenshot 2023-09-19 at 5 33 51 PM" src="https://github.com/jertel/elastalert2/assets/106295071/71179240-98bb-4b6b-be20-377aedeb9d89">
<img width="1406" alt="Screenshot 2023-09-18 at 9 50 36 PM" src="https://github.com/jertel/elastalert2/assets/106295071/4c69043e-54a1-4ba1-9b10-dde924e5d06f">

**Comment by ghost** [comment]
@jertel

**Reply by jertel** [reply]
I don't understand what you're asking. Please do not attach Word documents. You can attach screenshots directly by pasting into a comment.

**Reply by ghost** [reply]
I was trying to send notification from elastalert to ms teams and i want only few parameters should be posted in Ms teams so that i have made configuration as in the above image but i am getting alert in teams which is irrelevent to my configuration 

I want elastalert to post only server name, mount point,used space and mount type but elastalert sending data to teans in above format which are attached in as images 2

**Reply by jertel** [reply, marked as answer]
Why are you specifying `msteams_data:` and `msteams_message`? I don't see either of those in the ElastAlert 2 [documentation](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#microsoft-teams). Please let me know where you found those references so they can be removed/corrected.


```
name: Disk Usage Alert

... add your query filter, etc here ...

alert_text_type: aggregation_summary_only
ms_teams_alert_summary: Disk Usage is above threshold
ms_teams_alert_facts:
- name: Server
  value: my_server_field_name
- name: IP
  value: my_ip_field_name
- etc
```
