### DISCUSSION TITLE
spike with field_value does not work

### DISCUSSION THREAD

**Discussion by Cheney-77** [jertel/elastalert2#1281] [Q&A] [answered]
i want to monitor if  the host processes grow too fast,
at the beginning,host process like this:
![1695806894324](https://github.com/jertel/elastalert2/assets/39728340/6803625d-05b2-48a0-9fdf-f90f1be537b1)
then i use a python script to add 1024 processes,last for 5 min:
![image](https://github.com/jertel/elastalert2/assets/39728340/9817d99b-2757-42a2-9b6b-b0ddf877c1c7)
after that ,my host process like this:
![image](https://github.com/jertel/elastalert2/assets/39728340/d0819604-954c-42ff-b5ca-10997af89350)

i write a rule to like this:
![image](https://github.com/jertel/elastalert2/assets/39728340/1a9105d1-c6e6-4044-978d-70299ab764db)
why the rule does not trigger?

**Comment by Cheney-77** [comment]
any problem with my rule yaml?

**Comment by jertel** [comment]
Including the debug logs would help us help you.

**Reply by Cheney-77** [reply]
ok,sir,i run the alert server by docker container,the run command like this:
![image](https://github.com/jertel/elastalert2/assets/39728340/a419669e-68ea-490e-bd19-fd89067c216b)
after i ran the python script, the docker container log like this:
![image](https://github.com/jertel/elastalert2/assets/39728340/bb12023d-11ba-4659-bf61-186781bcc96e)
from the kibana dashboard,we can see last 5min,the process increse a lot:
![image](https://github.com/jertel/elastalert2/assets/39728340/20fd17d1-fbdc-4790-9eb8-17e2b0b7d22b)

**Reply by Cheney-77** [reply]
the log shows 0 matches , 0 alerts

**Reply by jertel** [reply]
Please enable detailed debug by ensuring the logging parameters in your config.yaml are all set to DEBUG:

```
logging:
 version: 1
 incremental: false
 disable_existing_loggers: false
 formatters:
   logline:
     format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

 handlers:
   console:
     class: logging.StreamHandler
     formatter: logline
     level: DEBUG
     stream: ext://sys.stderr



 loggers:
   elastalert:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch.trace:
     level: DEBUG
     handlers: []
     propagate: true

   '':  # root logger
     level: DEBUG
     handlers:
       - console
     propagate: false
```

Specifically, with the logs covering the timeframe just before and after when the spike hits.
