### DISCUSSION TITLE
Something wrong with the rules

### DISCUSSION THREAD

**Discussion by baiyibing123** [jertel/elastalert2#1298] [Q&A] [answered]
name: nginx
type: frequency
index: nginx
filter:
- query:
    query_string:
      query: "status: (501 OR 502 OR 503 OR 504 OR 500)"
num_events: 100
timeframe:
    minutes: 1
alert:
- "elastalert_modules.feishu_alert.FeiShuAlerter"

feishu_webhook: "xxx"
feishu_msgtype: "text"

alert_text: |
    kibana_url: "xxx"
    http_host: {}
    request_uri: {}
    status: {}
    _id: {}
    alarm_reason: "1分钟内{}条日志出现报错"
alert_text_args:
    - http_host
    - request_uri
    - status
    - _id
    - num_matches
alert_text_type: alert_text_only

These are my rules, I think the alarm should only be triggered if num_matches is greater than 100, but when the alarm comes out, I find the value of num_matches is 1

![image](https://github.com/jertel/elastalert2/assets/14048464/242732cc-5900-4417-9d0a-04e3afa03fac)

**Comment by jertel** [comment]
Please see #11 and reformat your question/rule so its indentation and syntax is accurately represented.

**Reply by baiyibing123** [reply]
```
name: nginx_feishu
type: frequency
index: nginx
filter:
- query:
    query_string:
      query: "status: (501 OR 502 OR 503 OR 504 OR 500)"
num_events: 100
timeframe:
    minutes: 1
include: ["fields.kafka_topic","http_host","request_uri","status"]    
alert:
- "elastalert_modules.feishu_alert.FeiShuAlerter"

feishu_webhook: "xxx"
feishu_msgtype: "text"

alert_text: |
    kibana_url: "xxx"
    fields.kafka_topic: {}
    http_host: {}
    request_uri: {}
    status: {}
    _id: {}
    alarm_reason: "1分钟内{}条日志出现报错"
alert_text_args:
    - fields.kafka_topic
    - http_host
    - request_uri
    - status
    - _id
    # - num_hits
    - num_matches
alert_text_type: alert_text_only
```
