### DISCUSSION TITLE
Elastalert2 trigger alert when there is No any data in elastic search index

### DISCUSSION THREAD

**Discussion by Raushi007** [jertel/elastalert2#1306] [Q&A] [answered]
If there is no data in the Elasticsearch index, alert through ElastAlert2. I am using Elasticsearch version 8. I have tried the flatline type but it’s not working. If anyone has a sample configuration, please help

**Comment by jertel** [comment]
This is a working flatline rule that alerts when there is no record containing a field named `blah` with the value of `test`, in any index.

```
name: flatline_test_rule
type: flatline
index: "*"
filter:
- query:
    query_string:
      query: 'blah: test'
threshold: 1
timeframe:
  seconds: 20
alert:
- debug
realert:
  minutes: 1
```

**Reply by Raushi007** [reply, marked as answer]
Hi Jertel,
Thanks for prompt response
I have used this configuration

```
name: flatline_test_rule
type: flatline
index: "filebeat*"
filter:
- query:
    query_string:
      query: "*"
threshold: 1
timeframe:
  minutes: 1
realert: 
    minutes: 5
alert_text_type:  there is no data index {{match}} 
alert:
- ''slack"
```

But what I have observed is that it's matching even if I have passed 'index: "pilebeat*"'.
I have changed the spelling but it's still matching the event.
I have checked the logs but not found why it's triggering.
Additionally, I have so many indexes, so I want to send an alert with the index name.
So, if my index has no data, how can I send the index name dynamically in 'alert_text'?
