### DISCUSSION TITLE
No matches in Spike Aggregation

### DISCUSSION THREAD

**Discussion by shaigbdb** [jertel/elastalert2#1309] [Q&A] [answered]
I'm trying to create a spike aggregation down rule for the last 30 minutes period compared to the respective period on the previous day.

I wrote a filter to filter out everything except those two 30 minutes periods, which if I understand correctly, should allow me to compare them when the current and reference windows are 1 day long. The query works, and I do see hits in the log, but no matches. I’m also getting results for the buckets when running in Elasticsearch, and I can see the difference when comparing the time windows in Elasticsearch.

I’ve tried both up and down spikes, none of them match (even after decreasing the spike height to a very small size)

I've turned on the debug log - the two queries that appear for each run of the rule look identical, including the range filter.

Any help would be appreciated.
```

name: Verify Down Spike
type: spike_aggregation
index: indices-*
doc_type: _doc
timestamp_type: unix_ms
filter:
  - query:
      query_string:
        query: "(@timestamp:[now-1d-30m TO now]) AND NOT (@timestamp:[now-1d TO now-30m])"
spike_height: 1.001
spike_type: down
metric_agg_type: value_count
metric_agg_key: _id
query_key: ["field1.keyword", "field2.keyword"]
timeframe:
  days: 1
buffer_time:
  days: 1
alert:
- "slack"
alert_on_new_data: true

```
possibly Relevant config.yaml settings:

```
run_every:
  minutes: 1
old_query_limit:
  minutes: 0
buffer_time:
  days: 1
alert_time_limit:
  days: 2
scan_entire_timeframe: true
```

query as it appears in the log:

```

{
  "aggs": {
    "bucket_aggs": {
      "aggs": {
        "bucket_aggs": {
          "aggs": {
            "metric__id_value_count": {
              "value_count": {
                "field": "_id"
              }
            }
          },
          "terms": {
            "field": "field1.keyword",
            "min_doc_count": 1,
            "size": 50
          }
        }
      },
      "terms": {
        "field": "field2.keyword",
        "min_doc_count": 1,
        "size": 50
      }
    }
  },
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": 1699813095000,
                  "lte": 1699899495000
                }
              }
            },
            {
              "query_string": {
                "query": "(@timestamp:[now-1d-30m TO now]) AND NOT (@timestamp:[now-1d TO now-30m])"
              }
            }
          ]
        }
      }
    }
  }
}
```
