### DISCUSSION TITLE
How to send all warnings at once via http_post2

### DISCUSSION THREAD

**Discussion by huangyutongs** [jertel/elastalert2#1314] [Q&A] [answered]
I tried aggregation, and the result was that when there were two messages matching, it was sent twice after waiting for the aggregation time. How to aggregate the contents of the two alerts together and only send them once?
I don't know if I missed something.

this is my message
```
{
   "@timestamp": "2023-11-23T07:12:11.640Z",
   "message": "Message 11",
   "level": "Error",
   "url": "/api/app/pda-ddd/1",
   "name": {
      "first": "Zachary523",
      "last": "Tong51"
      },
   "fields": {
     "RequestPath": "/"
   }
}
```
config.yaml
```
rules_folder: /opt/elastalert/rules

run_every:
  seconds: 20

buffer_time:
  minutes: 15

es_host: es.baidu.cn
es_port: 80
es_username: test
es_password: test

writeback_index: elastalert_status_test

alert_time_limit:
  days: 2

use_ssl: False
verify_certs: False
```
rules/a.yaml
```
name: library
type: frequency
index: library*

num_events: 1
timeframe:
  minutes: 15

aggregation:
  seconds: 50

aggregation_key: "level"
top_count_keys: ["level"]
summary_table_fields:
  - level
filter:
  - query:
      query_string:
        query: "level: Error"

realert:
  minutes: 0

alert: post2
http_post2_url: "https://webhook.site/2b487563-0e71-40cf-b756-ddddddd"
attach_related: true
http_post2_payload: |
  {
  "level": "{{level}}",
  "message": "{{message}}"
  }
```
