### DISCUSSION TITLE
Flatline alert not showing alert_text_args in email notification

### DISCUSSION THREAD

**Discussion by Nenya2021** [jertel/elastalert2#1318] [Q&A] [answered]
Hi,

I'm new here and I'm not sure if I'm posting in the right place or in the right way. Redirections are welcome :)

I'm creating an alert to detect if one or more servers are not sending logs.

It works fine, but I can't get it to print the fields that I need ("event.created" or any other time field and "host.name") in the email notification. Both fields exist and I can check them through Kibana.

This is my code:

```
name: "MO-MET-AGNT-01: No logs from server"

type: flatline

index: metricbeat-*

threshold: 1
timeframe:
  minutes: 2

query_key: "host.name"

use_terms_query: true

filter:
- query:
    query_string:
      query: "*"

alert:
- "email"

from_addr: "mdr_xxxxx@xxxx.org"
email:
   - "soporte@xxxxx.es"

alert_subject: "MO-MET-AGNT-01: No logs from server"
email_format: html
alert_text_type: alert_text_only
alert_text_args:
  - event.created       # 0
  - host.name            # 1
alert_text: "<H1>Server {1} didn't report during the last 2 minutes</H1><br><br> Details: <br><br> {0} <b>SERVER:</b> {1} <br><br><b>Priority:</b> High</br>"
```
What's lacking here?

Thanks in advance.
