### DISCUSSION TITLE
Spike aggregation with percentile not working

### DISCUSSION THREAD

**Discussion by missaeldenadai** [jertel/elastalert2#1321] [Q&A] [answered]
Hi,

I'm trying to create an alert based on the spike of a percentile aggregation and I'm getting errors whether I set the field `metric_agg_type` with `percentile` or `percentiles`.
According to the [docs](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#rule-types), I should use `percentiles`. However, if I do so, I get a Python error saying `Cannot unpack non-iterable NoneType object`, because `percentiles` is not an expected value for `spike_check_type` and I think the reason is [this line](https://github.com/jertel/elastalert2/blob/7e60c677cbda2cd44f0bfa30d9da5bed8b35d0a6/elastalert/ruletypes.py#L451).
If, in the other hand, I use `percentile`, I get a schema validation error because I'm violating [this rule of the schema](https://github.com/jertel/elastalert2/blob/7e60c677cbda2cd44f0bfa30d9da5bed8b35d0a6/elastalert/schema.yaml#L153).

Is this an issue? Is there a way to bypass this situation?

Below is my rule configuration.
```
  payment_send_spike_latency: |-
    ---
    name: some name
    type: spike_aggregation
    index: .ds-traces-apm-default*
    filter:
      - query:
          query_string:
            query: some_query
    timeframe:
      hours: 1
    metric_agg_key: transaction.duration.us
    metric_agg_type: percentile
    percentile_range: 95
    spike_type: "up"
    spike_height: 1.5
    min_doc_count: 10
    alert: slack
    <slack alert fields>
```

Thank you.
