### DISCUSSION TITLE
Rule not triggering alerts but does with elastalert-test-rule --alert

### DISCUSSION THREAD

**Discussion by iliketurtlesyep** [jertel/elastalert2#1363] [Q&A] [answered]
Hi there.  I have the following rule that triggers when run against elastalert-test-rule --alert but doesn't otherwise:

```
name: root login
type: any
index: .ds-logs-system.auth-default-*
use_strftime_index: true
is_enabled: true

filter:
- query:
    query_string:
      query: "host.hostname: myhostname AND user.name: root AND event.action: ssh_login AND system.auth.ssh.event: Accepted"

realert:
  minutes: 0

alert:
  - "slack"

alert_subject: "root login at {} from {}"
alert_subject_args:
  - "@timestamp"
  - source.ip
alert_text: |
  Timestamp: {0}
  Source host: {1}
alert_text_args: ["@timestamp", "source.ip"]

slack_webhook_url: REDACTED
```

The logs show 0 hits and 0 seen:

```
INFO:elastalert:Queried rule root login from 2024-01-25 01:15 UTC to 2024-01-25 01:24 UTC: 0 / 0 hits
INFO:elastalert:Ran root login from 2024-01-25 01:15 UTC to 2024-01-25 01:24 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:root login range 592
```

But elastalert-test-rule shows the correct result of 13 and with '--alert' passed to it, it sends the alerts to my slack channel as you'd expect. 

```
elastalert_status - {'rule_name': 'root login', 'endtime': datetime.datetime(2024, 1, 25, 1, 21, 5, 194603, tzinfo=tzutc()), 'starttime': datetime.datetime(2024, 1, 24, 1, 21, 5, 194603, tzinfo=tzutc()), 'matches': 13, 'hits': 13, '@timestamp': datetime.datetime(2024, 1, 25, 1, 21, 9, 295511, tzinfo=tzutc()), 'time_taken': 3.8375191688537598}
```

I'm just not sure why it's working properly with elastalert-test-rule but not otherwise. Does anyone have any ideas?

Thanks!

**Comment by jertel** [comment]
Hello! The two logs are showing different time ranges: The `elastalert-test-rule` shows a 24h time range, while the normal mode log shows a 9 minute time range. If those 13 records were located prior to the 9 minute time range then it would explain why they aren't showing up.

**Reply by iliketurtlesyep** [reply]
Thanks for the reply. That's true but I was triggering events most of the day yesterday that should have gotten picked up but no alerts were ever generated. Can you think of any other reason why this might be happening?

Thanks again!

**Reply by iliketurtlesyep** [reply]
The normal run also shows 0 already seen. I'm stumped as it's the same rule so I'm not sure why `elastalert-test-rule` works properly but not the normal run.

**Reply by jertel** [reply]
I suggest turning on debug logging, startup ElastAlert 2, let it stabilize for a few minutes, assuming your run_every value is a minute or so. Then trigger the event. Start capturing the ElastAlert 2 debug logs at that point and once you see the rule run you should have the log coverage of the full Elastic query and response. This also assumes your events are very quickly ingested into ES. If there's a lag then it could take more rule run cycles for ElastAlert 2 to see the event.

Being able to compare the debug logs of both the test and non-test mode should help detect whatever difference is occurring.

**Reply by iliketurtlesyep** [reply]
Thanks again for the response. And sorry for the stupid question but how do you enable debug logging?  I uncommented the bits in the config.yaml but that didn't seem to do have any effect.  Here's what it looks like:

```
rules_folder: rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: myeshost.mydomain.com
es_port: 9200
use_ssl: True
verify_certs: True
ssl_show_warn: True
es_username: myusername
es_password: mypasswd
writeback_index: elastalert_status
alert_time_limit:
  days: 2
logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: logline
      level: DEBUG
      stream: ext://sys.stderr
  file:
      class : logging.FileHandler
      formatter: logline
      level: DEBUG
      filename: elastalert.log
```

I'm starting the docker container with the following command:

```
docker run --name elastalert -v /opt/elastalert2/config.yaml:/opt/elastalert/config.yaml -v /opt/elastalert2/rules:/opt/elastalert/rules jertel/elastalert2 --debug
```

I let is settle for a few minutes:

```
# docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS         PORTS     NAMES
1d4575853ef0   jertel/elastalert2   "/opt/elastalert/run…"   7 minutes ago   Up 7 minutes             elastalert
```

Then kicked off an SSH session which should trigger the alert at 18:20:37 UTC:

```
Fri 26 Jan 18:20:37
root@mybox [/opt/elastalert2]
# ssh root@remotehost
```

And it was indexed in ES two seconds later. The timestamp is weird to me as it says it's ```Jan 26, 2024 @ 06:20:39.000```

<img width="209" alt="image" src="https://github.com/jertel/elastalert2/assets/144930164/31dc1d92-3ebe-47a0-9a5f-f29146ddf4b0">

The elastalert logs didn't pick anything up for that time period for that rule:

```
INFO:elastalert:Skipping writing to ES: {'rule_name': 'root login', 'endtime': '2024-01-26T18:21:32.271954Z', 'starttime': '2024-01-26T18:11:59.433469Z', 'matches': 0, 'hits': 0, '@timestamp': '2024-01-26T18:21:32.335840Z', 'time_taken': 0.06387042999267578}                    
INFO:elastalert:Ran root login from 2024-01-26 18:11 UTC to 2024-01-26 18:21 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:root login range 572
```

I would imagine that if the timestamp was the issue, elastalert-test-rule wouldn't be triggering either so that might be a red herring. Although the timezone on the remote box isn't the same but would there be a difference between elastalert-test-rule's results and it running normally?

Thanks again for your help -- I really appreciate it!

**Reply by jertel** [reply]
Add this to your config, where `loggers:` should be at the same indentation level as `handlers:`.

```
 loggers:
   elastalert:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch.trace:
     level: DEBUG
     handlers: []
     propagate: true

   '':  # root logger
     level: DEBUG
     handlers:
       - console
     propagate: false
```

The rest of the info you just provided is very helpful. The times appear to match up, assuming that @timestamp field is being store/shown as UTC time. You could also try simplifying your query filter to have it look for `"*"` as the `query:` value, and see if you get hits.
