### DISCUSSION TITLE
Metadata in Alert Rule

### DISCUSSION THREAD

**Discussion by MateSousa** [jertel/elastalert2#1368] [Q&A] [answered]
Is it possible to use the metadata inside the alert rule to be sent, for example, in a curl command?

E.g.

```
rules:
  testing: |-
    ---
    es_host: 
    es_port: 
    name: testing
    type: frequency
    index: traces-apm*,apm-*,logs-apm*,metrics-apm*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - bool:
        must:
          - match_phrase:
               message: "testing"
    alert:
    - "command" 
    command: "curl -X POST 'url' -d '{\"title\":\"${metadata.@timestamp}\"}'"
```
