### DISCUSSION TITLE
is there a way to mount a persistentvolume for rules?

### DISCUSSION THREAD

**Discussion by invizus** [jertel/elastalert2#1435] [Q&A] [answered]
Before trying longhorn or other alternative I thought I could just make an easy test with pvc. However it looks more complicated. I am using helm chart provided in this repo.

I think this chart uses ConfigMaps and is not using any of persistent volumes.

My volume gets created but it does not get bound, it stays Available.

this is my pvc config:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-mount
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rules
  namespace: elastalert
  labels:
    name: elastalert2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-mount
  local:
    path: /mnt/nfs/elastalert2/rules
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rules
  namespace: elastalert
spec:
  storageClassName: local-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: elastalert2
```

**Comment by jertel** [comment]
You need to tell the chart to mount the volume using the  `extraVolumes` and `extraVolumeMounts` parameters, and then reference the volume name for the rules via the `rulesVolumeName` parameter.

**Reply by invizus** [reply]
Thanks, I tried that but it did not work, most likely wrong config. I will give it another go.

**Reply by invizus** [reply]
Looks like I do not need persistentvolume in kubernetes, I can use host directory directly, but I still cannot make it all work. This is part of `values.yaml` config:

```
rulesFolder: "/srv/rules2"

extraVolumes:
  - name: rules2
    hostPath:
      path: /mnt/nfs_01/elastalert2/rules/
      type: DirectoryOrCreate
extraVolumeMounts:
  - name: rules2
    mountPath: "/srv/rules2"
    readOnly: false
```

When I deploy helm:
```
$ helm install -n elastalert --create-namespace -f values.yaml elastalert2 elastalert2/elastalert2
Error: INSTALLATION FAILED: 1 error occurred:
        * Deployment.apps "elastalert2" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/srv/rules2": must be unique
```

Without `rulesFolder: "/srv/rules2"` , I can deploy the chart, and then when I exec into container and list directory, it contains my rule files, so it mounts alright. 

But, how to tell elastalert to use those rules? without `rulesFolder`, `/opt/elastalert/rules` is empty dir.
