### DISCUSSION TITLE
num_events for a frequency rule

### DISCUSSION THREAD

**Discussion by gminogiannis** [jertel/elastalert2#1438] [Q&A]
Hello!
We 've been using a frequency rule with a configuration similar to the below:
```
type: frequency
scan_entire_timeframe: True
index: logs-*

num_events: 10
timeframe:
  minutes: 5

filter:
- query_string:
    analyze_wildcard: true
    query: 'level: (ERROR OR WARN) AND NOT message: ("test msg" OR "testing rule")'


alert:
  - "command"

realert:
 minutes: 30

command: ["/opt/scripts/send-sms.sh"]
```

The rule is executed every minute and is expected to check if more than 10 documents during the last 5 minutes match the query.
Nevertheless, we have seen several cases whereby the alert is triggered even if less than 10 documents match the query.

Is there a way to troubleshoot this ?

P.S: ElastAlert2 is launched as a Docker container via the following command:
```
sudo docker run \
--name elastalert2 \
--net="host" \
-v /opt/elastalert/config.yaml:/opt/elastalert/config.yaml \
-v /opt/elastalert/rules:/opt/elastalert/rules \
jertel/elastalert2:2.12.0
```
P.S2: We are still using 2.12.0 because newer versions fail to start. That's something for another discussion thread, though.

---
