### DISCUSSION TITLE
Adding additional fields to ElastAlert documents.

### DISCUSSION THREAD

**Discussion by jeff-bb** [jertel/elastalert2#1441] [Q&A] [answered]
Given this sample yaml file below, I'm curious how to get various key/values/arrays into the elastalert as new fields.

For example, name maps to rule_name description maps to description, elastic query results map to match_body... but what about fields defined in the yaml that I'd like to push forward into the alert. For example, status, severity, references, and mitre?

I had the thought of modifying the elastaery.py self.add_metadata_alert and ruletypes.py __init__ sections but that felt dirty to insert like that.

Is this something I'd leverage a custom rule type for to insert this additional data using add_data? I've done some amount of searching, but I can't find other references to this. I've found some references to using this data in the alert_text, but I want to get it stored with the document.

```
name: Rulename
status: stable
severity: medium
priority: 3
description: Words
references:
    - https://google.com
mitre:
    - TA0001
        -T1659
    - TA0002
        -T1651
        -T1059

type: any
index: logstash-*

buffer_time:
    days: 7
realert:
    hours: 1

query_key: [host.name]

filter:
    - query:
        query_string:
            query: 'event.code:1'

alert_subject: "host {}"

alert_subject_args:
    - host.name

alert_text: |-
    Event Activity!
    Occurred at: {}
    Host: {}

alert_text_args:
    - "@timestamp"
    - host.name

alert_text_type: alert_text_only

alert:
    - "email"

email:
    - "to@domain"
from_addr: "from@domain"
smtp_host: "1.1.1.1"
```
