### DISCUSSION TITLE
Wildcard filter doesn't seem to be working for one value, but works for the other

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#1442] [Q&A] [answered]
Here is the filter:

```
filter:
- query:
    bool:
      must:
      - term:
          winlog.provider_name: "Microsoft-Windows-Sysmon"
      - term:
          event.code: 11
      should:
      - term:
          dirname: "Desktop"
      - term:
          dirname: "Documents"
      minimum_should_match: 1
      must_not:
      - wildcard:
          winlog.event_data.TargetFilename: "*:Zone.Identifier"
      - wildcard:
          file: "*.tmp"
```
It seems to be working for the `winlog.event_data.TargetFilename: "*:Zone.Identifier"` but not the `file: "*.tmp"`

Any idea what the solution is?
