### DISCUSSION TITLE
percentage_match rule Kibana link generating wrong query

### DISCUSSION THREAD

**Discussion by aliosmanisikk** [jertel/elastalert2#1450] [Q&A] [answered]
Not sure yet if I'm doing sth wrong, so decided to create a discussion rather than an issue.

I'm running elastalert2 version 2.18.0

My alert rule looks like this

```
name: High error rate
description: "80% of requests should be successful"
type: percentage_match
index: prod-*
doc_type: _doc

filter:
  - query_string:
      query: 'message:"Response sent"'

match_bucket_filter:
  - query_string:
      query: 'message:"Response sent with errors"'

buffer_time:
  hours: 1
realert:
  hours: 1

max_percentage: 20
min_denominator: 20

query_key:
  - body.queryDetails.operationName.keyword
include:
  - body.queryDetails.operationName.keyword

# Generate link
generate_opensearch_discover_url: true
kibana_discover_app_url: "https://opensearch.grandvision.io/app/data-explorer/discover#"
kibana_discover_index_pattern_id: "prod-*"
kibana_discover_version: "2.11"

# Alert format
alert:
  - slack
slack_channel_override: "#graph-prod-alerts"
slack_title: "Query/mutation error rate higher than 20%"
alert_text_args:
  - body.queryDetails.operationName.keyword
  - opensearch_discover_url
alert_text_type: alert_text_only
alert_text: |
  *{0}* error rate is more than 20%.
  <{1}|*Open OpenSearch query*>
```

My alert text looks like this `{'keyword': 'getCart'} error rate is more than 20%.` while it should looks like `getCart error rate is more than 20%.`

And when I click the kibana link, the query looks like this

```
{
  "query": {
    "match": {
      "body.queryDetails.operationName.keyword": {
        "query": {
          "keyword": "getCart"
        }
      }
    }
  }
}
```

instead of 

```
{
  "query": {
    "match": {
      "body.queryDetails.operationName.keyword": "getCart"
    }
  }
}
```

As a result, the query on Opensearch fails. It used to work correctly in v2.9.0 . This started occurring after upgrading to v2.18.0
