### DISCUSSION TITLE
Removing whole message from Teams alerts

### DISCUSSION THREAD

**Discussion by StasABerg** [jertel/elastalert2#1453] [Q&A] [answered]
Hey all, Im having an issue removing the main json body from the teams alerts, I want to keep only the parameters I choose.
In the image attached I get first the message above the actual parameters that I have chosen to show in the teams alert.
![Untitled](https://github.com/jertel/elastalert2/assets/114340468/d4670d70-fcfa-4cda-a148-776108c0f5f2)

heres the rule.yaml:
```
name: "name"
index: "index-*"
es_host: host03
es_port: 9200
is_enabled: true
ms_teams_alert_fixed_width: true
ms_teams_alert_facts:
  - name: Request Host
    value: request.headers.host
  - name: Requesrt URI
    value: request.uri
  - name: Request Method
    value: request.method
  - name: Status Code
    value: "response.status"
  - name: Upstream Status
    value: upstream_status
  - name: X-Forwarded-For
    value: request.headers.x-forwarded-for
  - name: Client IP
    value: "client_ip"
  - name: User Agent
    value: request.headers.user-agent
alert_text: "Hey {}"
alert_text_args:
  - "Please be notified"


alert:
  - "ms_teams"
ms_teams_webhook_url: "hook"
type: "frequency"
filter:
  - terms:
      request.headers.host:
               - 8
               - 7
               - 6
               - 5
               - 4
num_events: 1
timeframe:
  hours: 1
```
