### DISCUSSION TITLE
Can top_count_keys be passed to http_post_payload values?

### DISCUSSION THREAD

**Discussion by shahriar52** [jertel/elastalert2#146] [Q&A] [answered]
Hi,

Just wondering if I can use the result of `top_count_keys` as a value of a key at `http_post_payload`. For example,
```
name: Testing rule
index: zabbix-metrics-*
top_count_keys: ["hostname"]
timeframe:
  minutes: 5

filter:
- query:
    query_string:
      query: "itemname: \"Incoming traffic on eth0\""
- range:
    itemvalue_integer:
      gte: 100000

include:
  - hostname

alert: post
http_post_url: "https://www.example.com/api"
http_post_payload:
  hosts: top_count_keys
http_post_headers:
  authorization: Basic #################
```
