### DISCUSSION TITLE
is not valid under any of the given schemas

### DISCUSSION THREAD

**Discussion by zshhh666666** [jertel/elastalert2#1474] [Q&A] [answered]
Please look at the following questions for me!!tks!!!
![error](https://github.com/jertel/elastalert2/assets/104488381/b81dc8ed-cabc-4e3e-886d-ce8f3c1c6c4d)
Here is my rules file!
```
index: "alerttest*"

type: "Frequency"

name: "a"

is_enabled: true
num_events: 2
realert:
  minutes: 5
terms_size: 50
timeframe:
  minutes: 5

filter:
  - query_string:
      query: "@timestamp:*"

alert:
  - "email"
email:
  - "zhangs@yusur.tech"
  - "sunxd@yusur.tech"
smtp_host: smtp.qq.com
smtp_port: 465
smtp_auth_file: /opt/elastalert/rules/smtpfile/email_auth.yaml
``` 
Here are my startup commands!
docker run --net=elastic --name elastalert --restart=always \
-v /opt/elk8.12.0/elastalert/alerttest/elastalert.yaml:/opt/elastalert/config.yaml \
-v /opt/elk8.12.0/elastalert/alerttest/rules:/opt/elastalert/rules \
-v /opt/elk8.12.0/elastalert/alerttest/certs:/opt/elastalert/certs \
harbor.yusur.tech/tools/elastalert2:2.18.0 --verbose

By the way,The type field of rules doesn't work if I use "frequency", so I use "Frequency".
