### DISCUSSION TITLE
Rule not triggering alert.

### DISCUSSION THREAD

**Discussion by manishparmar5751** [jertel/elastalert2#1480] [Q&A] [answered]
Below is the rule, which was working before but does not seem to be now. Nothing has changes in our environment here.

Index `switches ` is a test index and has no data coming in i.e always zero hits for this index. Jira credentials are good.
```
name: "Nodata flatline - switches"
type: flatline
index: "switches*"
realert:
  minutes: 2
threshold: 1
timeframe:
  minutes: 2
filter:
- query:
    match_all: {}
doc_type: _doc
alert:
- "jira"
jira_server: "https://XYZ.atlassian.net/"
jira_project: "CASE"
jira_issuetype: "Incident"
jira_account_file: "XYZ/examples/rules/jira_acct.txt"
jira_priority: 0
jira_description: "Index swtiches* has no data flowing in Prod ELK cluster. \n"

```

```
Jun 25 04:09:33 prod-elk-monitor python[3041]: INFO:elastalert:Ran Nodata flatline - switches from 2024-06-25 04:02 PDT to 2024-06-25 04:09 PDT: 0 query hits (0 already seen), 0 matches, 0 alerts sent
Jun 25 04:09:33 prod-elk-monitor python[3041]: INFO:elastalert:Nodata flatline - switches range 442

```
