### DISCUSSION TITLE
Does the elastalert-test-rule tool has an option to display the queries being made to Elasticsearch?

### DISCUSSION THREAD

**Discussion by houjjou** [jertel/elastalert2#1562] [Q&A] [answered]
### When testing rules using the `elastalert-test-rule`, it would be useful to see the queries being made on elasticsearch 

This could be helpful to understand why the rule may not be working (or to understand how the rules work at all) 

I have seen that one can log the queries using `--es_debug_trace` when running elastalert2 with the cli. However I'm unsure if this feature exists when using the `elastalert-test-rule` tool.

Right now, I'm using the `elastalert-test-rule` tool with this command :
```shell
# elasticsearch: 7.17
# elastsearch: 2.20.0

docker run --rm -it \
    -v $(pwd)/elastalert.yaml:/opt/elastalert/config.yaml \
    -v $(pwd)/charts/staging/rules:/opt/elastalert/rules \
    --entrypoint elastalert-test-rule \
    jertel/elastalert2 --days 2 \                             
    ./rules/5xx_percentage.yaml
```

But I don't see any option to display the actual queries being made to Elasticsearch (either in a file or in the console).
Could you please enlighten me on this matter?

Thanks in advance.

**Comment by jertel** [comment, marked as answer]
If you add the documented logging configuration in your `elastalert.yaml` config file it will output the query details.

Ex:

```
logging:
 version: 1
 incremental: false
 disable_existing_loggers: false
 formatters:
   logline:
     format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

 handlers:
   console:
     class: logging.StreamHandler
     formatter: logline
     level: DEBUG
     stream: ext://sys.stderr



 loggers:
   elastalert:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch.trace:
     level: DEBUG
     handlers: []
     propagate: true

   '':  # root logger
     level: DEBUG
     handlers:
       - console
     propagate: false
```
