### DISCUSSION TITLE
Misunderstanding query_key and alerting

### DISCUSSION THREAD

**Discussion by Saintel** [jertel/elastalert2#1569] [Q&A] [answered]
I have documents in ElasticSearch which contains at least 5 fields: solution, source, environment, region, level
And i have to get alert, when one of resulting group `solution*source*environment*region` contains 10+ documents with `level:<4`

My config:
```yml
type: frequency

timeframe:
  minutes: 5

query_key:
 - solution
 - source
 - environment
 - region

num_events: 10

filter:
- query:
    query_string: {query: 'solution: ("mySolution1","mySolution2) AND level:<4'}

alertmanager_fields:
  solution: solution
  source: source
  environment: environment
  region: region

alert_text: "Too many exceptions: {0}"
alert_text_type: alert_text_only
alert_text_args:
- num_matches
include: ["solution","environment","source","region"]
```

But in alert i recieved the same num_matches (in test cases):

```
Alerts, [13.11.2024 11:41]
🔥 Alerts Firing 🔥


🪪 Exceptions
📖 Too many exceptions: 18

environment: Production
region: Region2
solution: mySolution1
source: RouterApi

Alerts, [13.11.2024 11:41]
🔥 Alerts Firing 🔥

🪪 Exceptions
📖 Too many exceptions: 18

environment: Production
region: Region2
solution: mySolution2
source: Jobs.ActivationReminder

🔥 Alerts Firing 🔥


🪪 Exceptions
📖 Too many exceptions: 18

environment: Test
region: Region1
solution: mySolution1
source: Platform.Backend

...
etc.
```
And when i manualy check documents, the counters per group not match with alerts.

What i missing? Can anyone help me to achieve results i need?
