### DISCUSSION TITLE
Realerting is broken when compound query key with array fields is used in elastalert >= 2.19

### DISCUSSION THREAD

**Discussion by ptobis** [jertel/elastalert2#1591] [Q&A]
# Description
An incorrect silence cache key is created, ignoring any query key fields, when the following circumstances occur:
* elastalert2 > 2.18.0
* "realert" is set in the rule,
* compound query key (i.e. created from multiple query key fields) is configured in the rule,
* any query key field refers to an array, that means square brackets are used in at least one of the field names of the compound query key (e.g. "array[0]field")
# Example rule
```yaml
---
name: "test"
type: any
index: "<index>-*"

realert:
    hours: 1

query_key:
    - "some_field"
    - "some_array[0]some_other_field"

filter:
    - query:
        query_string:
          query: "field: value OR otherfield: othervalue"

# Alert configs
alert: "post2"
http_post2_url: "<url>"
http_post2_all_values: true
```
# Result
The silence cache key written to ES contains only the rule name, and completely ignores query key fields. This leads to a situation where all alerts coming from the rule, regardless of query keys, are ignored during the configured time.
# Expected result
The silence cache key written to ES contains the rule name and combined values of the compound query key. Only the alerts that match the same query key values are suppressed.
# Investigation
The error appears when calling a method get_query_key_value: https://github.com/jertel/elastalert2/blob/70bc1d825c27d0622dd41bf9253773d0a6e7a3e1/elastalert/elastalert.py#L908
because of a new implementation of _find_es_dict_by_key function, that is indirectly used by the get_query_key_value method: https://github.com/jertel/elastalert2/blob/d400d00eddb841d56df05ab2c77d398d39fec5c1/elastalert/util.py#L47
In case the above circumstances happen, get_query_key_value always return None, that leads to alert suppression not working properly.

The workaround for handling compound query keys that existed in the old version of _find_es_dict_by_key unfortunately has not been implemented in the new function: https://github.com/jertel/elastalert2/blob/3b4608ca8f9c4b69153ecd6a44a42d7a70562ecc/elastalert/util.py#L68-L81

Please fix the _find_es_dict_by_key function, so it also accepts the compound query key with arrays (square brackets)
