### DISCUSSION TITLE
Why is the match_time and alert_time so different?

### DISCUSSION THREAD

**Discussion by vutuong** [jertel/elastalert2#1606] [Q&A] [answered]
This is my rule config:
```
name: test
type: frequency
es_host: es-http
es_port: 9200
es_username: elastalert
es_password: 123
use_ssl: True
index: os-log
timestamp_field: "os_time"
enabled: true
verify_certs: False
num_events: 1
timeframe:
    minutes: 3
run_every:
    minutes: 3
filter:
  - term:
      junos_eventname.keyword: "UI_LOGIN_EVENT"
  - term:
      junos_hostname.keyword: "TEST-DEVICE
alert:
    - "email"
email:
    - "example.com.vn"
smtp_auth_file: "/opt/elastalert/alerts/email/tech.com.vn.yaml"
from_addr: "ElastAlert"
smtp_host: "1.1.1.1"
smtp_port: 25
smtp_ssl: False
```
I got this data from elastalert index:
<img width="767" alt="image" src="https://github.com/user-attachments/assets/ffa87825-c1de-4514-8ec5-64b4fadf0740" />

Because match_time is same as my raw log time. I wonder why match_time and alert_time so different? How can I set to display the alert history from elastalert metadata each 5 minute as match_time ?
