### DISCUSSION TITLE
Templating for alertmanager annotations and labels

### DISCUSSION THREAD

**Discussion by tgxworld** [jertel/elastalert2#1612] [Ideas]
In Prometheus, there is templating support for labels and annotation when [defining an alerting rule](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating) and I would like to propose doing the same for AlertManager alert type in ElastAlert2. 

My general idea now is to rely on the `jinja` templating engine so that labels and annotations can be defined like so:

```
alertmanager_labels:
  service_name: "{{_data["service.name"]}}"
  id: "{{_data["some.field"]}}:{{_data["some.other.field"]}}"
alertmanager_annotations:
  some_external_link: "http://some.domain.com/status/{{_data["service.name"}}"
```
