### DISCUSSION TITLE
flatline rule not working as expected

### DISCUSSION THREAD

**Discussion by mobbackup** [jertel/elastalert2#1616] [Q&A]
Hi Team,

I have setup two flatline rules on two different clusters. One is working as expected and other one is not working. 

Both the rules are same and its as per below. 

It's a flatline type rule where in a min if there are less than 100 hits, it will send the email. 

```
name: flatline alerts
type: flatline
index: com-prod*
threshold: 100
timeframe:
  minutes: 1
filter:
 - query:
      query_string:
        query: 'message: "there is 2xx"'
alert_subject: "Alert - No 2xx on com prod Environment"
alert_text_type: alert_text_only
alert_text: "
Lesser 2xx event(s) in last 1 minute on the com prod Environment.\n
Issue details:\n
Environment: prod\n
TimeStamp: {0}\n
Please contact the team.\n
Thanks & Regards,\n
Alert Monitoring"
alert_text_args: ["@timestamp"]
alert:
  - "ses"
ses_aws_access_key_id: "B..."
ses_aws_secret_access_key: "B.."
ses_aws_region: "e..."
ses_from_addr: "someone@abc.com"
ses_email:
  - "someone@abc.com"
```

Below are the details.

A] The cluster where it works has below config. 

Ai] 
run_every:
  minutes: 1

Aii]
buffer_time:
  minutes: 15

Aiii] 
alert_time_limit:
  days: 2

Aiv] 
Total rules - 14 rules 

Here, if there are more than 100 hits in a min say for a duration of 15 mins, i am not getting email alerts so flatline rule is working here. 

B] The cluster where it is not working has below config. 

Bi] 
run_every:
  minutes: 1

Bii] 
max_threads: 25  
(increased max threads due to no. of rules)

Biii] 
buffer_time:
  minutes: 15

Biv]
alert_time_limit:
  minutes: 60

Bv] 
Total rules - 62 rules

Here, even if there are more than 100 hits in a min say for a duration of 15 mins, i am still getting email alerts which i should not get as per above flatline rule.

I am not able to find the issue here as why same rule is working in one place but not in other place. Any help here is appreciated.

Thanks,
