### DISCUSSION TITLE
How to make a properly configuring an "OK" rule to trigger after a problem alert?

### DISCUSSION THREAD

**Discussion by aratnikov-emexglobal** [jertel/elastalert2#1637] [Q&A]
First of all, thank you for this fantastic project! It has been incredibly helpful for monitoring our services, and I truly appreciate the effort put into maintaining it. But I really need your help.

I have a PROBLEM alert set up in Praeco, and it works just fine. Here is the rule (I've trimmed some Praeco-specific fields for clarity):  

```yaml
alert:
  - "slack"
alert_subject: "[PROBLEM] my-problem-alert-name"
filter:
  - query:
      query_string:
        query: "MessageTemplate:\"Attempt to create document duplicate with\""
index: "prod_api-*"
name: "my-problem-alert-name"
realert:
  hours: 2
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "any"
use_strftime_index: false
```

This rule works perfectly, and I receive an alert whenever the issue occurs.  

However, I also want to create an **OK rule**, which should be sent **only after** the problem alert has been triggered (indicating that the issue has appeared and then resolved). I also understand, that alert will be send after elastalert2 service restart. Here is my attempt:  

```yaml
alert:
  - "slack"
alert_subject: "[OK] my-problem-alert-name"
alert_text_type: "alert_text_only"
doc_type: "properties"
filter:
  - query:
      query_string:
        query: "MessageTemplate:\"Attempt to create document duplicate with\""
index: "prod_api-*"
name: "my-problem-alert-name_ok"
realert:
  weeks: 9999
terms_size: 50
threshold: 1
timeframe:
  minutes: 10
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "flatline"
use_strftime_index: false
```

When I first created this rule, it immediately sent an OK alert (which is expected). However, today, after the problem alert was triggered, I did **not** receive the OK alert as I expected.  

Here is how it looks in Praeco for the OK rule:  
![изображение](https://github.com/user-attachments/assets/831c5492-c4b1-4239-937a-f83d92e9c404)  

From my understanding, if I **do not use** `realert`, the OK alert will be sent every minute. However, I am unsure of the correct way to configure it so that it only sends **after the problem alert has been triggered and then stops when the issue is resolved**.  

How should I properly configure this OK rule? Any guidance would be greatly appreciated!  

Thanks again for all your work on ElastAlert2!
