### DISCUSSION TITLE
SSL elasticsearch

### DISCUSSION THREAD

**Discussion by ngms17** [jertel/elastalert2#1645] [Q&A]
Running Elastlart2 with docker. This is my Elastalert config file:

```
# ElastAlert 2 Config
rules_folder: rules
scan_subdirectories: false
run_every:
  minutes: 5
buffer_time:
  minutes: 15
es_host: timon.inesctec.pt
es_username: "elastic"
es_password: "xxxxx"
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
use_ssl: True
verify_certs: True
ca_certs: /opt/elastalert2/elasticsearch-ca.pem
```

When i start the container, it gives me this error:

`elasticsearch.exceptions.ConnectionError: ConnectionError(Could not find a suitable TLS CA certificate bundle, invalid path: /opt/elastalert2/elasticsearch-ca.pem) caused by: OSError(Could not find a suitable TLS CA certificate bundle, invalid path: /opt/elastalert2/elasticsearch-ca.pem)`

The path is correct, what am i doing wrong?

Thanks
