### DISCUSSION TITLE
How can I just have all alerts print to logs, with context, without debug mode enabled?

### DISCUSSION THREAD

**Discussion by davehouser1** [jertel/elastalert2#1656] [Q&A] [answered]
I don't want to send an alert anywhere, I just want to have the log print to the log output. 
I want the alert to include `alert_text`. I tried using `alert: command` with `/bin/echo`, but I cant figure out how to include the `alert_text` in the output. 
I know debug mode does this by default, but I dont want to keep debug mod on in production. 
How can I accomplish this?

**Comment by jertel** [comment]
Use the debug alerter.

```
alert: debug
```

**Reply by davehouser1** [reply]
I get no output when setting `alert: debug`, my config in the values.yaml for kube deployment is at the end of this post. If I change back to command settings I see an alert. Note I am not running the chart with any args (`--debug` mode is not enabled).

I cant find much documentation on how to use `alert: debug`. There is just one paragraph on what this setting does [here](https://elastalert2.readthedocs.io/en/latest/alerts.html), with no examples. Looking closer at the code. It seems that `DebugAlerter()` cant even be called unless `self.debug` is True, which its not because I don't want to enable `--debug`, just want single line errors not all the output that `--debug` gives. 

Is there no way to format the `alert: command` to include data from the alert? I found [this post](https://github.com/Yelp/elastalert/issues/2218) which is leading me to believe... its not possible to include alert_text in the command output. 

Looking at the `command` documentation I see this

> Strings can be formatted using the old-style format (%) or the new-style format (.format()). When the old-style format is used, fields are accessed using %(field_name)s, or %(field.subfield)s. When the new-style format is used, fields are accessed using {field_name}. New-style formatting allows accessing nested fields (e.g., {field_1[subfield]}). In an aggregated alert, these fields come from the first match.

Where can I find a list of fields and subfields? its not clear what I can access. If I use `%(rule)s` like the example shows I can access just the rule data. But when I try to use `{match}` I get `<MISSING VALUE>`

My expectations is that I would just see one line of output with the alert info from the index without doing anything else. 

Am I missing something? 

```
  rules:

    rule-test: |-
      ---
      name: "Node Change Alert"
      type: any
      index: rule-test
      timeframe:
        minutes: 1
      alert: debug
      alert_text_type: alert_text_jinja
      alert_text: |
        Alert triggered! *({{num_hits}} Matches!)*
        Something happened with {{username}} ({{email}})
        {{description|truncate}}
      pipe_match_json: true
      realert:
        seconds: 10
```

**Reply by jertel** [reply, marked as answer]
Your first post asks how to send alerts to the log, so I expected you had already enabled ElastAlert 2 logging. Are you seeing *any* log output? If not, you will need to read the [docs](https://elastalert2.readthedocs.io/en/latest/logging.html) about logging. Below is an example config.yaml snippet to enable logging to console.

```
logging:
 version: 1
 incremental: false
 disable_existing_loggers: false
 formatters:
   logline:
     format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

 handlers:
   console:
     class: logging.StreamHandler
     formatter: logline
     level: INFO
     stream: ext://sys.stderr

 loggers:
   '':  # root logger
     level: INFO
     handlers:
       - console
     propagate: false
```

There is no need to specify `--debug` to get the DebugAlerter working. The piece of code you looked at is for logging process malfunctions of ElastAlert 2 itself. In other words, ElastAlert 2 is capable of using it's own alerting system to notify when an internal issue arises, such as loss of connection to Elasticsearch.

If using the Command alerter the `{field_name}` notation is referencing the actual fields in the event that triggered the alert. Therefore there is no predefined list of fields to choose from. It all depends on *your* data in your Elasticsearch cluster. As far as wanting to use the `alert_text` property with the Command alerter: yes, you can. This is [documented](https://elastalert2.readthedocs.io/en/latest/alerts.html#command) under the Command alerter section via the `pipe_alert_text` flag.
