### DISCUSSION TITLE
Changing max_threads does not take effect

### DISCUSSION THREAD

**Discussion by sirhc-chris** [jertel/elastalert2#1672] [Q&A]
We have a large number of rules so I want to increase the number of threads available to process them. Increasing `max_threads` from the default of `10` to `30` (or any other value, including `1`), and restarting the container, does not result in a change of behavior - I continue to see the same warning periodically logged suggesting the thread pool size is unchanged:
```
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: foo.bar.m. Connection pool size: 10
```

`max_threads` is being set in the main `config.yaml` mapped to `/opt/elastalert/config.yaml` within the container (not within the rule config) - an example config:
```
rules_folder: /opt/elastalert/rules

run_every:
  seconds: 10

buffer_time:
  minutes: 15

es_host: foo.bar.m
es_port: 9200

writeback_index: elastalert_status

alert_time_limit:
  days: 1
  
max_threads: 30
```

ElastAlert2 version: 2.23.0
Elasticsearch version: 8.15.2
Environment: Kubernetes (direct, not Helm) + reproduced in local Docker

**Comment by jertel** [comment]
`max_threads` is used for the worker thread pool. The log message above is referencing a connection pool. Without more log data I can't be sure which connection pool it is.

**Reply by sirhc-chris** [reply]
ah my bad, thanks - I'm running with `--verbose` but there aren't any other pertinent log messages surrounding it...

I've also cross-referenced with the elasticsearch logs but there's nothing relevant there either

**Reply by jertel** [reply]
What is `foo.bar.m`? Certainly that host should tell you what the connection pool relates to. For example, if that is the Elastic host then it confirms the Elastic connection pool size is the bottleneck.

**Reply by sirhc-chris** [reply]
yeah that's elastic (per `es_host`), but I thought the connection pool sizes are configured in the client? afaik there isn't any config in elasticsearch to control that 🤔

**Reply by jertel** [reply]
I see this in the Elasticsearch Python API documentation:

![image](https://github.com/user-attachments/assets/0279b785-202e-4408-9e83-be35cf2368c0)

I'm not seeing ElastAlert2 setting anything related to this, but I could be missing it. I suspect your queries take a (relatively) long time to finish which is contributing to the problem.

**Reply by sirhc-chris** [reply]
thanks - unfortunately I don't think it's that, the default value for `max_concurrent_searches` would be 140 based on that formula:
```
max(1, (14 * min(25, 10)))
```

**Reply by jertel** [reply]
It seems as if your ElastAlert 2 instance has been modified, or there's some custom code connecting to Elasticsearch. According to the code, specifically line 27 of `__init__.py`, ElastAlert 2 uses the RequestsHttpConnection, not the Urllib3Connection, which your log is showing is in use. I suggest getting a stack trace of the error to isolate the call stack. You may need to enable debug logging in ElastAlert 2.

**Reply by sirhc-chris** [reply]
> It seems as if your ElastAlert 2 instance has been modified, or there's some custom code connecting to Elasticsearch.

Nope, the only customisation I have done is a handful of [enhancements](https://elastalert2.readthedocs.io/en/latest/recipes/adding_enhancements.html) to modify some alerts before they're sent (no changes to the source code, nor are they related to connecting to elastic) 

> I suggest getting a stack trace of the error to isolate the call stack. You may need to enable debug logging in ElastAlert 2.

I already tried with `--verbose` but no dice. I'm not sure the easiest way to get the stack trace for the warning?

**Reply by jertel** [reply]
This may help. https://elastalert2.readthedocs.io/en/latest/logging.html

**Reply by sirhc-chris** [reply]
Thanks @jertel, appreciate your help with this! 

I've got a custom logging config:
```
    logging:
      version: 1
      incremental: false
      disable_existing_loggers: false
      formatters:
        logline:
          format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s [module: %(module)s] [funcName: %(funcName)s] %(pathname)s:L%(lineno)s %(stack_info)s'
      handlers:
        console:
          class: logging.StreamHandler
          formatter: logline
          level: DEBUG
          stream: ext://sys.stderr
      loggers:
        '':  # root logger
          level: DEBUG
          handlers:
            - console
          propagate: false
```
But I still can't get the full call stack from the warnings:

```
2025-06-12 08:00:15,388  WARNING urllib3.connectionpool Connection pool is full, discarding connection: foo.bar.m. Connection pool size: 10 [module: connectionpool] [funcName: _put_conn] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:L323 None
```


I noticed in the debug logs there are a number of calls using urllib3, not just the aforementioned warnings:
```
2025-06-12 10:36:07,852    DEBUG urllib3.connectionpool hhttp://foo.bar.m "POST /elastalert_status/_search?size=1000 HTTP/1.1" 200 None [module: connectionpool] [funcName: _make_request] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:L475 None
2025-06-12 10:36:17,716    DEBUG urllib3.connectionpool http://foo.bar.m "DELETE /_search/scroll HTTP/1.1" 404 32 [module: connectionpool] [funcName: _make_request] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:L475 None
2025-06-12 10:36:17,988    DEBUG urllib3.connectionpool hhttp://foo.bar.m "POST /elastalert_status_status/_doc HTTP/1.1" 201 183 [module: connectionpool] [funcName: _make_request] /usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py:L475 None
```
`RequestsHttpConnection` uses the requests library, but requests itself uses urllib3 as its transport library - so is this actually expected? Or would you expect the module path to be `requests.packages.urllib3.connectionpool` in the logs if that was the case?
