### DISCUSSION TITLE
rules template issue

### DISCUSSION THREAD

**Discussion by ZYWNB666** [jertel/elastalert2#1680] [Q&A]
I added a rule, but I don't know how the spec should be written, I wrote a template for a custom webhook via chatgpt, but I got an error when starting the pod. I ran it using helm install into k8s, and below are my rules
```yaml
name: "JSON Error Log Alert"
type: any
index: "k8s-gametech-production-*"

filter:
- bool:
    must:
      - exists:
          field: json.level
    must_not:
      - term:
          json.level: "INFO"

include:
  - message
  - kubernetes.labels.app
  - kubernetes.namespace

alert:
- "webhook"
webhook_url: "https://your.domain.com/alert"

http_post_payload:
  message: "{0}"
  app: "{1}"
  namespace: "{2}"

alert_text_args:
  - message
  - kubernetes.labels.app
  - kubernetes.namespace

realert:
  minutes: 10
```
