### DISCUSSION TITLE
limit_execution: delayed notifications

### DISCUSSION THREAD

**Discussion by mkondratev** [jertel/elastalert2#1681] [Q&A] [answered]
I have the following rules with different `limit_execution` times.

```yaml
name: MonFriWorkTime
type: flatline
limit_execution: "* 6-19 * * 1-5"
threshold: 1
timeframe:
  minutes: 10
  
name: MonFriNonWorkTime
type: flatline
limit_execution: "* 0-5,20-23 * * 1-5"
threshold: 1
timeframe:
  minutes: 30

name: SatSun
type: flatline
limit_execution: "* * * * 6,0"
threshold: 1
timeframe:
  minutes: 30
```

I expect to receive alerts within the time interval specified in `limit_execution` about events that occurred during `limit_execution`. In reality, the rule triggers outside of `limit_execution` and sends an alert within `limit_execution`, meaning after a 6-hour delay.

```json
{
  "_index": "elastalert",
  "_type": "_doc",
  "_id": "OA-FoJcBWBDl74cr2ge3",
  "_score": 0.0,
  "_source": {
    "match_body": {
      "@timestamp": "2025-06-23T23:57:23.663253Z",
      "key": "all",
      "count": 0,
      "threshold": 1,
      "num_hits": 330,
      "num_matches": 2
    },
    "rule_name": "MonFriWorkTime",
    "alert_info": {
      "type": "alertmanager"
    },
    "alert_sent": true,
    "alert_time": "2025-06-24T06:00:16.237305Z",
    "match_time": "2025-06-23T23:57:23.663253Z",
    "@timestamp": "2025-06-24T06:00:16.309467Z"
  }
}
```

This results in delayed notifications. How can I fix this?
