### DISCUSSION TITLE
How to remove _id, _index, _type, num_matches, num_hits and @timestamp from elastialert rules

### DISCUSSION THREAD

**Discussion by MohdRashid01** [jertel/elastalert2#189] [Q&A] [answered]
Hi All,

Below is the content which im getting in my gmail inbox. I want to

remove _id, _index, _type, num_matches, num_hits and @timestamp 

all this only i want message to be include in my email triggering everytime.

Below is getting into my gmail inbox
```
@timestamp: 2021-05-24T11:16:06Z
_id: 2S0WnnkBz7SOxaiw1TZk
_index: logstash-2021.05.24
_type: _doc
message: <30>May 24 11:16:06 fx-prod-1 prod_fx-control-plane.1.knel5yam 2021-05-24 11:16:06.926 INFO 1 --- [nio-8080-exec-9] com.fxlabs.fxt.rest.run.RunController : Find Latest by job id [8a8089ba777311370177734530902ec8] org [8a8081066e02d6a2016e04eacd2005c7] principal [8a808155647d283a01647d7c5e0d07ba]
num_hits: 8
num_matches: 1
```
and

Here is the rules.yaml file which i used to trigger email for issue
```
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: elasticsearch.example.com

es_host: elasticsearch.test.com
# (Optional)
# Elasticsearch port
#es_port: 14900
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword
es_username: testelastic
es_password: xxxx


# (Required)
# Rule name, must be unique
name: Exception Alert

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
#type: blacklist
type: any
include: ["message"]

# (Required)
# Index to search, wildcard supported
#index: logstash*
index: filebeat*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
#num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
#  hours: 1
#  minutes: 1
  seconds: 1

#compare_key: "message"

#blacklist:

#- "error"

realert:
  minutes: 5

 # This is send out all matches in one email
# aggregation:
#  minutes: 1

#  seconds: 0
#filter:
#- term:
#    message: "[error]"

#filter:
# - match:
 #   message: "job"

filter:
 - query:
      query_string:
 #       query: "message: exception AND  message: control"
        query: "message: job"
#filter:
#- query:
#   query_string:
#    query: "message: error"

alert:

- "slack"
- "email"


#- slack
slack_webhook_url: "https://hooks.slack.com/services/xxxxxxxx"
#slack_username_override: "ElastAlert"
slack_username_override: "Mohd Rashid"

#- email
email: ["rashidmd777@gmail.com"]
smtp_host: "smtp.gmail.com"
smtp_port: "587"
from_addr: "rashidmd777@gmail.com"
```
How to do it,

**Comment by nsano-rururu** [comment, marked as answer]
look
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#alert-subject

**Reply by MohdRashid01** [reply]
U mean if i add like below one will it remove all this remove _id, _index, _type, num_matches, num_hits and @timestamp and it should not show me in email.
 
It should show only MESSAGE like below image from email trigger

![image](https://user-images.githubusercontent.com/7812871/119499167-11638680-bd84-11eb-9867-db966a73bdd3.png)

This that correct way to add alert_subject_args:
```
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: elasticsearch.example.com

es_host: elasticsearch.test.com
# (Optional)
# Elasticsearch port
#es_port: 14900
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword
es_username: testelastic
es_password: xxxx


# (Required)
# Rule name, must be unique
name: Exception Alert

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
#type: blacklist
type: any
include: ["message"]

alert_subject_args:
- "@timestamp"
- "remove _id"
- " _index"
- "_type"
- "num_matches"
- "num_hits" 

# (Required)
# Index to search, wildcard supported
#index: logstash*
index: filebeat*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
#num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
#  hours: 1
#  minutes: 1
  seconds: 1

#compare_key: "message"

#blacklist:

#- "error"

realert:
  minutes: 5

 # This is send out all matches in one email
# aggregation:
#  minutes: 1

#  seconds: 0
#filter:
#- term:
#    message: "[error]"

#filter:
# - match:
 #   message: "job"

filter:
 - query:
      query_string:
 #       query: "message: exception AND  message: control"
        query: "message: job"
#filter:
#- query:
#   query_string:
#    query: "message: error"

alert:

- "slack"
- "email"


#- slack
slack_webhook_url: "https://hooks.slack.com/services/xxxxxxx"
#slack_username_override: "ElastAlert"
slack_username_override: "Mohd Rashid"

#- email
email: ["rashidmd777@gmail.com"]
smtp_host: "smtp.gmail.com"
smtp_port: "587"
from_addr: "rashidmd777@gmail.com"
```

**Reply by nsano-rururu** [reply]
I don't know what I want to do if I only write alert_subject_args and not alert_subject. Did you really read the document?

**Reply by MohdRashid01** [reply]
yes i read document but still not understand how to use it

**Reply by nsano-rururu** [reply]
Don't you understand this?
![キャプチャ](https://user-images.githubusercontent.com/22293449/119508774-fbb58780-bdaa-11eb-96c1-74b8d6cd2090.PNG)

**Reply by MohdRashid01** [reply]
then here is i have added it
alert_subject_args: "Issue (0)"
- "@timestamp"
- "remove _id"
- " _index"
- "_type"
- "num_matches"
- "num_hits"

**Reply by nsano-rururu** [reply]
Do you understand how to use it?
![キャプチャ](https://user-images.githubusercontent.com/22293449/119511229-2b658f00-bdad-11eb-95d4-0b2ae1fb0758.PNG)

**Reply by MohdRashid01** [reply]
U mean below one 

alert_text: "failed {1}" 
- "message"

**Reply by MohdRashid01** [reply]
U only please edit and make change and send me it will easily understand for me just look at above message

**Reply by nsano-rururu** [reply]
I'm not free. I was amazed.

**Reply by MohdRashid01** [reply]
Sorry that i couldn't understand it but really im trying to understand how alert_text work for my issue

**Reply by jertel** [reply]
Add these lines to your rule:

```
alert_text_type: alert_text_only
alert_subject: "This is my alert subject"
alert_text: "This is my alert body"
```

Now trigger an alert. What does the email look like now?

**Reply by nsano-rururu** [reply]
If you try to say that changing to "alert_text_type: alert_text_only" or "alert_text_type: exclude_fields" will change it, I think it might be a bug. Even if you change it, it does not change from the default
![キャプチャ](https://user-images.githubusercontent.com/22293449/119515469-d7f54000-bdb0-11eb-9edd-606ed7e1bd96.PNG)

**Reply by nsano-rururu** [reply]
@jertel 

It seems that a bug was introduced when alert_text_jinja was added. I think you need to change "and" between the two conditions on line 120 to "or" as shown below. What do you think?
When alert_text_type is set to exclude_fields or alert_text_only, it doesn't work as specified.

https://github.com/jertel/elastalert2/blob/master/elastalert/alerts.py#L120


current

```
        if self.rule.get('alert_text_type') != 'alert_text_only' and self.rule.get('alert_text_type') != 'alert_text_jinja':
            self._add_rule_text()
            self._ensure_new_line()
            if self.rule.get('top_count_keys'):
                self._add_top_counts()
            if self.rule.get('alert_text_type') != 'exclude_fields':
                self._add_match_items()
        return self.text
```

Proposed change

```
        if self.rule.get('alert_text_type') != 'alert_text_only' or self.rule.get('alert_text_type') != 'alert_text_jinja':
            self._add_rule_text()
            self._ensure_new_line()
            if self.rule.get('top_count_keys'):
                self._add_top_counts()
            if self.rule.get('alert_text_type') != 'exclude_fields':
                self._add_match_items()
        return self.text
```

**Reply by MohdRashid01** [reply]
> Add these lines to your rule:
> 
> ```
> alert_text_type: alert_text_only
> alert_subject: "This is my alert subject"
> alert_text: "This is my alert body"
> ```
> 
> Now trigger an alert. What does the email look like now?
```
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: elasticsearch.example.com

es_host: elasticsearch
# (Optional)
# Elasticsearch port
#es_port: 14900
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword
es_username: elastic
es_password: xxxx


# (Required)
# Rule name, must be unique
name: Exception Alert

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
#type: blacklist
type: any
include: ["message"]

# (Required)
# Index to search, wildcard supported
index: logstash*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
#num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
#  hours: 1
#  minutes: 1
  seconds: 1

#compare_key: "message"

#blacklist:

#- "error"

realert:
  minutes: 5

 # This is send out all matches in one email
# aggregation:
#  minutes: 1

#  seconds: 0
#filter:
#- term:
#    message: "[error]"

#filter:
# - match:
 #   message: "job"

filter:
 - query:
      query_string:
 #       query: "message: exception AND  message: control"
        query: "message: failed"
#filter:
#- query:
#   query_string:
#    query: "message: error"

alert:

- "slack"
- "email"

alert_text_type: alert_text_only
alert_text_subject: "This is my alert subject"
alert_text: "This is my alert body"

#- slack
slack_webhook_url: "https://hooks.slack.com/services/xxxxxxxxxxx"
slack_username_override: "ElastAlert"
#slack_username_override: "Mohd Rashid"

#- email
email: ["mohd@gmail.com"]
smtp_host: "smtp.gmail.com"
smtp_port: "587"
from_addr: "rashidmd777@gmail.com"
```

after i added above one i got email like this  "This is my alert body" not shown message alert

**Reply by nsano-rururu** [reply]
@MohdRashid01 

Now that I've found a bug, it doesn't work as expected,
According to the explanation according to the document, if only subject_text and alert_text are set as shown below, only that will be displayed.
![image](https://user-images.githubusercontent.com/22293449/119525008-1bec4300-bdb9-11eb-934b-ca3f00d1f30c.png)

**Reply by jertel** [reply]
@MohdRashid01 Good, now you can start to customize the alert_text, using variable substitution.

Ex:
```
alert_text_type: alert_text_only
alert_subject: "This is my alert subject"
alert_text: "Alert! {0}"
alert_text_args:
- message
```

@nsano-rururu Not sure I'm following. The way I'm reading the logic it looks correct. If the alert type is neither text-only nor text-jinja then include the rule text, top-counts, and match-items. That seems correct to me.

**Reply by nsano-rururu** [reply]
@jertel 

my misunderstanding. I'm sorry.
There was no problem in operation.

**Reply by w-HA** [reply]
to help our config ( change fields regarding yours )

alert_subject: "{0} {1} {2}"
alert_subject_args: ["service","resource","text"]

alert_text: |
    Begin problem at {0}
    Value : {1}
    Tags : {2}
alert_text_args: ["createTime","value","tags"]
alert_text_type: alert_text_only

w-HA

**Reply by MohdRashid01** [reply]
Hi Thanks
i have try to add but its not working

**Reply by jertel** [reply]
If you'd like more support you will need to provide further details such as screenshots of the emails after your latest attempts, elastalert logs, configurations, and anything else that you think will give us what we need to assist you.

**Comment by MohdRashid01** [comment]
Here is the email screenshot...yellow highlighted should not show in email....ONLY MESSAGES should show in email
![image](https://user-images.githubusercontent.com/7812871/120061096-25a3ce00-c079-11eb-9f59-8fb28440c855.png)

Here is the rules.yml file store in kibana of elasteralert
```
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: elasticsearch.example.com

es_host: elasticsearch.test.com
# (Optional)
# Elasticsearch port
#es_port: 14900
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword
es_username: testelastic
es_password: xxxx


# (Required)
# Rule name, must be unique
name: Exception Alert

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
#type: blacklist
type: any
include: ["message"]

 

# (Required)
# Index to search, wildcard supported
#index: logstash*
index: filebeat*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
#num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
#  hours: 1
#  minutes: 1
  seconds: 1

#compare_key: "message"

#blacklist:

#- "error"

realert:
  minutes: 5

 # This is send out all matches in one email
# aggregation:
#  minutes: 1

#  seconds: 0
#filter:
#- term:
#    message: "[error]"

#filter:
# - match:
 #   message: "job"

filter:
 - query:
      query_string:
 #       query: "message: exception AND  message: control"
        query: "message: job"
#filter:
#- query:
#   query_string:
#    query: "message: error"

alert:

- "slack"
- "email"


#- slack
slack_webhook_url: "https://hooks.slack.com/services/xxxxxxx"
#slack_username_override: "ElastAlert"
slack_username_override: "Mohd Rashid"

#- email
email: ["rashidmd777@gmail.com"]
smtp_host: "smtp.gmail.com"
smtp_port: "587"
from_addr: "rashidmd777@gmail.com"
```
If anything goes wrong do let know i have add include: ["message"] in my rules after that it showing above one screenshot high listed in yellow
