### DISCUSSION TITLE
Question about rule

### DISCUSSION THREAD

**Discussion by ngms17** [jertel/elastalert2#203] [Q&A] [answered]
I am trying to use ElastAlert with Suricata. My filter is currently like this.

```
filter:
- query:
    query_string:
      query: "suricata.eve.alert.signature: ET MALWARE"
```

I am not getting any hits though. I suspect that I have to put the exact value of "suricata.eve.alert.signature". 

But what I want to do is to alert on any log that contains the words ET MALWARE, independent of what type of ET MALWARE alert it is

**Comment by ferozsalam** [comment, marked as answer]
Are you able to post the sort of document you expect to match against? Feel free to redact anything specific to your organisation.

**Reply by ngms17** [reply]
Thanks for your reply.

I will use a different example. 

<img width="1338" alt="Screenshot 2021-05-31 at 09 58 04" src="https://user-images.githubusercontent.com/19928515/120168624-fe730b00-c1f6-11eb-9924-45e6e546edb6.png">

I want to match by "suricata.eve.alert.signature" field. This, for example, is the complete field for a rule that belongs to ET SCAN. What I want to do is to match any event that has the keywords "ET SCAN" on it.

If I do this I get matches.

```
filter:
- query:
    query_string:
      query: "suricata.eve.alert.signature: ET SCAN Possible WordPress xmlrpc.php BruteForce in Progress - Response" 
```
But I only want to do this and match any event that has ET SCAN on that field

```
filter:
- query:
    query_string:
      query: "suricata.eve.alert.signature: ET SCAN" 
```

**Reply by mrfroggg** [reply]
Try with
```
filter:
- query:
    query_string:
      query: "suricata.eve.alert.signature: ET SCAN*"
```
