### DISCUSSION TITLE
Cardinality Rule not working

### DISCUSSION THREAD

**Discussion by himanshigpta** [jertel/elastalert2#219] [Q&A] [answered]
Hi All, I've recently installed Elastalert2 on RHEL7 server, tested few rules & its working as expected! We've been using custom scripts for each alert but this seemed way better solution! But I'm unable to implement the Cardinality rule, my use case is pretty basic - I need an alert if any value in a field exceeds the threshold in last 10mins.
This is my config : 
```
index: hive*
name:  Hive Alerts

type: cardinality

cardinality_field: "loglevel"
max_cardinality: 10
query_key: "loglevel"

timeframe:
  hours: 4

alert:
- "email"

email:
- "redacted"
smtp_host: "redacted"
smtp_port: redacted
#testing subject
alert_subject: "ElastAlert: Loglevel {0} encountered at {1}"

alert_subject_args:
- loglevel
- "@timestamp"
```

Loglevel could be one of INFO, ERROR or WARN, and if any of these occur more than 10 times in last 4hours, an alert should be triggered.
I tried es_debug_trace which helped in some way, but I haven't achieved the expected result. I can see hits in the log but now matches, not sure why:
```
INFO:elastalert:Queried rule Hive Alerts from 2021-06-03 21:30 +0530 to 2021-06-03 21:45 +0530: 920 / 920 hits
INFO:elastalert:Ran Hive Alerts from 2021-06-03 21:30 +0530 to 2021-06-03 21:45 +0530: 920 query hits (370 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Hive Alerts range 900
INFO:elastalert:Background configuration change check run at 2021-06-03 21:46 +0530
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2021-06-03 21:46 +0530
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999692 seconds
INFO:elastalert:Queried rule Hive Alerts from 2021-06-03 21:31 +0530 to 2021-06-03 21:46 +0530: 1013 / 1013 hits
INFO:elastalert:Ran Hive Alerts from 2021-06-03 21:31 +0530 to 2021-06-03 21:46 +0530: 1013 query hits (919 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Hive Alerts range 900
INFO:elastalert:Background configuration change check run at 2021-06-03 21:47 +0530
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2021-06-03 21:47 +0530
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999796 seconds
INFO:elastalert:Queried rule Hive Alerts from 2021-06-03 21:32 +0530 to 2021-06-03 21:47 +0530: 1091 / 1091 hits
INFO:elastalert:Ran Hive Alerts from 2021-06-03 21:32 +0530 to 2021-06-03 21:47 +0530: 1091 query hits (1012 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Hive Alerts range 900
```

I've gone through lots of open/closed issues, tried multiple suggested solutions, but somehow cant make it work(trying for more than 2 days now)! The use case seems pretty straightforward for Elastalert2 I believe but I'm missing something, can anyone please help me debug or share a sample that I can refer maybe?

Thanks!

**Comment by jertel** [comment, marked as answer]
Cardinality is the measure of unique values for a given field. So the only way it would trigger is if you had 10 different log levels show up in a 4 hour timeframe. Ex: INFO, DEBUG, ERROR, WARN, TRACE, FATAL, VERBOSE, XXX, YYY, ZZZ.

I think what would make more sense for your need is a _frequency_ rule.

**Reply by himanshigpta** [reply]
@jertel Thanks for clearing the concept! I actually tried Frequency & even Spike with use_terms_query, but couldn't implement any of those properly either. This is one of the Frequency Rule configs that I tried:

```
name: Hive Alerts
type: frequency
index: hive*

num_events: 10
timeframe:
  hours: 4

doc_type: "doc"
use_terms_query: true
query_key: "loglevel.keyword"
top_count_number: 5
top_count_keys:
  - "loglevel"
#max_query_size: 0

aggregation_key: "loglevel.keyword"


#filter:
#- query:
#    query_string:
#      query: "loglevel: INFO"

alert:
- "email"

email:
- "redacted"
smtp_host: "redacted"
smtp_port: redacted
alert_subject: "ElastAlert: Loglevel {0} encountered at {1}"

alert_subject_args:
- loglevel
- "@timestamp"

summary_table_fields:
    - loglevel
    - host.name

```

The commented part actually worked for a particular field, but I dont want to hardcode each field, something more like GROUPBY so that if INFO(or WARN etc) exceeds threshold, alert is triggered. Also when I execute the query(obtained from es_debug_trace), I can see proper buckets :
 
![elastalert](https://user-images.githubusercontent.com/64949255/120691702-690c9b00-c4c4-11eb-925a-da4bfc41019a.PNG)

But still no alert is triggered, also it shows 0 hits in the log when I can see logs continuously getting ingested in ES.

**Reply by jertel** [reply]
It may need at least some filter to trip the hits > 0 check:
```
filter:
- query:
    query_string:
      query: "_exists_:loglevel"
```

**Reply by himanshigpta** [reply]
Thanks for the prompt response! I tried this filter, still getting 0 hits on the logs:
![server](https://user-images.githubusercontent.com/64949255/120696067-ba6b5900-c4c9-11eb-8774-135e511ebff0.PNG)

I can see logs on Kibana:
![kibana](https://user-images.githubusercontent.com/64949255/120696094-c3f4c100-c4c9-11eb-8ee4-ff66a21c2046.PNG)

Also I ran the query (from es_debug_trace), it's working fine:
![devConsole](https://user-images.githubusercontent.com/64949255/120696639-69a83000-c4ca-11eb-814e-b0aae1fb6231.PNG)

**Reply by jertel** [reply]
I recommend going back to the filter that did get hits and work from there, since that's closest to what you're looking to achieve. Then adjust that query to get to a point, either via a wildcard query, or something like the _exists_ check, where it no longer references those hard coded log levels.

**Reply by himanshigpta** [reply]
@jertel Thanks! I'll try what you've suggested. :)

**Reply by himanshigpta** [reply]
I think I've got the config near to what I need:

```
name: new Hive Frequency Alerts
type: frequency
index: hue*
num_events: 1

timeframe:
  minutes: 10

doc_type: "doc"
#use_terms_query: true
query_key: "loglevel.keyword"
top_count_number: 5
top_count_keys:
  - "loglevel"

aggregation_key: "loglevel.keyword"

filter:
- query:
    query_string:
      query: "_exists_:loglevel"

alert:
- "email"

email:
- "redacted"
smtp_host: "redacted"
smtp_port: redacted
alert_subject: "ElastAlert: Loglevel {0} encountered at {1}"

alert_subject_args:
- loglevel
- "@timestamp"

summary_table_fields:
    - loglevel
    - hostname
    - num_hits
```

I'm just stuck on one thing, can't get the aggregate result in 1 alert:

Adding below didn't help:
```
aggregation:
  minutes: 5
```
