### DISCUSSION TITLE
Alert only during specific period of the day

### DISCUSSION THREAD

**Discussion by pradeepgadkari** [jertel/elastalert2#244] [Q&A] [answered]
We have an application which writes log only during specific time in a day. Below is my rule but we still get an alert at 8:00 German time(6:00 UTC) for number of logs not meeting threshold(The query is run within the limit_execution time but the condition of the query is from 18:00-6:00 when there are no logs,hence the alert )
```
# Type of alert.
type: flatline

# Alert when this many documents matching the query occur within a timeframe
threshold: 1
use_terms: true

# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 10
realert:
  minutes: 30

exponential_realert:
  hours: 2

limit_execution: "* 6-18 * * *"

# 24H mode and UTC time
start_time: "6:00"
end_time: "18:00"
# Drop match and cancel alert if (inside/outside) range
drop_if: "outside"
```

Is the rule correct or do I need to make any changes? 
p.s: Running elastalert on docker

**Comment by nsano-rururu** [comment]
I don't think drop_if are implemented, where did you get the information?

**Comment by nsano-rururu** [comment, marked as answer]
I don't think limit_execution will throw out alerts outside the specified time

**Reply by nsano-rururu** [reply]
@pradeepgadkari

I think I set start_time, end_time, and drop_if by looking at the following, but it is not in the standard function.

https://github.com/0xSeb/elastalert_hour_range/blob/master/flatline_rule.yaml

```yaml
# 24H mode and UTC time (UTC +2 in France so the range is 6am 10pm)
start_time: "4:00"
end_time: "20:00"
# Drop match and cancel alert if (inside/outside) range
drop_if: "outside"
````
