### DISCUSSION TITLE
Observables for TheHive

### DISCUSSION THREAD

**Discussion by akiradreams** [jertel/elastalert2#248] [Q&A] [answered]
I have the rule already created, but it doesn't send me any observable no and I don't know what the problem is, the alert is created but without any observable.
Code:

```
name: demo
type: frequency
index: filebeat-*

num_events: 3

timeframe:
  hours: 1

realalert:
  minutes: 0

filter: []

alert: hivealerter

hive_connection:
  hive_host: http://xxx.xxx.xxx.xxx
  hive_port: 9000
  hive_apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  hive_proxies:
    http: ''
    https: ''

hive_alert_config:
  title: 'Test For Alerts'
  type: 'external'
  source: 'elastalert'
  description: '{match[message]}'
  severity: 2
  tags: ['elastalert', 'from {rule[name]}']
  tlp: 3
  status: 'New'
  follow: True

hive_observable_data_mapping:
  - alert: "{match[dissect.alert]}"
```

The dissect.alert, is a field created with the dissect option of filebeat.

Thanks for reading :)

**Comment by ferozsalam** [comment, marked as answer]
It looks like you're using the old-style TheHive alerter syntax. Which version of ElastAlert are you using? If you're using the latest version of ElastAlert, you need to use the syntax described in the documentation here: https://elastalert2.readthedocs.io/en/latest/ruletypes.html#thehive

**Reply by akiradreams** [reply]
I'm using this one:
https://elastalert.readthedocs.io/en/latest/running_elastalert.html#creating-a-rule

**Reply by ferozsalam** [reply]
That's the old documentation site for the original ElastAlert package. If you're using an old version of ElastAlert, that website will be correct.

If you're using a new version of ElastAlert (ElastAlert 2), you will need to use the syntax documented in my link above.

**Reply by ferozsalam** [reply]
Specifically which version of ElastAlert are you running?

**Reply by akiradreams** [reply]
I will update elastalert now.

**Reply by pandvan** [reply]
Hi @ferozsalam, I'm working on the migration of TheHive alerter rules to support the new syntax introduced with ElastAlert 2.1.0. It seems no more possible to directly access match fields and no all keys of `hive_alert_config` support match fields lookup.
For example, I need to set `source` to a matched field (dynamically created by a match enhancement) but cannot find a way to refer it. Only top-level rule data can be referred using dollar ($) syntax. Is there any way I can refer a matched field?

As @SkytheK question suggest, is not any way to interpolate matched fields or rule data to create "computed" tags?

**Reply by ferozsalam** [reply]
Hey @pandvan - interpolation from match data is still possible, yes, but the syntax has changed. See the `tags` field here: https://elastalert2.readthedocs.io/en/latest/ruletypes.html#thehive

We are using this internally and it works. Does this not work for you, or have you not updated with the new syntax?

**Reply by ferozsalam** [reply]
Ah, I see @pandvan, is it that you want to interpolate on the `source` field as well?

Yep, that isn't possible in the new version, but that is something that would be reasonably easy to add back in.

Before I start working on a diff, could you give me an example use case for this feature? This will help in testing.

**Reply by akiradreams** [reply]
> Specifically which version of ElastAlert are you running?

elastalert 0.2.4

**Reply by pandvan** [reply]
> Ah, I see @pandvan, is it that you want to interpolate on the `source` field as well?

Yes.

> Before I start working on a diff, could you give me an example use case for this feature? This will help in testing.

In our case we're trying to achieve some soft of "multi tenancy" so we use source field on TheHive to store tenant name.
Matched field is created by a simple Enhancement

```
class MarkTenant(BaseEnhancement):
    def process(self, match):
        e = Env()
        try:
            tenant_name = e('TENANT_NAME')
        except:
            tenant_name = "Unknown tenant"
        match['tenant'] = tenant_name
```

Regarding this particular use case we have resolved as of now ElastAlert 2 can directly use environment variables on YAML definition.
But I think it could be useful anyway to let source field to be interpolated.

About `tags`, and interpolation in general, if I have a matched field named `source.ip` how can I create a tag with value `IP address: source.ip`? Is it possible ti mix a literal string and a matched field as it was possible before? Made some trials with different syntax, but no one seems to work.

**Reply by akiradreams** [reply]
Well i have the same error with elastalert2

**Reply by akiradreams** [reply]
ERROR:elastalert:Error while running alert hivealerter: Error posting to TheHive: 404 Client Error: Not Found for url: http://localhost:9000/api/alert

**Reply by ferozsalam** [reply]
@SkytheK where is your TheHive instance located? It seems like ElastAlert isn't able to resolve the URL at all, which sounds like a different issue to the one you originally reported.

**Reply by akiradreams** [reply]
It is not the same because I get that error, but the reason is the same, the dissect.alert does not detect it as a valid field, and in the hive_alert_config the part: 
```
customFields:
    - name: example
      type: string
      value: example
```
It causes me errors and I do not know what is the reason, as well as the:
```
- alert: dissect.alert
```
But when I use this part it doesn't return me the error but it doesn't make me any observable either.
```
- alert: '{match[dissect.alert]}'
```
