### DISCUSSION TITLE
Numeric values for TheHive observables

### DISCUSSION THREAD

**Discussion by pandvan** [jertel/elastalert2#254] [Q&A] [answered]
It seems not possible to set a numeric value for a TheHive observable.
I’m trying to do the following:
```
hive_observable_data_mapping:
 - ip: client.ip
 - ip: server.ip
 - other: destination.geo.country_iso_code
 - other: client.user.name
 - other: destination.as.organization.name
 - autonomous-system: destination.as.number
 - url: url.original
```

where `destination.as.number` is a numeric value as per ECS schema definition (https://www.elastic.co/guide/en/ecs/1.7/ecs-as.html). The issue arises with any numeric matched field.

What is the correct way to deal with them?
