### DISCUSSION TITLE
Terms filter not working

### DISCUSSION THREAD

**Discussion by ngms17** [jertel/elastalert2#297] [Q&A] [answered]
My rule config is like this: 

```
filter:
- terms:
    rule.category: ["Denial of Service", "Executable code was detected", "A Network Trojan was detected", "Detection of a Denial of Service Attack", "Targeted Malicious Activity was Detected", "Exploit Kit A$
    suricata.eve.in_iface: ["enp3s0f0", "enp3s0f1"]
```

Although, this is not working giving me this error.

`ERROR:root:Error running query: RequestError(400, 'x_content_parse_exception', '[terms] query does not support multiple fields')`

**Comment by nsano-rururu** [comment]
look

terms does not support multiple fields
https://github.com/Yelp/elastalert/issues/2109

**Comment by jertel** [comment, marked as answer]
Change your filter to:

```
filter:
- terms:
    rule.category: ["Denial of Service", "Executable code was detected", "A Network Trojan was detected", "Detection of a Denial of Service Attack", "Targeted Malicious Activity was Detected", "Exploit Kit A$
- terms: 
    suricata.eve.in_iface: ["enp3s0f0", "enp3s0f1"]
```

NOTE: This is an AND query, so both terms must match at least one entry in their value list.

**Reply by nsano-rururu** [reply]
The document has the following description, so it seems better to correct it.

https://elastalert2.readthedocs.io/en/latest/recipes/writing_filters.html#id1

current

```
- terms:
    fieldX: ["value1", "value2"]
    fieldY: ["something", "something_else"]
    fieldZ: ["foo", "bar", "baz"]
```

update

```
- terms:
    fieldX: ["value1", "value2"]
- terms:
    fieldY: ["something", "something_else"]
- terms:
    fieldZ: ["foo", "bar", "baz"]
```
