### DISCUSSION TITLE
Doc update? booleans and negation

### DISCUSSION THREAD

**Discussion by TheNoButton** [jertel/elastalert2#330] [Ideas]
FYI, for https://elastalert2.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or

> For Elasticsearch 2.X, any of the filters can be embedded in not, and, and or:
> [ ... yaml example ... ]
> For Elasticsearch 5.x, this will not work and to implement boolean logic use query strings:

I'm on 7.x and was able to use `bool` `must` and `must_not` instead of a query string

```yaml
filter:
    - term:
        action: order
    - terms:
        dining:
            - pickup
            - delivery
    - bool:
        #exclude common/expected orders
        must_not:
            #Alice usually gets a pizza
            - bool:
                must: [ {term: {uid: alice}}, {term: {menu_item: pizza}} ]
            #Bob loves his hoagies 
            - bool:
                must: [ {term: {uid: bob}}, {term: {menu_item: sandwich}} ]
            #Charlie has a few favorites
            - bool:
                must:
                   - term:
                       uid: charlie
                   - match:
                       menu_item: "burrito pasta salad pizza"
```
