### DISCUSSION TITLE
`hive_alert_config` title and description fields

### DISCUSSION THREAD

**Discussion by shortstack** [jertel/elastalert2#339] [Q&A] [answered]
Hi,

We've had the following in our alert configuration prior to the latest upgrade. It was working as expected.

Now, these fields no longer render properly and the docs are a little confusing regarding how the variables in the title and description should be formatted.

Can someone clarify what the proper format is? I've tried several and it just spits out the text instead of the actual variable content and at this point it would be quicker to ask than to keep fighting it.

The tags render fine, but the title and description do not.

Thanks in advance.

Praeco v1.8.8 and ElastAlert v2.1.2

```
hive_connection:
   hive_host: 
   hive_port:
   hive_apikey: 

hive_alert_config:
  title: "ElastAlert - {match[rule][title]} - {match[agent][hostname]}"
  type: 'external'
  source: 'elastalert'
  description: |
    {match[rule][title]}


    **Hostname:** {match[agent][hostname]}


    **Timestamp:** {match[@timestamp]}


    **Message:** {match[message]}
  severity: 2
  tags: ['elastalert', '{match[rule][title]}', '{match[rule][level]}', '{match[clientid]}']
  tlp: 3
  status: 'New'
  follow: True
```
