### DISCUSSION TITLE
hive_observable_data_mapping not working for TheHive4

### DISCUSSION THREAD

**Discussion by siemproduct** [jertel/elastalert2#348] [Q&A] [answered]
Hi Team,
I am using TheHive4.1.7 and trying to create a case via Elastalert.

The case is being created fine but when it comes to observables or titles or any custom fields, it is not working as expected.

I see the variable input instead of actual value in TheHIve4 alert section. Example: {rule[name]}

elast.yaml is as below:
`hive_connection:
  hive_host: http://1.1.1.1/
  hive_port: 1000
  hive_apikey: key-here
hive_alert_config:
  title: '{rule[name]}'
  type: 'test'
  source: 'test'
  description: '{rule[name]}'
  severity: 2
  tags: ['{rule[name]}']
  tlp: 3
  status: 'New'
  follow: True
include: [message]
hive_observable_data_mapping:
    - message: "{match[message]}"
`

PFA screenshot
![image](https://user-images.githubusercontent.com/83961218/126118161-7fce2475-6e36-47d1-aad2-cd36ef8c3c36.png)

**Comment by ferozsalam** [comment, marked as answer]
Which version of ElastAlert are you using? Can you post your rule definition? And finally, can you link me to the documentation you are using to define the rule?

**Reply by ferozsalam** [reply]
The discussion [here](https://github.com/jertel/elastalert2/discussions/339) might also help you.

**Reply by siemproduct** [reply]
I believe the problem is with the doc I am referring to.
I am using Elastalert2. I changed my config to https://elastalert2.readthedocs.io/en/latest/ruletypes.html#thehive

I am using 2.1.2 release.

But now I see error is below in logs
Jul 19 12:59:08 e2e-84-157 python3[770862]: ERROR:elastalert:Error while running alert hivealerter: Error posting to TheHive: 404 Client Error: Not Found for url: http://1.1.1.1:9000/api/alert

`hive_connection:
  hive_host: http://1.1.1.1
  hive_port: 9000
  hive_apikey: test

hive_alert_config:
  customFields:
    - name: orgname
      type: string
      value: abc
    - name: tenant
      type: integer
      value: 333
  follow: True
  severity: 2
  status: 'New'
  source: 'test'
  description: 'test'
  tags: rule.orgname
  tlp: 3
  type: 'external'

hive_observable_data_mapping:
  - agent.name: agent.name`

Although, TheHIve is accessible and working fine.

**Reply by siemproduct** [reply]
I was able to create a ticket in TheHive. Now the only issue that remains is with observables.
Here is my observable config:
hive_observable_data_mapping:
  - agent-name: agent.name

The Error I see is in TheHive is as below:
org.thp.scalligraph.NotFoundError: ObservableType agent-name not found

**Reply by siemproduct** [reply]
Was able to get that done as well with the below config.

Now the question remains is, why it was not working with agent.name or agent-name

hive_observable_data_mapping:
  - hostname: agent.hostname
  
 Is . or - or _ is not supported in the mapping field?

**Reply by siemproduct** [reply]
Even hostName is not allowed.

Only lowercase are allowed, is that correct?

org.thp.scalligraph.NotFoundError: ObservableType hostName not found

**Reply by siemproduct** [reply]
Even this did not work, confused now.

ObservableType eventcode not found

hive_observable_data_mapping:
  - hostname: agent.hostname
  - eventcode: event.code
  - eventcreated: event.created
  - clientip: client.ip
  - sourceip: source.ip

**Reply by siemproduct** [reply]
This is my kibana query:
name: "login failure in past 1 minutes"
type: frequency
index: winlogbeat-*
num_events: 1
timeframe:
  minutes: 1
filter:
- query:
    query_string:
      query: "orgname:abc AND event.code:4625"

**Reply by ferozsalam** [reply]
See [here](https://github.com/jertel/elastalert2/discussions/248#discussioncomment-839624)

TheHive only supports a limited, pre-defined number of bbservable types. For example the IPs need to be represented like:

```
- ip: client.ip
- ip: source.ip
```

**Reply by siemproduct** [reply]
Thanks @ferozsalam that helped.

**Reply by ZainULArfeen** [reply]
Assalam o Alikum @ferozsalam,
Hope you are doing well, we are using TheHive 4.1.10-1 and we are writing rules, everything is working fine but we are having trouble with the CustomFields. We want to get agentname, srcip etc in customFields, below is the file we are using when we run elastalert service we get this error 

`"ERROR:elastalert:Error while running alert hivealerter: Error posting to TheHive: 404 Client Error: Not Found for url: https://192.168.142.74"`

Here is the rule we are trying:

```
es_host: 104.207.142.74
es_port: 9200
name: Wazuh-Rule-ID
type: frequency
index: wazuh-alerts-4.x-*
num_events: 1
timeframe:
    hours: 1
filter:
- term:
    rule.level: "5"

# Alternative for the Title
alert_subject_args:
- rule.description
alert_subject: "{0}"

#Alternative for the description
alert_text_args: [ "rule.description", "agent.name", "@timestamp", "full_log" ]
alert_text_type: alert_text_only
alert_text:  |
     '{0} . {2}'

realert:
  minutes: 0
alert: hivealerter
hive_connection:
  hive_host: https://104.207.142.111
  hive_port: 443
  hive_apikey: zBOlBlfBY/6neow6L0HVxBPK2VcP0Tc2

hive_alert_config:
  customFields:
    - name: Agent Name
      type: string
      value: agent.name

  type: 'Security Logs'
  source: 'elastalert'
  severity: 2
  tags: ["agent.name", "agent.id", "rule.description"]
  tlp: 3
  status: 'New'
  follow: True

hive_observable_data_mapping:
    - ip: agent.ip
```
