### DISCUSSION TITLE
elastalert-test-rule运行规则生效，而使用python3 -m elastalert.elastalert --config config.yaml --verbose --rule rules/test_frequency.yaml命令不生效

### DISCUSSION THREAD

**Discussion by Zinl** [jertel/elastalert2#368] [Q&A] [answered]
使用elastalert-test-rule可以用 如上图使用elastalert命令不运行规则 配置文件如下 规则文件
![image](https://user-images.githubusercontent.com/30452652/127127910-3036a37d-1c51-4f18-b67e-2c43145cda23.png)
![image](https://user-images.githubusercontent.com/30452652/127127958-3dae5460-e662-49da-b8b6-0600adaba799.png)
但是使用elastalert命令不执行规则

**Comment by nsano-rururu** [comment, marked as answer]
What language? .. China?

**Reply by nsano-rururu** [reply]
Did you read the following content?

ElastAlert 2 - Project Guidelines
https://github.com/jertel/elastalert2/discussions/11

**Reply by nsano-rururu** [reply]
- Why don't you provide the settings in the config.yaml and rule yaml files?
- What is the version of elastalert2?
- Does elastalert-create-index match with the recognition that it has been executed?
https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#setting-up-elasticsearch

**Reply by Zinl** [reply]
是的，这是中文。
这是config.yaml
![image](https://user-images.githubusercontent.com/30452652/127793759-a1187b33-46d1-4dd5-9d74-d89703a9574e.png)
![image](https://user-images.githubusercontent.com/30452652/127793825-90fab8f0-82c2-48a3-b362-a3fb785648ba.png)
这是rule
![image](https://user-images.githubusercontent.com/30452652/127793898-960b05e4-a572-44e5-b7a2-6f83a5cc51d8.png)
![image](https://user-images.githubusercontent.com/30452652/127793914-665fa459-2705-40db-9acc-e81159ef2f37.png)
![image](https://user-images.githubusercontent.com/30452652/127793930-8af33147-54ad-4ab4-a8c5-4e3fcba045d6.png)
elastalert2版本是最新版
elastalert-create-index可用，已建立elastalert_status索引
![image](https://user-images.githubusercontent.com/30452652/127794219-bcbea448-ea4f-4d2e-8a0a-58fcb0b6d396.png)

**Reply by nsano-rururu** [reply]
Try with
```yaml
filter:
- query:
    query_string:
      query: "_type: log"
```

**Reply by Zinl** [reply]
没有变化，还是一样

**Reply by nsano-rururu** [reply]
If the monitoring rule conditions are not matched within the period specified by buffer_time, nothing happens. With this setting, if "_type: log" has not occurred once in 4 hours (timeframe) in the past 15 minutes (buffter_time), it will not be notified.
Is it really the setting you wanted to set?
Are time_frame and buffter_time set in reverse?

**Reply by nsano-rururu** [reply]
example

If the monitoring rule conditions are not matched within the period specified by buffer_time in config.yaml, nothing happens. With this setting, you will not be notified unless there are 10 requests for status code 500 in the past 1 hour in 5 minutes.

Next, send a request with status code 500 10 times or more to match the monitoring conditions.


config.yaml

```yaml
es_host: localhost
es_port: 9200
rules_folder: rules
buffer_time:
  hours: 1
run_every:
  minutes: 1
writeback_index: elastalert_status

```

rule

```yaml
name: status500-moniroting
type: frequency
index: logstash-*
num_events: 10
timeframe:
    minutes: 5
filter:
  - term:
      response: 500
alert:
  - slack
slack_webhook_url: "https://hooks.slack.com/services/xxxxxxxxx/xxxxxxxx/xxxxxxxxxxxxxxxxxxx"
```
