### DISCUSSION TITLE
How to attach the query results to email alert with elastalert2?

### DISCUSSION THREAD

**Discussion by rameshar16** [jertel/elastalert2#379] [Q&A] [answered]
Hi,

Please let me know how to attach the query results to email alert with elastalert2.

Thanks and Regards,
Ramesh

**Comment by jertel** [comment, marked as answer]
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#alert-content

**Reply by rameshar16** [reply]
Thank you @jertel for the update.

Could you please provide the right parameters to attach the search and attach the query results to the the email.

Thanks and Regards,
Ramesh

**Reply by nsano-rururu** [reply]
@rameshar16 

Does that mean you don't understand after looking at the following?

email setting document
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#email

example
https://github.com/jertel/elastalert2/tree/master/examples/rules

**Reply by nsano-rururu** [reply]
@rameshar16 

example

"xxxx" in the email address part is not the value actually set.
Please set the correct value when actually setting.

```yaml
name: a
type: frequency
alert:
  - email
alert_subject: a
alert_subject_args: []
alert_text: b
alert_text_args: []
email:
  - xxxx@gmail.com
filter:
  - query:
      query_string:
        query: 'message:Quit'
from_addr: xxxx@yahoo.co.jp
smtp_host: 'smtp.mail.yahoo.co.jp'
smtp_port: 465 
smtp_ssl: true
smtp_auth_file: '/opt/elastalert/pass/smtp_auth_user.yaml'
index: mariadblog-*
is_enabled: true
num_events: 1
realert:
  minutes: 1
terms_size: 50
timeframe:
  minutes: 1
timestamp_field: '@timestamp'
timestamp_type: iso
use_strftime_index: false
```

"xxxx" in the email address and password part is not the value actually set
Please set the correct value when actually setting.

/opt/elastalert/pass/smtp_auth_user.yaml

```yaml
user: 'xxxx@yahoo.co.jp'
password: 'xxxx' 
```

**Reply by nsano-rururu** [reply]
@rameshar16

There is a bug that does not work properly when the address of microsoft 365 is specified for from_addr. Please be careful.
This is a bug from [Yelp/elastalert](https://github.com/Yelp/elastalert).

**Reply by nsano-rururu** [reply]
@rameshar16 

If you want to specify the gmail address in from_addr, you need to change the following settings.

Google account in advance → Apps that can access the account → Allow less secure apps: Disabled → Enabled
When I specified the Gmail address with from_addr and checked the operation, the problem \
![99171322-58c0e880-274b-11eb-86c8-2dfb30b20f7f](https://user-images.githubusercontent.com/22293449/127713258-af66920d-8c0a-4661-bdec-46298cc532a2.png)
![99171323-5e1e3300-274b-11eb-9f62-3cf093578215](https://user-images.githubusercontent.com/22293449/127713279-bbbad94e-a9ce-4be6-809b-67951f766071.png)
![99171325-61192380-274b-11eb-9004-11c3e7d05b0d (1)](https://user-images.githubusercontent.com/22293449/127713338-b9ec07e0-e7ae-47fc-b1f6-43e2e3e283af.png)


The difference in the settings related to gmail in the previous sample is as follows.

When using 587 for smtp_port

```yaml
from_addr: xxxx@gmail.com
smtp_host: 'smtp.gmail.com'
smtp_port: 587
smtp_auth_file: '/opt/elastalert/pass/smtp_auth_user.yaml'
```

When using 465 for smtp_port

```yaml
from_addr: xxxx@gmail.com
smtp_host: 'smtp.gmail.com'
smtp_port: 465
smtp_ssl: true
smtp_auth_file: '/opt/elastalert/pass/smtp_auth_user.yaml'
```


"xxxx" in the email address and password part is not the value actually set
Please set the correct value when actually setting.

/opt/elastalert/pass/smtp_auth_user.yaml

```yaml
user: 'xxxx@gmail.com'
password: 'xxxx' 
```
