### DISCUSSION TITLE
bool operations not working

### DISCUSSION THREAD

**Discussion by zayalaksme** [jertel/elastalert2#390] [Q&A] [answered]
Hello Jertel,

Expecting: match 2 events/logs, one is 8.8.8.8 (google) ping  up and 2nd event/log is tcp port down.
I am tryng Bool and must as shown in below rule, but there are no query hits? I followed the bool as showing in documentation (https://elastalert2.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or).  I am seeing logs/events in kibana discovery.
``````
es_host: "10.250.10.63"
es_port: 5555
name: DOWNSERVICE
type: any
index: heartbeat-*
include:
  - message
num_events: 05
timeframe:
  seconds: 60
filter:
- bool:
    must:
      - bool:
          must: [ {term: {monitor.name: GOOGLE}}, {term: {monitor.status: up}} ]
      - bool:
          must: [ {term: {monitor.type: tcp}}, {term: {monitor.status: down}} ]
query_key: url.full
old_query_limit:
  hours: 1
alert:
- "debug"
````````````

**Comment by jertel** [comment, marked as answer]
You probably want to use `should` instead of `must` on the outer bool block. As you have it written now it is requiring both monitor.name = GOOGLE AND monitor.name = tcp, which is impossible. Study this blog post to better understand the bool concept: https://www.elastic.co/blog/lost-in-translation-boolean-operations-and-filters-in-the-bool-query

**Reply by zayalaksme** [reply]
Hello Jertel, Thank you for your reply. 

Is elastalert can query the 2 logs/events at the same time? 

In above shared link i am seeing using the "must" to match prefference1 and preference2. Like this can below booll script will work?  If it doesnt work can you please guide me in the correct way?

I am expecting this rule to send an alert if GOOLE ip is reachable and internet/wan link down in remote site.

`````
filter:
- bool:
    must:
      - bool:
          must: [ {term: {monitor.name: GOOGLE}}, {term: {monitor.status: up}} ]
      - bool:
          must: [ {term: {monitor.name: INTERNETDOWN}}, {term: {monitor.status: down}} ]
query_key: url.full
`````````````
