### DISCUSSION TITLE
It seems that the description of the download_dashboard document is incorrect.

### DISCUSSION THREAD

**Discussion by nsano-rururu** [jertel/elastalert2#391] [Ideas]
I found a statement in a previous issue on yelp / elastalert that the download_dashboard documentation was incorrect. Since download_dashboard is not used, we have not confirmed the operation.
Also, since it is described as kibana3, it is unknown whether it will work with kibana3 or later.

filter download_dashboard AttributeError: 'dict' object has no attribute 'insert'
https://github.com/Yelp/elastalert/issues/1481

**Comment by nsano-rururu** [comment]
There is information that it does not work with Kibana 5

Load filters from a Kibana 5 dashboard
https://github.com/Yelp/elastalert/issues/949

**Reply by nsano-rururu** [reply]
Looking at the source code, it seems that Kibana 5 and 6 are compatible, and kibana 7 is not.
https://github.com/jertel/elastalert2/blob/master/elastalert/rule_from_kibana.py

**Reply by nsano-rururu** [reply]
I also checked `use_kibana4_dashboard`.
Since it worked with kibana 7.14.0, kibana 7 is also supported.

example 

```yaml
alert_text: "{}"
alert_text_args:
  - "kibana_link"
use_kibana4_dashboard: "http://127.0.0.1:5601/app/kibana#/dashboard/07bdfc10-f7fd-11eb-84fa-a33bdb7fffd8"
```

07bdfc10-f7fd-11eb-84fa-a33bdb7fffd8 is Dashboard ID.
