### DISCUSSION TITLE
run_every on frequency base

### DISCUSSION THREAD

**Discussion by paul-mesnilgrente** [jertel/elastalert2#422] [Q&A] [answered]
Hi, I have this rule:

```yaml
---
name: Unexpected Container State
type: frequency
timeframe:
  minutes: 5
num_events: 1
filter:
- term:
    "kubernetes.container.status.reason": "CrashLoopBackOff"
...
```

I created a container which is constantly crashing to trigger the alert. Although, I was expecting the alert to trigger every 5 minutes. Looks like I got that wrong. Is there anyway of doing this without using the `run_every` global configuration? I'd like to set this on each rule.

Also, ideally it would trigger in the minute if something happens and then alert every 5 minutes. But I could do if it was just checking every 5 minutes.
