### DISCUSSION TITLE
new_term rule with query

### DISCUSSION THREAD

**Discussion by gyterpena** [jertel/elastalert2#440] [Q&A] [answered]
Is it possible to have new_term rule with query filter? I have following rule that seems to work ok
```
name: Example new term rule
type: new_term
index: filebeat-*
fields:
 - "source.ip"
terms_window_size:
  days: 1
filter:
- term:
    source.homenet: "*"
alert:
- "email"
```

When I change it to 

```
name: Example new term rule
type: new_term
index: filebeat-*
fields:
 - "source.ip"
terms_window_size:
  days: 1
filter:
- query:
    query_string:
      query: (source.homenet:* AND source.ip:(192.168.0.0/24 OR 172.21.0.0/24))

alert:
- "email"
```
Elastalert fails to start. I get following error message.

```
{"log":"  File \"/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py\", line 91, in perform_request\n","stream":"stderr","time":"2021-09-01T11:59:35.973095691Z"}
{"log":"    self._raise_error(response.status_code, raw_data)\n","stream":"stderr","time":"2021-09-01T11:59:35.973203365Z"}
{"log":"  File \"/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py\", line 131, in _raise_error\n","stream":"stderr","time":"2021-09-01T11:59:35.973214836Z"}
{"log":"    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n","stream":"stderr","time":"2021-09-01T11:59:35.973714682Z"}
{"log":"elastalert.util.EAException: Error initializing rule Example new term rule: Error searching for existing terms: RequestError(400, 'x_content_parse_exception', {'error': {'root_cause': [{'type': 'parsing_exception','reason': 'unknown query [query]', 'line': 1, 'col': 231}], 'type': 'x_content_parse_exception', 'reason': '[1:231] [bool] failed to parse field [must]', 'caused_by': {'type': 'parsing_exception', 'reason': 'unknown query [query]', 'line': 1, 'col': 231, 'caused_by': {'type': 'named_object_not_found_exception', 'reason': '[1:231] unknown field [query]'}}}, 'status': 400})\n","stream":"stderr","time":"2021-09-01T11:59:35.973736524Z"}
{"log":"\n","stream":"stderr","time":"2021-09-01T11:59:35.973746839Z"}
```

Elastalert 2.2.1(docker)
ES 7.14

**Comment by gyterpena** [comment, marked as answer]
Edit: 
When I change rule to

```
name: Example new term rule
type: new_term
index: filebeat-*
fields:
 - "source.ip"
terms_window_size:
  days: 1
filter:
- query_string:
    query: "(source.homenet:* AND source.ip:(192.168.0.0/24 OR 172.21.0.0/24))"
alert:
- "email"
```

Elastalert will start.
