### DISCUSSION TITLE
Auto resolve for Pagerduty not always auto resolving - how to debug?

### DISCUSSION THREAD

**Discussion by phlegx** [jertel/elastalert2#441] [Q&A] [answered]
Hi there!

I created extra rules that provide me with auto resolve capability. It works actually pretty good, but sometimes the auto resolve - for example for checking if an HTTP endpoint is again available - is not working. Then of course the Alert remains unresolved in Pagerduty until I resolve it manually.

Any ideas on how to debug this so I can fix this? Is there another way of implementing auto resolve with Elastalert2?

Here is  my auto-resolve rule for HTTP endpoints (This is a template for Terraform):

```
name: "[${project_name}]][${environment}] HTTP ${name} ${severity} resolved"
description: Monitors HTTP status ${environment} environment
type: frequency
index: ${project_shortcut}-heartbeat-${environment}*
num_events: 1
timeframe:
  minutes: 1

- query:
    query_string:
      query: "monitor.status: up AND url.full: \"${full_url}\" AND monitor.type: http"


alert_subject: "[${project_name}]][${environment}] HTTP ${name} - {0} resolved"
alert_subject_args:
- url.full
- host.name

realert:
  minutes: 1
alert:
  - pagerduty

pagerduty_service_key: "${pagerduty_integration_key}"
pagerduty_client_name: "Elastalert"
pagerduty_event_type: "resolve"

pagerduty_api_version: "v2"
pagerduty_v2_payload_severity: "${severity}"
pagerduty_v2_payload_source: host.name
pagerduty_incident_key: "${project_shortcut}-${environment}-http-${full_url}-${severity}"
```

thanks in advance!
