### DISCUSSION TITLE
Shorten kibana_discover_url links

### DISCUSSION THREAD

**Discussion by pandvan** [jertel/elastalert2#445] [Q&A] [answered]
Would it be feasible to use the shorten form for generated `kibana_discover_url` URLs?
Kibana exposes an [API](https://www.elastic.co/guide/en/kibana/7.10/url-shortening-api.html) that permits to abbreviate the otherwise very long URLs. Don't know if there is a way to compute them without using the API.

This question arose because I had an issue with a SOAR that is used to further manage TheHive alerts after ElastAlert create them. As the URL is full of escaping characters the JSON parser of the SOAR get crazy. Of course, this is not related to ElastAlert anyway but perhaps short links can be handy also for someone else.

**Comment by nsano-rururu** [comment, marked as answer]
kibana_discover_url is generated inside elastalert2, so I wonder if you can use a shortened URL. I think that it is useless if you do not generate a shortened URL after changing to the implementation and generating it internally in elastalert2.

**Reply by jertel** [reply]
To put it another way, shortened URLs aren't _computed_ in Elasticsearch. They are _mapped_ to a unique, generated ID and that mapping exists only inside of Elasticsearch. So without using the API there is no way to obtain a shortened URL.

That said, yes, it's possible to support this but it will require modification to the `kibana_discover.py` and/or `elastalert.py` files inside ElastAlert 2. Alternatively, if you aren't ready to submit a PR meeting the contribution guidelines of this project, you could create a custom [enhancement](https://elastalert2.readthedocs.io/en/latest/recipes/adding_enhancements.html) for your deployed environment. The enhancement would intercept the URL before it goes to the alerter, exchange it with Elasticsearch's API for a short URL, and then replace the URL in the match data so that the alerter has the shortened URL.

**Comment by wajika** [comment]
I also faced similar problems. I use wechat as an alarm device. Wechat limits each message to 2048 bytes, but the length of the kibana url at least occupies 1000 bytes,and finally the entire message is truncated.   
![image](https://user-images.githubusercontent.com/17058349/132187148-49128ed6-6e18-4538-be88-b2f48f45bc9e.png)
I feel that kibana url wastes too much space.

**Reply by nsano-rururu** [reply]
It is convenient to have such a simple setting. The current kibana_discover is not easy to use because there are too many items to set.

rule1

```yaml
# Normal kibana_discover_url
# use_kibana_discover: "http://localhost:5601/app/kibana#/discover?_g=()&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:15,i:'1',w:24,x:0,y:0),id:'8f4d0c00-4c86-11e8-b3d7-01146121b73d',panelIndex:'1',type:visualization,version:'7.0.0-alpha1')),query:(language:lucene,query:''),timeRestore:!f,title:'New%20Dashboard',viewMode:edit)"

# use_kibana_discover is set in kibana_discover_url
alert_text: '{0}'
alert_text_args: [ kibana_discover_url ]
alert_text_type: alert_text_only
```

output1

```
http://localhost:5601/app/kibana#/discover?_g=()&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:15,i:'1',w:24,x:0,y:0),id:'8f4d0c00-4c86-11e8-b3d7-01146121b73d',panelIndex:'1',type:visualization,version:'7.0.0-alpha1')),query:(language:lucene,query:''),timeRestore:!f,title:'New%20Dashboard',viewMode:edit)
```

rule2

```yaml
# Specify the shortened URL obtained by the Shorten URL API
use_kibana_discover: "http://localhost:5601/goto/f73b295ff92718b26bc94edac766d8e3"

# use_kibana_discover is set in kibana_discover_url
alert_text: '{0}'
alert_text_args: [ kibana_discover_url ]
alert_text_type: alert_text_only

```

output2

```
http://localhost:5601/goto/f73b295ff92718b26bc94edac766d8e3
```

**Comment by wajika** [comment]
Are "use_kibana_discover" and "generate_kibana_discover_url" not the same?

```
generate_kibana_discover_url: True
kibana_discover_app_url: "http://192.168.10.148:5601/s/apm/app/discover#"
kibana_discover_version: "7.12"
kibana_discover_index_pattern_id: "b96eca80-ad0c-11ea-b618-530f4c7c7106"
kibana_discover_columns: ["trace.id","service.name","http.request.method","url.path","http.request.body.original","http.response.status_code"]
```

output

```
http://192.168.10.148:5601/s/apm/app/discover#/view/816a0d70-0eea-11ec-9353-5d4977dfe7ef?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(trace.id,service.name,http.request.method,url.path,http.request.body.original,http.response.status_code),filters:!(('$state':(store:appState),meta:(alias:'only%20show%20transaction',disabled:!f,index:b96eca80-ad0c-11ea-b618-530f4c7c7106,key:_index,negate:!f,params:(query:'apm-*-transaction-*'),type:phrase),query:(match_phrase:(_index:'apm-*-transaction-*'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b96eca80-ad0c-11ea-b618-530f4c7c7106,key:agent.name,negate:!f,params:(query:dotnet),type:phrase),query:(match_phrase:(agent.name:dotnet)))),index:b96eca80-ad0c-11ea-b618-530f4c7c7106,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
```

**Reply by nsano-rururu** [reply]
@wajika 

This is a function that does not currently exist. There are no plans to implement it.

**Comment by wajika** [comment]
```
http://192.168.10.148:5601/s/apm/login?next=/s/apm/app/discover#?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-06T08:39:38.661Z',to:'2021-09-06T09:09:38.661Z'))&_a=(columns:!(trace.id,service.name,http.request.method,url.path,http.request.body.original,http.response.status_code),filters:!(('$state':(store:appState),bool:(must:!((term:(http.response.status_code:'599')),(term:(service.name:Lonsid_MESPro_Web_Host)))),meta:(alias:filter,disabled:!f,index:b96eca80-ad0c-11ea-b618-530f4c7c7106,key:bool,negate:!f,type:custom,value:'{"must":[{"term":{"http.response.status_code":"599"}},{"term":{"service.name":"Lonsid_MESPro_Web_Host"}}]}'))),index:b96eca80-ad0c-11ea-b618-530f4c7c7106,interval:auto)
```

```

time:(from:'2021-09-06T08:39:38.661Z',to:'2021-09-06T09:09:38.661Z')
type:custom,value:'{"must":[{"term":{"http.response.status_code":"599"}},{"term":{"service.name":"Lonsid_MESPro_Web_Host"}}]}'
```

If you use a fixed short url, the time and filter conditions cannot be changed with the alert service, and finally can only be generated in real time through the code.

**Reply by nsano-rururu** [reply]
I know. So what?

**Reply by nsano-rururu** [reply]
It's no use telling me anything because I can't handle it.

**Reply by nsano-rururu** [reply]
@wajika 

jertal answers, but you have only two choices: fix it, pull request it, or implement the extension. Please do your best.

**Reply by JeffAshton** [reply]
I can probably schedule some time to implement this in October.

**Comment by JeffAshton** [comment]
PR is up:

https://github.com/jertel/elastalert2/pull/512

**Comment by JeffAshton** [comment]
PR #512 got merged.

Here's the config I'm using for an AWS OpenSearch instance:

```yml
generate_kibana_discover_url: True
shorten_kibana_discover_url: True
kibana_url: https://opensearch.example.org/
kibana_discover_app_url: app/discover?created_by=elastalert#/
kibana_discover_security_tenant: global
kibana_discover_version: '7.10'
```

I included `created_by=elastalert` as query string parameter in the `kibana_discover_app_url` to enable me to do a targetted garbage collection from the `.kibana*` indices.

```
POST /.kibana*/_search
```
```json
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "type": "url"
          }
        },
        {
          "range": {
            "url.createDate": {
              "lte": 1630454400000
            }
          }
        },
        {
          "match_phrase": {
            "url.url": "created_by=elastalert"
          }
        }
      ]
    }
  }
}
```
