### DISCUSSION TITLE
Skipped: maximum number of running instances reached (1)

### DISCUSSION THREAD

**Discussion by Harris-Chan** [jertel/elastalert2#456] [Q&A] [answered]
hi there,

I try to do a port scan alert with ` type: cardinality`. However, I find that it might happen a case that the rules will be skipped. 

Here is my yaml file of rule set. And I have around 12 rules run parallels with simple query.
```
type: cardinality

timeframe:
  minutes: 1

query_key : [source, dst]
cardinality_field: "dst_Port"
max_cardinality: 5

filter:
- query:
    query_string:
      query: "eventName:Session Allowed"
```

Below is the warning message received. Any possible method to solve this problem. Or are there any method to handle large amount of data. I have tried to adjust `misfire_grace_time `and `max_threads` but seems the problem is still not solved.
`WARNING:apscheduler.scheduler:Execution of job "Rule: (rule_name) (trigger: interval[0:05:00], next run at: 2021-09-08 08:02:24 UTC)" skipped: maximum number of running instances reached (1)
`

Besides, I am not so sure does the scrolling will affect it. Or the scrolling takes too long time so the rules are overtime.
Does scrolling will miss out any alerts too?
`INFO:elastalert:Queried rule (rule_name) from 2021-09-08 07:57 UTC to 2021-09-08 08:02 UTC: 40000 / 10000 hits (scrolling..)`

Any ideas what might is causing that?

Thanks
Harris
