### DISCUSSION TITLE
query_string filter does not work

### DISCUSSION THREAD

**Discussion by ben-sec** [jertel/elastalert2#459] [Q&A] [answered]
Hello!

Why is this simple query_string filter not working:
```
filter:
-query:
    query_string:
        query: "event.module: sysmon AND NOT process.command_line: dwm.exe"
```
I get

Error initializing rule New User found: Error searching for existing terms: RequestError(400, 'x_content_parse_exception', {'error': {'root_cause': [{'type': 'parsing_exception', 'reason': 'unknown query [que1:231] [bool] failed to parse field [must]', 'caused_by': {'type': 'parsing_exception', 'reason': 'unknown query [query]', 'line': 1, 'col': 231, 'caused_by': {'type': 'named_object_not_found_exception', 'reason': '[1:231] unknown field

What's wrong here? Thanks in advance!

Cheers, Ben

**Comment by jertel** [comment, marked as answer]
It's important that your questions, with accompanying code blocks such as rule configuration details and logs, be formatted properly so we can help you. Use triple backticks surrounding the code blocks to ensure indentation is properly maintained. 

Please review the project guidelines for more information about requesting support: https://github.com/jertel/elastalert2/discussions/11

**Reply by ben-sec** [reply]
Thanks for the note, I have updated my code snippet.

**Reply by jertel** [reply]
You need a space in between the first hyphen and `query`. Ex:

```
filter:
- query:
    query_string:
        query: "some query"
```
