### DISCUSSION TITLE
TheHive Configuration

### DISCUSSION THREAD

**Discussion by Harris-Chan** [jertel/elastalert2#465] [Q&A] [answered]
HI 

I am creating thehive alert in elastalert. And I want to change the type config in hive_alert_config from 'external' to some match field like index or rule name. However, I found that it can only return the string "index" in the type. How can I do it on `type `while Yelp/elastalert can use match[index].

I tried {_index} or _index on that `type `field but its only return me the string

```
hive_alert_config:
  customFields:
    - name: example
      type: string
      value: example
  follow: True
  severity: 2
  status: 'New'
  source: 'elastalert'
  description: 'Sample description'
  tags: ['tag1', 'tag2']
  title: 'Title'
  tlp: 3
  type: 'external'   <------------ Change it to match field

hive_observable_data_mapping:
  - domain: agent.hostname
  - domain: response.domain
  - ip: client.ip
```

**Comment by francisbebe** [comment]
I got same issue trying to get following
'{rule[name]}'
{match[somefield]}
or {match[_index]}?id={match[_id]}

anyone know how to solve this?? 
PS : i'm using elastalert docker version jertel/elastalert2:2.2.2

**Comment by jertel** [comment, marked as answer]
The `TheHive` alerter only supports dynamic match field substitution into the following fields:
- artifacts
- tags
- customFields
- title

You can submit a PR, following the [contribution guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md) if you would like to enhance this alerter to make more fields be dynamic.

**Comment by gatrene** [comment]
We are targeting to move from elastalert to elastalert2.
We setup a test config (commit 478eb6e9be25b330e4db7e7f56e45ab97f637294 - Wed May 11 21:05:09 2022), I've updated my previous hivealerter accordingly.
Here is my resulting config (I let initial elastalert config line in comment):

```
hive_alert_config:
    #title: "[{match[host][name]}] Whoami Execution from user {match[winlog][user][identifier]}}"
    title: 'Whoami Execution from winlog.user.identifier on server host.name'
    severity: 2
    #tags: ['host {match[host][name]}', 'user.id {match[winlog][user][identifier]}', 'rule win-pcr-0458']
    tags: [host.name, winlog.user.identifier,rule win-pcr-0458]
    type: 'external'
    source: 'elastalert'
    description: "
    Detects the execution of whoami, which is often used by attackers after exloitation / privilege escalation but rarely used by administrators \n 

    Hunting request:\n
    `event.code:1 AND process.name:whoami.exe` \n

    Here are the details:\n 
      - index: {match[_index]}\n 
      - index: {match[_index]}\n 
      #- host.name: {match[host][name]}\n 
      - host.name\n 
      #- user.id: {match[winlog][user][identifier}\n 
      - winlog.user.identifier 
    "

hive_observable_data_mapping:
#  - hostname: {match[host][name]}
  - hostname: host.name
```

In my case, dynamic match field substitution works 'hive_observable_data_mapping' and 'tags' fields, but not in 'title' nor 'description' fields (nb : I guess that 'customFields' you've mentionned refer to 'description').

Please let me know what do you think about these observations?

**Reply by nsano-rururu** [reply]
@gatrene 
I feel that the description is related to the one in the pull request. Please take a look.
https://github.com/jertel/elastalert2/pull/855

**Reply by gatrene** [reply]
You're right, I hadn't see this pull request, thanks for the info.
But for the 'title' field, I'm unable to make it work.

**Reply by nsano-rururu** [reply]
@gatrene 
It seems that you can write it as follows, but do you want to specify it separately from the value of alert_subject?
```yaml
alert_subject: "Whoami Execution from {0} on server {1}"
alert_subject_args:
  - winlog.user.identifier
  - host.name
```
