### DISCUSSION TITLE
Unable to get generate_kibana_discover_url to work

### DISCUSSION THREAD

**Discussion by Psyhil89** [jertel/elastalert2#514] [Q&A] [answered]
Hi All,

I am able to get email alerts as required however unable to generate URL for kibana dashboard in alerts.
Below is an example of a test rule and its output. May I please ask some one to guide me on what I did wrong here? 
Thank you in advance!

```
# description: Detects suspicious PowerShell download command(Invoke-webrequest)
alert:
- "email"
# (required, email specific)
# a list of email addresses to send alerts to
email:
- "redacted"
filter:
- query:
    query_string:
      query: ((event.code:"4104" AND (winlog.event_data.ScriptBlockText:IWR* OR winlog.event_data.ScriptBlockText:Invoke-WebRequest*)) OR (event.code:"4103" AND winlog.event_data.Payload:*Invoke-WebRequest*) OR (event.code:"800" AND winlog.event_data.param1:Invoke-WebRequest*) OR (event.code:"4100" AND winlog.event_data.Payload:*InvokeWebRequestCommand*))
index: winlogbeat-*
name: suspicious-powershell-download by Invoke-webrequest test
priority: 3
realert:
  minutes: 0
type: any
generate_kibana_discover_url: true
kibana_discover_app_url: redacted:5601/app/discover#/
kibana_discover_version: '7.13'
include:
  - winlog.computer_name
  - winlog.user.name
  - winlog.user.domain
  - winlog.event_data.ScriptBlockText
```

Alert Output
```
suspicious-powershell-download by Invoke-webrequest

@timestamp: 2021-10-19T13:29:10.849Z
_id: T-W9mHwBHRjHKVhtZxXj
_index: winlogbeat-7.8.0-000001
_type: _doc
num_hits: 3
num_matches: 3
winlog: {
    "computer_name": "redacted",
    "event_data": {
        "ScriptBlockText": "Invoke-WebRequest -Uri 'http://www.google.com'"
    },
    "user": {
        "domain": "redacted",
        "name": "redacted"
    }
}

```
