### DISCUSSION TITLE
Send alert only for first match or how to avoid the realert

### DISCUSSION THREAD

**Discussion by masterplanx** [jertel/elastalert2#520] [Q&A] [answered]
Hi Team! how are you?
I have 2 rules that monitor the CPU consumption of my kubernetes nodes. A rule that checks if the CPU is above 80% and another rule that checks if the processor is below 40%. 
This is working fine I have two alerts set one by slack and the other using http_post, which what it basically does is execute an API that depending on if the value is 80 it scales up and if it is less than 40 it does a downscale, all this is fine.
The problem we are having is that most of the time the nodes are below the **min_threshold**, therefore the condition is always running. I know elastalert2 doesn't support resolve events, so is there a way to prevent alerts from being re-run? I saw that you can set **realert** to a high value to avoid it https://elastalert2.readthedocs.io/en/latest/recipes/faq.html?highlight=days#how-can-i-prevent-duplicate-alerts
but maybe there is some way to filter with a query but I couldn't find it.
These are my rules:

```
rules:
  cpu_usage_up_period_60_output: |-
    ---
    name: CLUSTER CPU USAGE UP PERIOD_60
    type: metric_aggregation
    index: metricbeat-*
    metric_agg_key: system.cpu.total.norm.pct
    metric_agg_type: avg
    query_key: bucketID
    min_doc_count: 1
    doc_type: _doc
    buffer_time:
      hours: 1
    bucket_interval:
      minutes: 60
    sync_bucket_interval: true
    max_threshold: 0.8
    filter:
    - term:
        metricset.name: cpu
    alert:
    - "slack"
    - "post"
    slack:
    slack_webhook_url: "https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxxxxx"
    post:
    http_post_url: "http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    http_post_static_payload:
      infra_component: "kubernetes"
      operation: "up"
    http_post_payload:
      bucket_id: bucketID
    realert:
      minutes: 1
  cpu_usage_down_period_60_output: |-
    ---
    name: CLUSTER CPU USAGE DOWN PERIOD_60
    type: metric_aggregation
    index: metricbeat-*
    metric_agg_key: system.cpu.total.norm.pct
    metric_agg_type: avg
    query_key: bucketID
    min_doc_count: 1
    doc_type: _doc
    buffer_time:
      hours: 1
    bucket_interval:
      minutes: 60
    sync_bucket_interval: true
    min_threshold: 0.4
    filter:
    - term:
        metricset.name: cpu
    alert:
    - "slack"
    - "post"
    slack:
    slack_webhook_url: "https://hooks.slack.com/services/XxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    post:
    http_post_url: "http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    http_post_static_payload:
      infra_component: "kubernetes"
      operation: "down"
    http_post_payload:
      bucket_id: bucketID
    realert:
      days: 1
```

Regards!
