### DISCUSSION TITLE
Run rule once a day with time window from that day

### DISCUSSION THREAD

**Discussion by aizerin** [jertel/elastalert2#536] [Q&A] [answered]
I'm trying to set up a rule which will run only once a day. But I'm struggling with time window settings. I have following alert:

```yaml
---
name: Errors alerts
type: frequency
num_events: 1
timeframe:
  hours: 24
use_count_query: true
doc_type: "_doc"
limit_execution: "0-5 0 * * *"
index: some-error*
filter: []
alert:
  - "debug"
```

Which suppose to generate a report of num_hits in a single day. But there is a problem with `timeframe` settings. Currently, it will only take events at the time of execution, not for the whole day.  And I'm not able to find what exactly `timeframe` means. 

Is it possible to make it somehow with different settings?
