### DISCUSSION TITLE
Error posting to ms teams: 400 Client Error - Bad Request

### DISCUSSION THREAD

**Discussion by fabioformosa** [jertel/elastalert2#559] [Q&A] [answered]
Hi all,
we got `400 bad request` when we use the `ms_teams` alerter in conjunction with the prop aggregator.
The error in the logs is:
```
ERROR:elastalert:Error while running alert ms_teams: Error posting to ms teams: 400 Client Error: Bad Request 
for url: https://ms-team-webhook-url
```
The elastalert2 config is:
```
...
runIntervalMins: 1
bufferTimeMins: 60
alertRetryLimitMins: 2880
realertIntervalMins: 0
...
aggregation:
      minutes: 2
summary_table_fields:
  - "kubernetes.labels.app"
  - "log"
filter:
  - match:
      log: "error"
alert:
  - ms_teams
ms_teams_webhook_url: "https://ms-team-webhook-url"
ms_teams_alert_summary: "bla bla bla"
ms_teams_alert_fixed_width: False
```

Has anyone faced the same error?

**Comment by jertel** [comment]
Does it work without the aggregation? Have you enabled debug to see if there's additional information, such as the full error response from Teams being logged? That information may help identify the problem.

**Comment by fabioformosa** [comment]
The same issue is even I use realerting. No issues without the aggregation or realerting.

I added the alert "debug" below the alert "ms_teams",
```
...
alert:
  - ms_teams
  - debug
...
```
but I get no further details on the logs. (I'm using the elastalert2 helm chart and I monitor the kubernetes logs of the elastalert2 pod". Tell me if I'm looking for debug logs in a wrong place. The documentation talks about python object and getLogger. I don't know how to use them in a kubernetes way).

**Comment by jertel** [comment, marked as answer]
I looked at the teams.py file and it appears there is no logging of the request or response. My guess is there is a limit on the size of the MS Teams message and when you use aggregations it's causing the size to exceed the limit. Again, just a guess. I don't use MS Teams so I can't reproduce this.

Try adding this to your rule:

```
alert_text_type: aggregation_summary_only
```

**Comment by nsano-rururu** [comment]
I tried to move the alert notification to ms teams. My alert rule notified ms teams of the alert without any problem.


```yaml
alert:
  - "ms_teams"
alert_subject: "Test {} 123 aa☃"
alert_subject_args:
  - "message"
  - "@log_name"
alert_text: "Test {}  123 bb☃"
alert_text_args:
  - "message"
filter:
  - query:
      query_string:
        query: "message:Quit AND @log_name:mysqld.general"
generate_kibana_discover_url: false
index: "mariadblog-*"
is_enabled: true
match_enhancements: []
ms_teams_alert_summary: "ElastAlert Message"
ms_teams_theme_color: "#167CB0"
ms_teams_webhook_url: "https://xxxx.webhook.office.com/webhookb2/xxxx"
name: "a"
num_events: 2
realert:
  minutes: 5
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "frequency"
use_strftime_index: false
```
![キャプチャ](https://user-images.githubusercontent.com/22293449/140950616-e8d5a329-5d7c-4243-a8e5-0f0d1a12e76e.PNG)
