### DISCUSSION TITLE
customFields are not working

### DISCUSSION THREAD

**Discussion by mashaikx13** [jertel/elastalert2#563] [Q&A] [answered]
Hi @jertel 
Hope you are doing well, we are using TheHive 4.1.10-1 and writing rules for it, everything is working fine but we are having trouble with the customFields. We want to get agentname, srcip etc in customFields, below is the file we are using when we run elastalert service we get this error and we also tried the step in the documentation it would helpful if you can just give a real example of it.

`"ERROR:elastalert:Error while running alert hivealerter: Error posting to TheHive: 404 Client Error: Not Found for url: https://192.168.0.111"`

Here is the rule we are trying:

```
es_host: 192.168.0.110
es_port: 9200
name: Wazuh-Rule-ID
type: frequency
index: wazuh-alerts-4.x-*
num_events: 1
timeframe:
    hours: 1
filter:
- term:
    rule.level: "5"

# Alternative for the Title
alert_subject_args:
- rule.description
alert_subject: "{0}"

#Alternative for the description
alert_text_args: [ "rule.description", "agent.name", "@timestamp", "full_log" ]
alert_text_type: alert_text_only
alert_text:  |
     '{0} . {2}'

realert:
  minutes: 0
alert: hivealerter
hive_connection:
  hive_host: https://192.168.0.111
  hive_port: 443
  hive_apikey: zBOlBlfBY/6neow6L0HVxBPK2VcP0Tc2

hive_alert_config:
  customFields:
    - name: Agent Name
      type: string
      value: agent.name

  type: 'Security Logs'
  source: 'elastalert'
  severity: 2
  tags: ["agent.name", "agent.id", "rule.description"]
  tlp: 3
  status: 'New'
  follow: True

hive_observable_data_mapping:
    - ip: agent.ip
```
