### DISCUSSION TITLE
Confused by `num_hits`

### DISCUSSION THREAD

**Discussion by SHxKM** [jertel/elastalert2#579] [Q&A] [answered]
**Note:** Admittedly I'm still on the "Yelp" version of this, but since that repo seems stale/dead, I thought I'd ask here whether what I'm experiencing is a bug, and if not - what is the possible explanation for it.

I've been trying to understand the meaning of `num_hits` as it relates (if at all) to `num_matches`. I understand now that when I get an alert, the `num_hits` is pretty meaningless as it only says what were the number of hits for the _latest_ query.

But what I don't understand is how, for a given timeframe, say `2021-11-29 22:06 UTC` and `2021-11-29 22:16 UTC`, reported `num_hits` is `121`, while directly viewing the data in Kibana shows `89` hits. As I understand, `hits` refers to documents retrieved in a single query, so how can this be possible? from what I gather, `num_hits` should be _at most_ `89` in this case, but I wouldn't be surprised if I'm wrong.

For reference/context I'm attaching some properties of my rule:

```
type: frequency
timeframe:
  minutes: 10
num_events: 1
use_count_query: true
doc_type: logs
top_count_keys: ["some_attr"]
top_count_number: 100
filter:
  - query:
      query_string:
        query: "\"Some Target String:\""
```
