### DISCUSSION TITLE
Daily alerts don't trigger query

### DISCUSSION THREAD

**Discussion by an-tex** [jertel/elastalert2#590] [Q&A] [answered]
When defining a limit_execution to be triggered only once a day like this:
`limit_execution: "0 5 */1 * *"`, it actually never triggers. Changing it to e.g. hourly:
`limit_execution: "0 */1 * * *"`, it works.

In the log I only see

```
08:28:06.658Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Pausing XXX until next run at 2021-12-02 05:00 UTC
```

But on the next day at this time the same log appears and no query is made.

Here's my elastalert.yaml
```yaml
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch-es-http

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: False

ssl_show_warn: False

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: xxx
es_password: xxx

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

#skip_invalid: True
```

The alert is not silenced
