### DISCUSSION TITLE
How to use env variables in config.yaml using docker-compose file

### DISCUSSION THREAD

**Discussion by rschirin** [jertel/elastalert2#591] [Q&A] [answered]
Hey there,
is there anyone that can show to me how to specify and use environment variables in the config.yaml file?
I am using a docker-compose file and this is my section:

```
  elastalert2:
    container_name: elastalert2
    image: jertel/elastalert2:latest
    restart: always
    volumes:
      - type: bind
        source: ./elastalert2/config.yaml
        target: /opt/elastalert/config.yaml
      - type: bind
        source: ./elastalert2/rules
        target: /opt/elastalert/rules
    environment:
      ES_HOSTS: $ES_HOSTS
      ES_USERNAME: elastic
      ES_PASSWORD: $ELASTIC_PASSWORD
```

Should I specify anything into the config.yaml file? Anyway I am getting an error related to Elasticsearch host during the first connection phase.
thanks
