### DISCUSSION TITLE
Elastalert in HTML format

### DISCUSSION THREAD

**Discussion by Singh-Shivani** [jertel/elastalert2#609] [Q&A] [answered]
Hii,

> I want to show my **elastalert mail in HTML format** but I'm unable to get correct request code for it.

My requirement - 

> I want to give kibana discover page link in `alert_text` with dynamic value of `@timestamp` (time when alert got triggered)

My rule file - 
```
alert_text: |
    <html>
    <body>
        <script>
            function loadUrl() {
                var timestamp = {3};
                var url = "localhost:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'" + timestamp + "',to:now))&_a=("some_applied_filters'),sort:!(!('@timestamp',desc)))";


                document.getElementById('KibanaLink').href = url;
            }
        </script>
        <p style="text-align:left;">Hi Team,</p>
        <p>{2} Elastalert for more details</p>
        <table style="font-family:arial, sans-serif;border-collapse:collapse;">
            <tr>
                <th style="border:1px solid;text-align:left;">_id</th>
                <th style="border:1px solid;text-align:left;">Category</th>
                <th style="border:1px solid;text-align:left;">Upper_Threshold</th>
                <th style="border:1px solid;text-align:left;">timestamp(IST)</th>

            </tr>
            <tr>
                <td style="border:1px solid;text-align:left;"> {} &nbsp;</td>
                <td style="border:1px solid;text-align:left;"> {} &nbsp;</td>
                <td style="border:1px solid;text-align:left;"> {} &nbsp;</td>
                <td style="border:1px solid;text-align:left;"> {} &nbsp;</td>
            </tr>
        </table>


        <br/>Kibana Link-
        <button onclick="loadUrl()">
            <a id="KibanaLink" href="#">Link</a>
        </button>
        <br/>
        <p style="text-align:left;">Regards,</p>
        <p style="text-align:left;">Team</p><br />
    </body>

    </html>

alert_text_args: ["_id", "Category", "Upper_Threshold", "@timestamp"]
```
The part I'm most concerned about is getting `@timestamp` value in `loadURL()` function- 
- "localhost:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0)**,time:(from:'" + timestamp + "',to:now))**&_a=("applied_filters'),sort:!(!('@timestamp',desc)))";

**Thank you!**

**Comment by nsano-rururu** [comment, marked as answer]
https://github.com/Yelp/elastalert/issues/1473

**Reply by nsano-rururu** [reply]
kibana_discover_url 
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#generate-kibana-discover-url

**Reply by Singh-Shivani** [reply]
### How Can I add my @timestamp value(coming from index pattern) here - _**kibana_discover_from_timedelta:**_

generate_kibana_discover_url: True
kibana_discover_app_url: "http://localhost:5601/app/discover#/"
kibana_discover_index_pattern_id: "4babf380-c3b1-11eb-b616-1b59c2feec54"
kibana_discover_version: "7.15"
kibana_discover_from_timedelta:
  **_minutes: 10_** 
kibana_discover_to_timedelta:
  minutes: 10
alert_text: '{0}'
alert_text_args: [ kibana_discover_url ]
alert_text_type: alert_text_only

**Reply by phoenixx1** [reply]
I have similar issue, if you find any solution please tell that will be helpful 
@nsano-rururu 🙏🙏🙏🙏🙏

**Reply by jertel** [reply]
The timestamp value is pulled automatically, assuming the `timestamp_field` is set to your desired timestamp field (most likely it's defaulting to `@timestamp` which appears to be what you want to use anyway). Then, the from/to timedelta parameters are add to either end of the timestamp, which gives Kibana the timerange to search. If you want to narrow that window closer to the triggered event record's timestamp then reduce those `kibana_discover_to_timedelta` and `kibana_discover_from_timedelta` values in your rule config.

This is the logic that is being applied, which should help you understand what's going on internally:

https://github.com/jertel/elastalert2/blob/2bdd36a8c638667fa1f10130e72be178ec2b803f/elastalert/kibana_discover.py#L58

**Reply by Singh-Shivani** [reply]
Thanks, but I'm using .yaml file for my rule and config, how can I use this in my existing code(given above)?? @jertel

**Comment by jertel** [comment]
Everyone uses .yaml syntax for their rules and config. I don't understand how that comment is relevant to this topic.

Regardless, if you're choosing to use your own HTML message with embedded custom link, instead of the existing Kibana link feature, then you will need to provide more debug/logging information in order for us to try and assist. For example, is your browser/email reader throwing a javascript error due to the missing quotations on the line `var timestamp = {3}`? What specifically are you seeing?

**Reply by Singh-Shivani** [reply]
Thank you, I want to put my `@timestamp `field value in `kibana_discover_from_timedelta:`

My rules.yaml file -
```
alert_subject: "Test Alert: API Err {0}% [{2}/{3}] against threshold {1}%"

alert_subject_args:
- "1"
- "2"
- "3"
- "4"

generate_kibana_discover_url: True
kibana_discover_index_pattern_id: "XXX"
kibana_discover_version: "7.1"
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 10

alert_text: 'Category-{0}, Kibana URL - {1}, Timestamp - {2}'

alert_text_args:
- "Category"
- "kibana_discover_url"
- "@timestamp"

alert_text_type: alert_text_only

type: any
```

**Reply by jertel** [reply]
It already does this for you as I mentioned in my [previous post](https://github.com/jertel/elastalert2/discussions/609#discussioncomment-1798539). What are you seeing? Is the time in Kibana incorrect, causing your events to not show up?

**Reply by Singh-Shivani** [reply]
I'm seeing nothing in URL, In my emails I'm getting - 
`Category-XXX, Kibana URL - , Timestamp - 2021.12....`

**Reply by jertel** [reply]
In the most recent config you pasted it appears to be missing the `kibana_discover_app_url` parameter, which is required. You should review the elastalert log to find any errors or warnings that can give you specifics about why it's unable to generate the URL.

**Reply by Singh-Shivani** [reply]
sorry my bad I forgot to write` kibana_discover_app_url`. I have made correct changes and will review logs as well.

**Reply by Singh-Shivani** [reply]
### Is there anything wrong in this rule file? I'm not getting any mails.

```
match_enhancements:
- "time_enhancement.TimeEnhancement"


alert_subject: "Test 3 Alert: API Err {0}% [{2}/{3}] against threshold {1}%"

alert_subject_args:
- "ErrorPercentage"
- "Upper_Threshold"
- "TotalError"
- "TotalTraffic"

generate_kibana_discover_url: True
kibana_discover_app_url: "https://XXX.com/app/discover#/"
kibana_discover_index_pattern_id: "44992fa0-38c7-11ec-8493-b57c82cf4f00"
kibana_discover_version: "7.1"
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 10

alert_text: 'Category-{0}, Kibana URL - {1}'

alert_text_args:
- "Category"
- "kibana_discover_url"

alert_text_type: alert_text_only


type: any


realert:
  minutes: 5

index: my-index*


num_events: 1

attach_related: true

timeframe:
  hours: 1


filter:
- query:
  query_string:
   query: "Category: api"


timestamp_field: "timestamp"

alert:
- "email"
```

**Reply by nsano-rururu** [reply]
I think the following description should be corrected

current

```yaml
filter:
- query:
  query_string:
   query: "Category: api"
```

after

```yaml
filter:
- query:
    query_string:
      query: "Category: api"
```
