### DISCUSSION TITLE
Docker container keeps randomly stopping. Can anyone help?

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#614] [Q&A] [answered]
I am running this command to create and run a docker container in a CentOS VM:
`docker run -d -v /etc/elastalert/elastalert.yaml ghcr.io/jertel/elastalert2/elastalert2`

My container starts and I can see it running with the `docker ps` command. However after a few minutes the container is no longer present in the `docker ps` command. I have used the `docker start` command to start the container back up, but still after a few minutes it stops again. Also this is the log from the `docker logs` command:

`Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 224, in main
    host = args.host if args.host else input('Enter Elasticsearch host: ')
EOFError: EOF when reading a line
Enter Elasticsearch host: `

So obviously it seems there is an issue with the Elasticsearch host. However my config file is specifying my Elasticsearch host, so I am a bit confused.

**Comment by jertel** [comment, marked as answer]
Your `-v` parameter is incorrect. Please see the documentation, specifically the [section](https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#as-a-docker-container) that covers how to run ElastAlert 2 in a Docker container.

**Reply by roman-tasi** [reply]
Thank you... 

So for my `-v` parameter, will this work: `-v /etc/elastalert/elastalert.yaml:/opt/elastalert/config.yaml` ?
Keep in mind that `/opt/elastalert/config.yaml` does not exist on my VM.

**Reply by jertel** [reply]
Yes, that will work. The `-v` param will project the elastalert.yml onto that path that you specify on the right side of the colon character.

**Reply by sevenval-admins** [reply]
@jertel I have the same Problem. 
If I run 
`docker run -d -v /tmp/elastalert.yaml:/opt/elastalert/config.yaml jertel/elastalert2`
then I get the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 219, in main
    host = args.host if args.host else input('Enter Elasticsearch host: ')
EOFError: EOF when reading a line
```
When I run it as k8s deployment, I get the same error:
Here is my deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  labels:
   app: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      restartPolicy: Always
      containers:
      - command:
        - /opt/elastalert/run.sh
        - --verbose
        name: ops-elastalert
        image: jertel/elastalert2:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /opt/config/
            name: elastalert-config
      volumes:
      - configMap:
          defaultMode: 256
          name: elastalert-config
          optional: false
        name: elastalert-config
```
and here is my config.yaml (the same that I used in order to try to start the container):
```
apiVersion: v1
data:
  config.yaml: |-
    rules_folder: /opt/rules/

    buffer_time:
      minutes: 5

    run_every:
      minutes: 5

    es_host: my-es-host
    es_port: 9200
    es_conn_timeout: 60

    scan_subdirectories: false

    writeback_index: elastalert_ops-elastalert

    disable_rules_on_error: false
kind: ConfigMap
metadata:
  name: elastalert-config
```
Any help and suggestion will be very appreciate.
