### DISCUSSION TITLE
Getting CERTIFICATE_VERIFY_FAILED Even if verify_certs: False is Set

### DISCUSSION THREAD

**Discussion by cagri387** [jertel/elastalert2#624] [Q&A] [answered]
I am using latest docker image and trying to send alerts to ms_teams, but I get error below:

`ERROR:elastalert:Error while running alert ms_teams: Error posting to ms teams: HTTPSConnectionPool(host='ABC.webhook.office.com', port=443): Max retries exceeded with url: /webhookb2/312312321321312 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))`

I have already set **verify_certs** parameter to false but, it didn't make any difference.

config.yaml:

```
es_host: xxxx
es_port: 9200
es_username: abc
es_password: xxxx

rules_folder: rules

run_every:
  minutes: 3

buffer_time:
  minutes: 3

use_local_time: false

writeback_index: elastalert_status

verify_certs: False

alert_time_limit:
  hours: 1

disable_rules_on_error: false
```

rule:

```
name: my_rule
type: any
index: xxx*

filter:
  - query:
      query_string:
        query: "message: \"XXXX\""


verify_certs: False

alert:
  - "ms_teams"

ms_teams_webhook_url: "https://xyz"

ms_teams_alert_summary: "ABC"
alert_text: "{0}"
alert_text_args:
  - message
  
alert_text_type: alert_text_only

realert:
  minutes: 2
```

I also tried to send notification via curl in container, but if I don't set -k option in curl command, again I get the certification error above. 
How can I solve this problem? 
Is there something missing in the docker image, or did I miss something? 

Thanks in advance.
