### DISCUSSION TITLE
Rison Decoder Error--Help

### DISCUSSION THREAD

**Discussion by Psyhil89** [jertel/elastalert2#626] [Q&A] [answered]
Greetings

Been running into an issue where kibana url in alert email from Elastalert is inaccessible with error
`Error restoring state from URL`
`Rison decoder error: unmatched  "'"`

I removed everything from the specific rule to have minimum thing to generate the alert thinking some unsupported character was added but still same.

Any guidance on what is causing the issue?
Elastalert version we have is 2.2.2 and Elasticsearch is 7.16.1 version if it helps.

**Comment by nsano-rururu** [comment, marked as answer]
I'm ignoring the project guidelines. You should look at the project guidelines and add the necessary information.
https://github.com/jertel/elastalert2/discussions/11

**Reply by Psyhil89** [reply]
Thanks @nsano-rururu & my apologies for not sharing the details earlier as was not sure what will be required to identify the cause.
So far only 2 alerts of many are having this issue & hence I thought its some character in the alert rule causing the issue.

Below is an alert rule removed everything and kept bare minimum to generate kibana url.

```
description: Failed Login detection
alert:
- "email"
# (required, email specific)
# a list of email addresses to send alerts to
email:
- "redacted"
email_format: html
timeframe:
  hours: 1
type: frequency
filter:
- query:
    query_string:
      query:(winlog.channel:Security AND (winlog.event_id:529 OR winlog.event_id:4625) AND NOT (winlog.event_data.TargetUserName:SYSTEM OR winlog.event_data.TargetUserName:*$ OR winlog.event_data.TargetUserName:LOCAL\ SERVICE) AND NOT (winlog.event_data.Status:0xc000006e OR winlog.event_data.Status:0xc000005e OR winlog.event_data.Status:0xc00002a6))
index: winlogbeat-*
num_events: 5
query_key: winlog.event_data.TargetUserName
name: Failed Logins Observed Test
priority: 3
realert:
  minutes: 0

#Kibana_generation
generate_kibana_link: true
kibana_url: http://redacted:5601
generate_kibana_discover_url: True
shorten_kibana_discover_url: True
kibana_discover_app_url: http://redacted:5601/app/discover#/
kibana_discover_version: "7.15"
kibana_discover_index_pattern_id: "winlogbeat-*"

alert_text: "<b>Kibana Dashboard:</b> {0}<br><br>"

alert_text_type: alert_text_only

alert_text_args:
  - kibana_discover_url
```

Please let me know in case any more details are required, honestly I tried looking for the cause and could not find it or probably overlooked hence reached out here.

**Reply by nsano-rururu** [reply]
`kibana_url` is not used in the kibana_discover setting. With the correct settings, the generated URL is stored in `kibana_discover_url` and can be used in the rule as follows:

example 

```yaml
generate_kibana_discover_url: True
kibana_discover_app_url: "http://localhost:5601/app/discover#/"
kibana_discover_index_pattern_id: "4babf380-c3b1-11eb-b616-1b59c2feec54"
kibana_discover_version: "7.15"
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 10
alert_text: '{0}'
alert_text_args: [ kibana_discover_url ]
alert_text_type: alert_text_only
```

**Reply by nsano-rururu** [reply]
I don't think there is a "shorten_kibana_discover_url: True" setting.

**Reply by nsano-rururu** [reply]
Regarding the value of kibana_discover_index_pattern_id, do you recognize that the name `winlogbeat- *` is specified in the extension when creating the index pattern?

**Reply by nsano-rururu** [reply]
I think you should run it with `es_debug_trace` to see what queries are being issued to elasticsearch.
https://elastalert2.readthedocs.io/en/latest/recipes/faq.html?highlight=es_debug_trace%20#my-rule-is-not-getting-any-hits

**Reply by nsano-rururu** [reply]
@Psyhil89 

look
https://github.com/elastic/kibana/issues/75957

**Reply by Psyhil89** [reply]
Thank you @nsano-rururu, for super fast response and wish you Merry Christmas!
shorten_kibana_discover_url:  settings was mentioned in the docs& schema hence I was attempting to use it but never worked for me :)
The `winlogbeat-*` is specified correctly & is the index we are using to save events from winlogbeat.
Got some more details as had been troubleshooting the issue yesterday thinking there is definitely a character being added in alert rule but that's not the case.

The issue appears to be way kiabana dashboard URL being generated in certain scenario where clickable link is half of the display text of URL.
This is causing two issues:-
1. Mostly Risen Decoder error for unmatched "'"
2. ElasticSearch giving error for malformed URL.

In both the  cases, if I copy paste the complete URL text it works fine but clicking it gives error for either of above two hence the root cause is same for both.

example the clickable URL part is below and gives error for Risen Decoder error
`http://redacted:5601/app/discover#/?_g=%28filters%3A%21%28%29%2CrefreshInterval%3A%28pause%3A%21t%2Cvalue%3A0%29%2Ctime%3A%28from%3A%272021-12-24T10%3A15%3A29.044Z%27%2Cto%3A%272021-12-24T10%3A35%3A29.044Z%27%29%29&_a=%28columns%3A%21%28_source%29%2Cfilters%3A%21%28%28%27%24state%27%3A%28store%3AappState%29%2Cbool%3A%28must%3A%21%28%28query_string%3A%28query%3A%27%28%28event.code%3A%224104%22%20AND%20%28winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BWw%5D%5BRr%5D.%2A/%20OR%20winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%29%20OR%20%28event.code%3A%224103%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%20OR%20%28event.code%3A%22800%22%20AND%20winlog.event_data.param1%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%20OR%20%28event.code%3A%224100%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D%5BCc%5D%5BOo%5D%5BMm%5D%5BMm%5D%5BAa%5D%5BNn%5D%5BDd%5D.%2A/%29%29%27%29%29%29%29%2Cmeta%3A%28alias%3Afilter%2Cdisabled%3A%21f%2Cindex%3A%27winlogbeat-%2A%27%2Ckey%3Abool%2Cnegate%3A%21f%2Ctype%3Acustom%2Cvalue%3A%27%7B%22must%22%3A%5B%7B%22query_string%22%3A%7B%22query%22%3A%22%28%28event.code%3A%5C%224104%5C%22%20AND%20%28winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BWw%5D%5BRr%5D.%2A/%20OR%20winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%29%20OR%20%28event.code%3A%5C%224103%5C%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BB`

Where as complete display text is below and works if accessed by copy pasting in browser

`http://redacted:5601/app/discover#/?_g=%28filters%3A%21%28%29%2CrefreshInterval%3A%28pause%3A%21t%2Cvalue%3A0%29%2Ctime%3A%28from%3A%272021-12-24T10%3A15%3A29.044Z%27%2Cto%3A%272021-12-24T10%3A35%3A29.044Z%27%29%29&_a=%28columns%3A%21%28_source%29%2Cfilters%3A%21%28%28%27%24state%27%3A%28store%3AappState%29%2Cbool%3A%28must%3A%21%28%28query_string%3A%28query%3A%27%28%28event.code%3A%224104%22%20AND%20%28winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BWw%5D%5BRr%5D.%2A/%20OR%20winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%29%20OR%20%28event.code%3A%224103%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%20OR%20%28event.code%3A%22800%22%20AND%20winlog.event_data.param1%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%20OR%20%28event.code%3A%224100%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D%5BCc%5D%5BOo%5D%5BMm%5D%5BMm%5D%5BAa%5D%5BNn%5D%5BDd%5D.%2A/%29%29%27%29%29%29%29%2Cmeta%3A%28alias%3Afilter%2Cdisabled%3A%21f%2Cindex%3A%27winlogbeat-%2A%27%2Ckey%3Abool%2Cnegate%3A%21f%2Ctype%3Acustom%2Cvalue%3A%27%7B%22must%22%3A%5B%7B%22query_string%22%3A%7B%22query%22%3A%22%28%28event.code%3A%5C%224104%5C%22%20AND%20%28winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BWw%5D%5BRr%5D.%2A/%20OR%20winlog.event_data.ScriptBlockText%3A/%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%29%20OR%20%28event.code%3A%5C%224103%5C%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%20OR%20%28event.code%3A%5C%22800%5C%22%20AND%20winlog.event_data.param1%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5B-%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D.%2A/%29%20OR%20%28event.code%3A%5C%224100%5C%22%20AND%20winlog.event_data.Payload%3A/.%2A%5BIi%5D%5BNn%5D%5BVv%5D%5BOo%5D%5BKk%5D%5BEe%5D%5BWw%5D%5BEe%5D%5BBb%5D%5BRr%5D%5BEe%5D%5BQq%5D%5BUu%5D%5BEe%5D%5BSs%5D%5BTt%5D%5BCc%5D%5BOo%5D%5BMm%5D%5BMm%5D%5BAa%5D%5BNn%5D%5BDd%5D.%2A/%29%29%22%7D%7D%5D%7D%27%29%29%2C%28%27%24state%27%3A%28store%3AappState%29%2Cmeta%3A%28alias%3A%21n%2Cdisabled%3A%21f%2Cindex%3A%27winlogbeat-%2A%27%2Ckey%3Awinlog.computer_name%2Cnegate%3A%21f%2Cparams%3A%28query%3AUKDC3BTSEC01.bkuk.local%2Ctype%3Aphrase%29%2Ctype%3Aphrase%2Cvalue%3AUKDC3BTSEC01.bkuk.local%29%2Cquery%3A%28match%3A%28winlog.computer_name%3A%28query%3AUKDC3BTSEC01.bkuk.local%2Ctype%3Aphrase%29%29%29%29%29%2Cindex%3A%27winlogbeat-%2A%27%2Cinterval%3Aauto%29
`

**Reply by nsano-rururu** [reply]
shorten_kibana_discover_url is the one added in the following pull request. I overlooked it. I have never used it.
https://github.com/jertel/elastalert2/pull/512

**Reply by nsano-rururu** [reply]
Would you like to isolate the problem? ..

- Is it the same problem if shorten-kibana-discover-url is invalid?

- Did you read the documentation for shorten-kibana-discover-url? .. It is written that the specification of kibana_discover_app_url changes.
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#shorten-kibana-discover-url
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#kibana-discover-app-url

- Did you check the description in the following documents?
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#kibana-username
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#kibana-password
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#kibana-url
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#kibana-discover-security-tenant

**Reply by Psyhil89** [reply]
Absolutely & thank you for pointing out!
I had removed the `shorten-kibana-discover-url` from the alert to test if this fixes it, so far not & the output of the issue was shared in previous comment where clickable URL is truncated but display text of URL is complete.

As of now I am using the minimum things to get the `kibana_discover_url` with complete URL and not a truncated one but no success.
This is the alert rule Kibana URL generation options I am using.
```
generate_kibana_discover_url: True
kibana_discover_app_url: "http://redacted:5601/app/discover#/"
kibana_discover_version: "7.16"
kibana_discover_index_pattern_id: "winlogbeat-*"
```
In regards to `kibana_username` & `kibana_password` the option and its value are currently defined in the elastlalert config file & hence should be able to authenticate the API

Reviewing the documentation again and testing the alert & config with more changes. will update.

Wish you happy holidays and a very happy & prosperous New Year in advance!

**Reply by nsano-rururu** [reply]
@JeffAshton 

There is a problem that shorten-kibana-discover-url does not work well. Can you give me some advice on what the settings are missing?

**Reply by JeffAshton** [reply]
We are using it in production with OpenSearch 1.0 without any issues.  We did notice we needed to enable session side links to handle large queries (greater than 8kb).

**Reply by JeffAshton** [reply]
What I would recommend doing is building the same equivalent url with Kibana itself and so a diff with a generated link.  Not sure if something has changed with later versions of Elasticsearch.  The Elastic fork is dead to me.  😜

The shorten url stuff also uses the same code to generate the long link, so if none shortened urls are broken, shortening will only fix things if your url is being truncated say by something like the Slack app.

**Reply by nsano-rururu** [reply]
@JeffAshton 

Thank you for your answer.
I checked the specifications of the short URL API.
It seems that the return of the short URL API has changed since kibana 7.16.

**kibana 7.10～7.15**
https://www.elastic.co/guide/en/kibana/7.10/url-shortening-api.html
https://www.elastic.co/guide/en/kibana/7.11/url-shortening-api.html
https://www.elastic.co/guide/en/kibana/7.12/url-shortening-api.html
https://www.elastic.co/guide/en/kibana/7.13/url-shortening-api.html
https://www.elastic.co/guide/en/kibana/7.14/url-shortening-api.html
https://www.elastic.co/guide/en/kibana/7.15/url-shortening-api.html

API return
```json
{
  "urlId": "f73b295ff92718b26bc94edac766d8e3"
}
```


**kibana 7.16**
https://www.elastic.co/guide/en/kibana/current/short-urls-api-create.html

API return
```json
{
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
  "slug": "adjective-adjective-noun", 
  "locator": {
    "id": "LOCATOR_ID",
    "version": "x.x.x", 
    "state": {} 
  },
  "accessCount": 0,
  "accessDate": 1632680100000,
  "createDate": 1632680100000
}
```
---
@Psyhil89

I tried it in the following environment.
Please refer to the rules as well.
In kibana 7.16, the alert did not fly, so
Currently, shorten-kibana-discover-url is up to kibana 7.15
It will be a usable setting.

**example**

elasticsearch 7.10.2
kibana 7.10.2
elastalert2 2.2.3

```yaml
alert:
  - "slack"
alert_subject: "Test {} 123 aa☃"
alert_subject_args:
  - "message"
  - "@log_name"
alert_text: "Test {}  123 bb☃"
alert_text_args:
  - "message"
filter:
  - query:
      query_string:
        query: "@timestamp:*"
index: "mariadblog-*"
is_enabled: true
name: "a"
num_events: 2
realert:
  minutes: 5
generate_kibana_discover_url: true
shorten_kibana_discover_url: true
kibana_url: "http://kibana:5601/"
kibana_discover_app_url: "app/discover#/"
kibana_discover_index_pattern_id: "mariadblog"
kibana_discover_version: "7.10"
slack_attach_kibana_discover_url: true
slack_webhook_url: "https://hooks.slack.com/services/xxxxxx"
slack_channel_override: "#abc"
slack_emoji_override: ":kissing_cat:"
slack_msg_color: "warning"
slack_parse_override: "none"
slack_username_override: "elastalert"
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "frequency"
use_strftime_index: false
```
![WS000000](https://user-images.githubusercontent.com/22293449/147592722-b4668e32-c5dd-44dc-a549-ff6b9044bf88.JPG)

**Reply by JeffAshton** [reply]
That's too bad they changed the API so drastically.  It was so simple and powerful before.

**Reply by jertel** [reply]
Here's a PR that attempts to support both the old and new API. I've not tested it yet, as I don't have Kibana setup right now. Anyone have an OpenSearch or 7.15 Kibana and able to test it to ensure the older version still works?

https://github.com/jertel/elastalert2/pull/633

**Reply by nsano-rururu** [reply]
I will try it from now on.

**Reply by nsano-rururu** [reply]
I tried. There is an error.

```bash
INFO:elastalert:Queried rule a from 2021-12-29 04:57 UTC to 2021-12-29 04:59 UTC: 8 / 8 hits
ERROR:elastalert:Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/elastalert/kibana_external_url_formatter.py", line 90, in format
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://kibana:5601/api/short_url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 1538, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 1598, in send_alert
    matches[0]['kibana_discover_url'] =  kb_link_formatter.format(kb_link)
  File "/usr/local/lib/python3.10/site-packages/elastalert/kibana_external_url_formatter.py", line 92, in format
    raise EAException("Failed to invoke Kibana Shorten URL API: %s" % e)
elastalert.util.EAException: Failed to invoke Kibana Shorten URL API: 404 Client Error: Not Found for url: http://kibana:5601/api/short_url

ERROR:elastalert:Uncaught exception running rule a: Failed to invoke Kibana Shorten URL API: 404 Client Error: Not Found for url: http://kibana:5601/api/short_url
INFO:elastalert:Rule a disabled
```

**Reply by nsano-rururu** [reply]
I'm also worried that the changed api has separate pages for create and get.

Create short URL API
https://www.elastic.co/guide/en/kibana/7.16/short-urls-api-create.html
Get short URL API
https://www.elastic.co/guide/en/kibana/7.16/short-urls-api-get.html

**Reply by jertel** [reply]
The create API is all that's needed. It returns the ID for the URL. You can verify this in Kibana by clicking the Share link and enabling the short URL.

As far as the error you received, can you confirm you are using Kibana 7.16?

**Reply by nsano-rururu** [reply]
I'm using Kibana 7.16. something?
confirm.

**Reply by nsano-rururu** [reply]
```bash
[CORP\sano@a-ngft53r34ong es]$ docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED              STATUS                        PORTS                                                                                                    NAMES
9ee6396a769a   docker.elastic.co/kibana/kibana:7.16.0                 "/bin/tini -- /usr/l…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:5601->5601/tcp, :::5601->5601/tcp                                                                kibana
45f92470ac38   mariadb:10.4.11                                        "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp                                                                mariadb
784c802602da   fluentd:1.10.2                                         "tini -- /bin/entryp…"   About a minute ago   Up About a minute             5140/tcp, 0.0.0.0:24224->24224/tcp, 0.0.0.0:24224->24224/udp, :::24224->24224/tcp, :::24224->24224/udp   fluentd
74f535cf6f4e   docker.elastic.co/elasticsearch/elasticsearch:7.16.0   "/bin/tini -- /usr/l…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 0.0.0.0:9300->9300/tcp, :::9300->9300/tcp                     elasticsearch
```

**Reply by nsano-rururu** [reply]
elastalert2 also brings a pull request locally and runs it with a docker image.
```
[CORP\sano@a-ngft53r34ong es]$ docker ps | grep elastalert
ed9f6e3c06fb   elastalert2:2.2.4                                      "/opt/elastalert/run…"   2 minutes ago    Up 2 minutes                                                                                                                       elastalert
```

rule

```yaml
alert:
  - "slack"
alert_subject: "Test {} 123 aa☃"
alert_subject_args:
  - "message"
  - "@log_name"
alert_text: "Test {}  123 bb☃"
alert_text_args:
  - "message"
filter:
  - query:
      query_string:
        query: "message:Quit"
index: "mariadblog-*"
is_enabled: true
name: "a"
num_events: 2
realert:
  minutes: 5
generate_kibana_discover_url: true
shorten_kibana_discover_url: true
kibana_url: "http://kibana:5601/"
kibana_discover_app_url: "app/discover#/"
kibana_discover_index_pattern_id: "mariadblog"
kibana_discover_version: "7.16"
slack_attach_kibana_discover_url: true
slack_webhook_url: 'https://hooks.slack.com/services/xxxx'
slack_channel_override: "#abc"
slack_emoji_override: ":kissing_cat:"
slack_msg_color: "warning"
slack_parse_override: "none"
slack_timeout: 10
slack_username_override: "elastalert"
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "frequency"
use_strftime_index: false
```
