### DISCUSSION TITLE
Need help with my filter

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#637] [Q&A] [answered]
Currently my filter is hitting on just about every record in Elasticsearch because it is splitting my query into individual words. This is what I currently have:

```
filter:
- query:
    query_string:
      query: "A user account was locked out"
```

Can anyone help with what I should do to only receive matches that have the entire phrase: "A user account was locked out". I am considering using the '`term`' type but still am quite inexperienced. 

Thank you!
