### DISCUSSION TITLE
How to fix <MISSING VALUE>

### DISCUSSION THREAD

**Discussion by roman-tasi** [jertel/elastalert2#639] [Q&A] [answered]
I want to fill these values with the actual values in the log:

```
Lockout Event detected on <MISSING VALUE>.
Details of the event:
        - User: DCON2$
        - Source IP: <MISSING VALUE>
```
Also I want the User field to correspond to the actual user not the machine. Ideally I would actually want both User and Machine fields along with Source IP. This is the part of my config that generates this:

```
alert_subject_args:
  - host.hostname
alert_text: |-
  Lockout Event detected on {}.
  Details of the event:
          - User: {}
          - Source IP: {}
alert_text_args:
  - host.hostname
  - user.name
  - source.ip
```

Thank you !!

**Comment by nsano-rururu** [comment, marked as answer]
https://github.com/jertel/elastalert2/discussions/335

**Reply by nsano-rururu** [reply]
How do you write anything other than alert_subject_args and alert_text? .. Does the index to be searched always have host.hostname and source? I don't think anyone will answer without giving a little more information.

**Reply by nsano-rururu** [reply]
https://github.com/Yelp/elastalert/issues/768

**Reply by nsano-rururu** [reply]
Do you feel anything when you see the difference between the discussion below and the information you provide?
https://github.com/jertel/elastalert2/discussions/335

**Reply by roman-tasi** [reply]
These are the fields I want to extract:

`user.name[0], agent.hostname[0], source.ip[0], source.port[0]`

So I would format it like this?

```
alert_text: |-
  Lockout Event Detected:
  Details of the event:
          - User: {1}
          - Host: {2}
          - Source IP: {3}
          - Source Port: {4}
alert_text_args:
  - user.name[0]
  - agent.hostname[0]
  - source.ip[0]
  - source.port[0]
```

Here's a sample of the 'user' field in the JSON of the log:

```
"user": {
      "name": "roman",
      "domain": "UPKASI",
      "id": "S-1-0-0"
    },
```
The other fields (`agent`, `source`) follow a similar format.

**Reply by jertel** [reply]
Brackets are only needed when dealing with arrays. If your values aren't showing up as expected check the underlying ES field mappings and the values store within to make sure your logs are being indexed correctly. For example, if raw JSON is being dumped into the `user` field then it would explain why it cannot access a `user.name` subfield.

**Reply by roman-tasi** [reply]
This is what I am currently using:

```
alert_subject: "Lockout Event Detected from User {0}"
alert_subject_args:
  - winlog.event_data[0]TargetUserName
alert_text: |-
  Lockout Event detected.
  Details of the event:
          - User:
          - Host:
          - Source IP:
          - Source Port:
alert_text_args:
  - winlog.event_data[0]TargetUserName
  - winlog.computer_name
  - source.ip
  - source.port

```
The `args` are from Kibana -> Discover -> Expanded Document -> Table -> Field. Is there anything you see that can be wrong? It's still `<MISSING VALUE>` or blank.

@jertel

**Reply by roman-tasi** [reply]
@jertel Can you offer your input?

**Reply by nsano-rururu** [reply]
@roman-tasi

If you can't provide the structure of the data, I think it's difficult to help. Also, please understand that it is not a free customer center. Please understand that you may not be able to answer immediately because you are investigating and answering with less private time.

**Reply by jertel** [reply]
I suggested that you review your ES field mappings and determine what the underlying data resembles. What was your analysis of that recommendation?

Also, turn on debug (see docs for help) and restart Elastalert 2. This will provide you with more detailed output, including Elastic responses with fields/values, that you can share here.

**Reply by roman-tasi** [reply]
Ok I am currently trying the `--es_debug_trace <trace.log>` argument but am running into an issue if you could help. This is the error I am receiving:

`PermissionError: [Errno 13] Permission denied: '/etc/elastalert/es_debug_log.txt'`

for this argument in my `docker run` command: `--es_debug_trace /etc/elastalert/es_debug_log.txt` 

I have created the `es_debug_log.txt` in `/etc/elastalert` and gave it these permissions: `-rwxrwxrwx.` I am also running from `root`. Basically how do I work around this error?

**Reply by jertel** [reply]
I've requested that this user read up on Docker filesystem mapping in multiple previous posts. @roman-tasi you will need to add a `-v <host path>:<container path>:rw` parameter.

**Reply by roman-tasi** [reply]
Ok that error is fixed. However in my logs for the container I am not seeing the rule running cycle. This is all it looks like:

```
[root@ELK-Stack elastalert]# docker logs e5a8c38210e07d10575b597fe4a786fbe80816f96e36fa7bf77a874bdcd615d7
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation.
[root@ELK-Stack elastalert]#
```
Any idea why the rule isn't being triggered? I never had that issue before adding the `es_debug_log.txt`.

**Reply by jertel** [reply]
What does the `es_debug_log.txt` file have in it?

**Reply by roman-tasi** [reply]
That file is empty. 

Also reverting back to my old command without the ` -v $(pwd)/es_debug_log.txt:/etc/elastalert/es_debug_log.txt:rw` is still giving the same issue where the container logs do not have any rule queries.

**Reply by jertel** [reply]
After you run it, check `docker ps -a` and see if elastalert is still running. From the docker log output it looks like it abruptly stopped.

**Reply by roman-tasi** [reply]
The command `docker ps -a` is coming back with `STATUS` as "`Up`" a certain amount of time not `Exited`. So I'm pretty lost on how to proceed, unless you know any thing else I could do.

**Reply by jertel** [reply]
Did you change a logging settings in the elastalert config file?

**Reply by nsano-rururu** [reply]
I think es_debug_trace can be used to check what kind of query is being issued to elasticsearch, but I don't think it can solve <MISSING VALUE>.

**Reply by nsano-rururu** [reply]
I feel that it is useless if I can not check the data structure by myself with try and error by modifying the source code instead of docker, adding print statements, python setup.py install.

**Reply by nsano-rururu** [reply]
@roman-tasi

- Is the index you are searching for in the rule a log of your own app? .. Is it something that OSS collects? For example, metricbeat, filebeat, heartbeat, etc.
- Why don't you provide the information you need to reproduce the same information?

**Reply by roman-tasi** [reply]
The index I am searching for is winlogbeat which is searching for lockout logs. It is just that I need user, machine, and source ip fields. But apparently my data structure is not proper.

**Reply by roman-tasi** [reply]
This is my `rules.yaml` :

```
name: ElastAlert Rules File
type: any
num_events: 1
filter:
- query:
    query_string:
      query: "\"A user account was locked out\""
index: winlogbeat-*
realert:
  minutes: 0
query_key:
  - source.ip
include:
  - winlog.event_dataTargetUserName
  - winlog.computer_name
  - user.name
  - host.hostname
  - message
include_match_in_root: true
alert_subject: "Lockout Event Detected from User {0}"
alert_subject_args:
  - winlog.event_dataTargetUserName
alert_text: |-
  Lockout Event detected.
  Details of the event:
          - User-Test:
          - Host-Test:
          - Host-Test1:
          - Host-Test2:
          - message-Test:
alert_text_args:
  - winlog.event_dataTargetUserName
  - winlog.computer_name
  - user.name
  - host.hostname
  - message
alert:
  - email:
     from_addr: "relay2@uktasi.org"
     email: "info@uktasi.org"
     smtp_host: "mail.uktasi.org"
     smtp_port: 587
     smtp_ssl: false

```

None of my alert arguments are working. They are all just missing/empty values.

**Reply by nsano-rururu** [reply]
Since it supports heartbeat, filebeat, and metricbeat data structures, it probably does not support winlogbeat data structures.
To be honest, I think you should look for another product.

**Reply by nsano-rururu** [reply]
I don't think you should definitely use elastalert2.

**Reply by roman-tasi** [reply]
> Since it supports heartbeat, filebeat, and metricbeat data structures, it probably does not support winlogbeat data structures.
> To be honest, I think you should look for another product.

@jertel Can you confirm this

**Reply by jertel** [reply]
I've seen challenges with _some_ windows logs when the field names contain spaces. But I don't see spaces in your examples. I would expect it to work. 

In your most recent config you pasted this, which appears to be missing the argument slot syntax, e.g. `{0}`:
```
alert_text: |-
  Lockout Event detected.
  Details of the event:
          - User-Test:
          - Host-Test:
          - Host-Test1:
          - Host-Test2:
          - message-Test:
```

Did you intend to do this? I would expect it to look like this:

```
alert_text: |-
  Lockout Event detected.
  Details of the event:
          - User-Test: {0}
          - Host-Test: {1}
          - Host-Test1: {2}
          - Host-Test2: {3}
          - message-Test: {4}
```

Below is a working rule that uses the argument syntax. This rule uses the Kibana sample data, so you should be able to reproduce this on a brand new Elastic instance.

```
name: clothing_order_placed

type: any

timeframe:
  minutes: 1440

scan_entire_timeframe: true

filter:
 - query:
     query_string:
       query: "\"Women's Clothing\""

index: "*"

include_match_in_root: true
timestamp_field: order_date

alert_text_type: alert_text_only
alert_text: |-
  Women's Clothing order placed.
  Details of the event:
          - currency: {0}
          - email: {1}
          - products.manufacturer: {2}
          - geoip.continent_name: {3}
          - taxful_total_price: {4}

alert_text_args:
  - currency
  - email
  - products[0]manufacturer
  - geoip.continent_name
  - taxful_total_price

is_enabled: true

slack_webhook_url: https://hooks.slack.com/services/xyz

alert:
- slack
```

And here is my logging configuration from config.yaml:
```
logging:
 version: 1
 incremental: false
 disable_existing_loggers: false
 formatters:
   logline:
     format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

 handlers:
   console:
     class: logging.StreamHandler
     formatter: logline
     level: DEBUG
     stream: ext://sys.stderr

 loggers:
   elastalert:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch:
     level: DEBUG
     handlers: []
     propagate: true

   elasticsearch.trace:
     level: DEBUG
     handlers: []
     propagate: true

   '':  # root logger
     level: DEBUG
     handlers:
       - console
     propagate: false
```

Notice in the below output that I get in my ElastAlert2 console, when debug is enabled, it has the full elasticsearch response, including all the data that I'm trying to include in my alert:
```
2022-01-17 21:13:47,751     INFO        elasticsearch POST http://172.17.0.1:9200/elastalert_status/_doc [status:201 request:0.006s]
2022-01-17 21:13:47,751    DEBUG        elasticsearch > {"match_body":{"geoip":{"continent_name":"South America","city_name":"Bogotu00e1","country_iso_code":"CO","location":{"lon":-74.1,"lat":4.6},"region_name":"Bogota D.C."},"customer_first_name":"Sonya","customer_phone":"","type":"order","manufacturer":["Spherecords Maternity","Tigress Enterprises"],"products":[{"tax_amount":0,"taxful_price":11.99,"quantity":1,"taxless_price":11.99,"discount_amount":0,"base_unit_price":11.99,"discount_percentage":0,"product_name":"Basic T-shirt - darkblue/white","manufacturer":"Spherecords Maternity","min_price":5.88,"created_on":"2016-12-12T20:18:14+00:00","unit_discount_amount":0,"price":11.99,"product_id":11504,"base_price":11.99,"_id":"sold_product_566452_11504","category":"Women's Clothing","sku":"ZO0706307063"},{"tax_amount":0,"taxful_price":28.99,"quantity":1,"taxless_price":28.99,"discount_amount":0,"base_unit_price":28.99,"discount_percentage":0,"product_name":"Sandals - gold","manufacturer":"Tigress Enterprises","min_price":13.05,"created_on":"2016-12-12T20:18:14+00:00","unit_discount_amount":0,"price":28.99,"product_id":16385,"base_price":28.99,"_id":"sold_product_566452_16385","category":"Women's Shoes","sku":"ZO0011300113"}],"customer_full_name":"Sonya Salazar","order_date":"2022-01-17T20:18:14Z","customer_last_name":"Salazar","day_of_week_i":0,"total_quantity":2,"currency":"EUR","taxless_total_price":40.98,"total_unique_products":2,"category":["Women's Clothing","Women's Shoes"],"customer_id":28,"sku":["ZO0706307063","ZO0011300113"],"event":{"dataset":"sample_ecommerce"},"order_id":566452,"user":"sonya","customer_gender":"FEMALE","email":"sonya@salazar-family.zzz","day_of_week":"Monday","taxful_total_price":40.98,"_id":"kjrfaX4BI56Iq-mtpKkF","_index":"kibana_sample_data_ecommerce","_type":"_doc","num_hits":1,"num_matches":1},"rule_name":"clothing_order_placed1","alert_info":{"type":"slack","slack_username_override":"elastalert"},"alert_sent":true,"alert_time":"2022-01-17T21:13:47.590015Z","match_time":"2022-01-17T20:18:14Z","@timestamp":"2022-01-17T21:13:47.745398Z"}
2022-01-17 21:13:47,751    DEBUG        elasticsearch < {"_index":"elastalert_status","_type":"_doc","_id":"gjrjaX4BI56Iq-mtje7j","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1}
```

This is the output I received in Slack:
![image](https://user-images.githubusercontent.com/16639611/149837596-0dceb145-0f21-4c79-aef8-a9374b678776.png)

This is the screen in Kibana that lets you add sample data:
![image](https://user-images.githubusercontent.com/16639611/149837267-cd217fd0-5d6c-4a2c-b418-561712e7ab83.png)

Everything I've included here should be sufficient information for someone to get their rules up and running with dynamic alert text, including array values! If you continue to have issues with your rules and alert text I recommend hiring an experienced consultant to get you going.
