### DISCUSSION TITLE
Run queries every minute

### DISCUSSION THREAD

**Discussion by ngms17** [jertel/elastalert2#649] [Q&A] [answered]
```
name: Critical Activity Detected

alert_subject: "Critical alert detected"
alert_subject: "{0} - from {1} to {2}"
alert_subject_args:
- suricata.eve.alert.signature
- source.address
- destination.address

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
# The any rule will match everything. Every hit that the query returns will generate an alert.
type: any

# (Required)
# Index to search, wildcard supported
index: suricata-ids-*

realert:
 minutes: 0

#aggregation:
# minutes: 15

filter:
- terms:
    rule.category: ["Denial of Service", "Successful User Privilege Gain", "Unsuccessful User Privilege Gain", "Attempted Admin$

alert:
- "email"
alert_text: "** ELASTALERT **\n\nSignature: {0}\n\nCategory: {1}"
alert_text_args: ["suricata.eve.alert.signature", "rule.category"]

```

I want to send an alert for every match that i have. The realert option allows that. 

I want to run the queries every minute, because it is a big network and i have a lot of matches. So, i want to decrease the querie span to 1 minute and send every alert in that time span.

If i run this rule, ElastAlert runs every 15 minutes. How can i change it to run every 1 minute?
