### DISCUSSION TITLE
ElastAlert and Elasticsearch Data Streams

### DISCUSSION THREAD

**Discussion by ar3diu** [jertel/elastalert2#664] [Q&A] [answered]
I'm trying to set up a flatline rule to detect when a host stops sending any logs to Elasticsearch. All works fine when I'm using indices like `filebeat-*`, `winlogbeat*` etc. But when I try to monitor the hosts onboarded with Elastic Agent, the rule simply doesn't trigger. After several tests, I concluded that elastalert can't read data in `.ds-logs-*` indices. I searched online, but I couldn't find any information on the subject. Any idea on how I could get around this?

```
name: Rule_name
index: .ds-logs-*
type: flatline
threshold: 1
timeframe:
  minutes: 60
doc_type: _doc
use_terms_query: true
query_key: host.name.keyword
forget_keys: false
filter:
  - query:
      query_string:
        query: "_exists_: host.name"
```
