### DISCUSSION TITLE
Inheriting common settings from config.yaml

### DISCUSSION THREAD

**Discussion by sgolod** [jertel/elastalert2#666] [Q&A] [answered]
I trying to follow DRY and moved default settings to config.yaml

```
realert:
  minutes: 60
exponential_realert:
  hours: 24
```

Example rule:
```
name: 'Alert rule 1' 
index: logstash-*                                                                              
type: any           
filter:                                                                                        
  - query:                                                                                     
      query_string:                                                                            
        query: '.....'                      
alert:                                                                                         
- telegram                                                                                     
```

I'm assuming what my rule 1 will be realerted in 1 hours. But indeed - it realerting every minute. It seems ignore values from config.yaml and set values because this code:
https://github.com/jertel/elastalert2/blob/d71cfa63aeed0ffe6562833fb3d937ea65b05161/elastalert/loaders.py#L313

What am I doing wrong?
