### DISCUSSION TITLE
slack_alert_fields does not add fields

### DISCUSSION THREAD

**Discussion by ngatti-asso** [jertel/elastalert2#669] [Q&A] [answered]
Hi. I have a working rule that pushes alerts to a slack channel.
The alert information isn't enough and I wanted to add more information on the slack message. So I tried by adding `slack_alert_fields` with other fields that exists on the document, but the slack message appears empty. If I add a field that already exists on the message, it is added.
Here is my slack alert configuration:
```
alert:
- "slack"
slack_webhook_url:
- "https://hooks.slack.com/services/BLABLA"
slack_channel_override:
- "#elastalert-test"
slack_alert_fields:
  - title: Container Name
    value: container.name
  - title: container.runtime
    value: container.runtime
  - title: metric_docker.cpu.total.pct_avg
    value: metric_docker.cpu.total.pct_avg
  - title: docker.container.status
    value: docker.container.status
```

Here is the message I get:
```
Threshold violation, avg:docker.cpu.total.pct 0.8295833333333333 (min: None max : 0.6)
@timestamp: 2022-01-21T16:03:00Z
container: {
   "name": "midlayer-pro.web.1"
}
metric_docker.cpu.total.pct_avg: 0.8295833333333333
num_hits: 9360
num_matches: 8

Container Name
midlayer-pro.web.1
container.runtime
metric_docker.cpu.total.pct_avg
0.82958333333333
docker.container.status
```

You can see in the message that 
`container.runtime` and `docker.container.status` does not show any information
`Container Name` and `metric_docker.cpu.total.pct_avg` do show. And both fields are already on the message itself.

Is this a bug or am I missing some configuration? I tried with different fields and none of them showed up unless they are already on the message.

Thanks.

**Comment by nsano-rururu** [comment]
The source code is open to the public.
If it's a bug, please make a pull request.
https://github.com/jertel/elastalert2/blob/master/elastalert/alerters/slack.py

**Comment by jertel** [comment, marked as answer]
I'm not able to reproduce the problem you are reporting. Below is my example rule (I'm using the sample data available with Kibana):

![image](https://user-images.githubusercontent.com/16639611/150569810-f379e15d-762b-4850-a1aa-b6fc10ef2965.png)

And here is my rule configuration:
```
alert_text_type: alert_text_only
alert_text: |-
  Women's Clothing order placed.
  Details of the event:
          - currency: {0}
          - email: {1}
          - products.manufacturer: {2}
          - geoip.continent_name: {3}
          - taxful_total_price: {4}

alert_text_args:
  - currency
  - email
  - products[0]manufacturer
  - geoip.continent_name
  - taxful_total_price

slack_alert_fields:
  - title: category
    value: category[0]
  - title: currency
    value: currency
  - title: sku
    value: sku[0]
  - title: order_id
    value: order_id
```

Notice that my rule never references `order_id` or `sku` prior to be using used in the slack alert fields. You may want to verify that the field types you're trying to reference are not arrays, or some other format that needs to be explicitly converted to a string, which could explain why it works in your formatted message but not as an alert field.
