### DISCUSSION TITLE
docker-compose elastalert not working on restart

### DISCUSSION THREAD

**Discussion by vibarco** [jertel/elastalert2#680] [Q&A] [answered]
Hello,

when using elasalert2 from docker-compose elastalert is not resuming alerts, 

after changing a rule i do:
```
docker-compose stop elastalert
docker-compose start elastalert
```
and elastalert is not resuming until past hours, no activity in alert_status_status

**my config file**

 ```
es_host: elasticsearch
 es_port: 9200

 writeback_index: elastalert_status

 rules_folder: rules

 run_every:
    minutes: 1

 buffer_time:
    minutes: 30

 logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

 loggers:
    elastalert:
      level: DEBUG
      handlers: []
      propagate: true

 elasticsearch:
      level: DEBUG
      handlers: []
      propagate: true
```
**rule config**

```
name: Test rule

 run_every:
    seconds: 20

 type: any

 timeframe:
   minutes: 120

 scan_entire_timeframe: true

 filter:
  - query:
      query_string:
        query: "\"string_to_find\""

 index: "cqg*"
 is_enable: true

 alert:
   - email:
      from_addr: ""
      email: ""
 alert_subject: "Test"
 smtp_host: ""
 smtp_port:
 smtp_ssl: true
 smtp_auth_file: "/opt/elastalert/smtp-auth.yml"
```

What i am doing wrong?

Best regards

**Comment by jertel** [comment, marked as answer]
I don't understand this statement:

> and elastalert is not resuming until past hours, no activity in alert_status_status

ElastAlert 2 will not re-alert on something it's already alerted on. However, if you change the _name_ of the rule, then it will re-alert on everything again, since it has no stored knowledge of already having executed searches and alerts for that new rule name.

**Reply by vibarco** [reply]
Many thanks @jertel, 

sorry sure it is my fault because i don't fully understand the elastalert behaviour. What i mean is if i stop elastalert container and start again i don't see any activity inmediatly in the elastaler_status_status log, as i have set in rule run_every: 20 seconds i expect at least to see the alert triggered every 20 seconds in the elastalert_status_status index when it starts but it doesn't

`docker-compose stop elastalert`

last log entry when stopped

![elastalert1](https://user-images.githubusercontent.com/33134255/151518140-e662aac3-36f7-4b46-acaf-201377a6127e.jpg)

`docker-compose start elastalert` immediatly start again

next log entry appears one hour later

![elastalert2](https://user-images.githubusercontent.com/33134255/151518559-76f7f29c-ae09-4a04-8e8e-0e0d785af5e9.jpg)

Pease look at the hole when elastalert starts no logging until one hour later

Regards

**Reply by jertel** [reply]
You will need to enable debug logging and then check the elastalert log file or `docker logs elastalert` to find out what ElastAlert is doing during this first hour.

**Reply by vibarco** [reply]
Many thanks @jertel, i'll try to activate logging, i am a novice using elastalert

Best

**Reply by vibarco** [reply]
Are the indexes elastalert create correct? elastalert_status_status i think is not in docs

![indexes](https://user-images.githubusercontent.com/33134255/151580062-64b1e52e-4aeb-44e2-a625-f117ebe0a284.jpg)

**Reply by jertel** [reply]
If you set your `writeback_index` setting to `elastalert_status` then it will append the index suffixes, like `_status`, and `_silence` to that, and you end up with `elastalert_status_status`, etc. If you set `writeback_index: elastalert` instead, it will avoid the redundant `_status`. But it doesn't cause a problem if you leave it as you have it.

**Reply by vibarco** [reply]
Thank you @jertel. I am not getting anything distinct to this in logs with this logging section conf. No errors

```
logging:
 version: 1
 incremental: false
 disable_existing_loggers: false
 formatters:
   logline:
     format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'
handlers:
  console:
     class: logging.StreamHandler
     formater: logline
     level: DEBUG
     stream: ext://sys.stderr
loggers:
   elastalert:
     level: DEBUG
     handlers: []
     propagate: true
elasticsearch:
     level: DEBUG
     handlers: []
     propagate: true
'':
     level: DEBUG
     handlers:
        - console
     propagate: false

```
`docker-compose logs -f elastalert`

![logs](https://user-images.githubusercontent.com/33134255/151589743-577d287e-d6a2-4184-930d-b6bd64dc621d.jpg)

**Reply by jertel** [reply]
The `elasticsearch and ''` loggers don't look like they're indented correctly. It should look like this:

```
logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      formatter: logline
      level: DEBUG
      stream: ext://sys.stderr

  loggers:
    elastalert:
      level: DEBUG
      handlers: []
      propagate: true

    elasticsearch:
      level: DEBUG
      handlers: []
      propagate: true

    elasticsearch.trace:
      level: DEBUG
      handlers: []
      propagate: true

    '':  # root logger
      level: DEBUG
      handlers:
        - console
      propagate: false
```
