### DISCUSSION TITLE
Query : Field Exists ?? Its Possible?

### DISCUSSION THREAD

**Discussion by portalthiago** [jertel/elastalert2#683] [Q&A] [answered]
Guys, its possible in elastalert2 having a test on a alert query that respond if a field exists? 

rule.mitre.tactic: "exists" as example. This will help alot. Anyone know about it? Thx

![image](https://user-images.githubusercontent.com/20935653/151703537-50887e26-df3a-442d-91fb-6c3ed0459415.png)

**Comment by nsano-rururu** [comment, marked as answer]
try it.

```yaml
filter:
  - query:
      query_string:
        query: "_exists_:rule.mitre.tactic"
```

**Reply by nsano-rururu** [reply]
yelp / elastalert past issues

https://github.com/Yelp/elastalert/issues/670#issuecomment-246533613
>Osquery data? :)
>
>Are you using timestamp_field: _timestamp?
>
>This looks like it's missing a timestamp field where it expects one. It probably shouldn't crash like this, but maybe try adding to the filters

```yaml
query:
  query_string:
    query: "_exists_: _timestamp"
```
