### DISCUSSION TITLE
Flatline Rule not working

### DISCUSSION THREAD

**Discussion by newcron** [jertel/elastalert2#709] [Q&A] [answered]
I'm trying to monitor an external system that sends a heartbeat to my application using elastalert2 2.2.1. 

The external system will send a heartbeat every 10 minutes to an API endpoint and I'll convert that heartbeat into a log message that gets sent into ELK.  

My idea is this: I get a log event every 10 minutes, so in every 25 minutes window, there should at least be 2 events that are found. To my understanding, the way to go with elastalert is a _flatline_ rule:

```
      cpi_heartbeat: |-
        name: CPI Heartbeat missing
        type: flatline
        index: app-filebeat-*
        threshold: 2
        timeframe:
          minutes: 25
        filter:
        - term:
            logs.level: info
        - term:
            kubernetes.labels.app: sap-erp-adapter
        - term:
            logs.message: Heartbeat
        alert:
          - opsgenie

```

I've now been trying to get this to run pretty much the whole day, but I am simply not able to get the config right. However,  I can confirm that the filters are correct and matching

The example shown above will: 

* detect missing heartbeats quickly and fire
* will continue to fire forever - even if the heartbeats kick back in (where I'd expect the rule to stop yielding alerts) 
* will eventually just go in "crazy mode" where it starts reporting missing heart beat every minute although everything is fine. 

When I was tweaking the rule, I'd either get to a point when the alert would never be triggered or when the alert would be constantly triggered. 

What am I doing wrong here?
