### DISCUSSION TITLE
Cardinality rule, counting issue when using query_key

### DISCUSSION THREAD

**Discussion by nvasoft** [jertel/elastalert2#717] [Q&A] [answered]
Hi,

I'm trying to set up an alert for DNS-query where unique session ID surpass a limit within 4 hours. Since there are several source IP in the request to the DNS, I need to group the result per sourсe IP. The rule is set to aggregate every 30 minutes. I am using an enhancement to count the number of events across unique sessions ID.

> 

```
aggregation:
  schedule: "*/30 * * * * *"
index: XXXXXX-%Y.%m.%d
name: XXXXXX
type: cardinality
cardinality_field: "session.id"
max_cardinality: 500
timeframe:
  hours: 4
filter:
- query_string:
   query: "XXXXXX"
query_key: "source.ip"

alert:
 - "telegram"
alert_text: " host {0} DNS query {1} count {2}
  - "source.ip"
  - "resource"
  - "cardinality_count"
alert_text_type: "alert_text_only"

match_enhancements:
  - "elastalert_modules.my_enhancements.GetUniqueCardinalityCount"
```

I added this in elastalert_modules/my_enhancements.py
```
from elastalert.enhancements import BaseEnhancement

class GetUniqueCardinalityCount(BaseEnhancement):

    def process(self, match):
        match["cardinality_count"] = len(self.rule["type"].cardinality_cache["all"])
```

The enhancement doesn't work if I use query_key in the rule:
`  ERROR:root:Uncaught exception running rule XXXXXX: name 'all' is not defined`

and I need to get the cardinality_count separately for each unique value of the query_key field.
How can the module be changed so that it works correctly?
