### DISCUSSION TITLE
How to get alerts for a field containing certain strings/words ? Query hits are showing as 0 even though there are hits in Elasticsearch

### DISCUSSION THREAD

**Discussion by iamrahulramesh** [jertel/elastalert2#723] [Q&A] [answered]
# Hi , I am currently running this rule to get a match of  "google.com" from all entries in "link" field, It should be alerting me/taking count if there is "google.com"  somewhere in each of the link, But while running this rule, Eventhough matches are there, It is not showing any counts / sending alerts . I highly appreciate a little help here.

```
name: Flatline_google

type: flatline

index: logstash-*

threshold: 20

timeframe:
  minutes:  10

filter:
  query:
    match:
      link: "google.com"

alert:
  "ms_teams"
alert_subject: Weekly volume of google is less than weekly threshold
alert_subject_args: []
alert_text: Please check for any anomalies for google
alert_text_args: []
ms_teams_webhook_url: webhook.office.com/webhookb2/xxx
ms_teams_alert_summary : "Alert, weekly threshold level of google is less"```

**Comment by jertel** [comment, marked as answer]
From the docs:

[FAQ](https://elastalert2.readthedocs.io/en/latest/recipes/faq.html#my-rule-is-not-getting-any-hits)

I suggest starting there.

**Reply by iamrahulramesh** [reply]
# I have tried running this and still getting 0 hits eventhough most of the links contains "google.com"

```
name: google Frequency

type: frequency


index: logstash-*

num_events: 5

timeframe:
  minutes: 1




filter:
- query:
    query_string:
      query: "link: www.google.com"

alert:
- "ms_teams"
alert_subject: Weekly volume of google is more than weekly threshold
alert_subject_args: []
alert_text: Please check for any anomalies for google
alert_text_args: []
ms_teams_webhook_url: webhook.office.com/webhookb2/xxx
ms_teams_alert_summary : "Alert, weekly threshold level of google is more"
````
### I ran elastalert using this 
```
python -m elastalert.elastalert --verbose --rule google_frequency.yaml --start 2022-02-11 

```

#  This is my config.yaml file 

```rules_folder: threshold_rules


run_every:
  minutes: 1

buffer_time:
  days: 7

es_host: "xxx.gcp.elastic-cloud.com"

es_port: 9243


use_ssl: True

verify_certs: True


es_username: username
es_password: password

writeback_index: elastalert_status

writeback_alias: elastalert_alerts
alert_time_limit:
  days: 2
