### DISCUSSION TITLE
How do I configure alerts for the absence of data in certain fields?

### DISCUSSION THREAD

**Discussion by ixiaoyi93** [jertel/elastalert2#728] [Q&A] [answered]
elastalert2 has solved my problem of alerting me to certain fields matching in the query results very well. Now I would like to implement an alert for certain indexes or fields that do not return a value or have empty data for a certain period of time?

**Comment by jertel** [comment, marked as answer]
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#flatline

**Reply by ixiaoyi93** [reply]
> https://elastalert2.readthedocs.io/en/latest/ruletypes.html#flatline

Thank you very much for your reply, I have reconfigured it via the documentation link. But it didn't work as I wanted, so I would like to ask you to help me to see if my configuration is wrong.

My configuration：
```
name: parse-mqtt-yiliu
type: flatline

timeframe:
  minutes: 30
  
threshold: 1
doc_type: _doc
use_count_query: true


index: vm-iot-parser-logs-%Y.%m.%d
query_timezone: "Asia/Shanghai"

filter:
- query:
    query_string:
      query: "app_name:parse-mqtt-yiliu AND \"before unzip:\""

alert:
  - "elastalert_modules.feishu_alert.FeishuAlert"

feishualert_url: "https://open.feishu.cn/open-apis/bot/v2/hook/"


feishualert_botid:
  ""

feishualert_title:
  "parse-mqtt-yiliu"


feishualert_skip:
  start: "00:00:00"
  end: "00:00:00"

feishualert_body:
  "
   event-name: mqtt-yiliu 30minutes no date！！！\n
   alert-time: {feishualert_time}
  "
```
![image](https://user-images.githubusercontent.com/34268642/154925555-7d39a7d8-04bb-4de1-8b01-a2c442abc0e1.png)

![image](https://user-images.githubusercontent.com/34268642/154925705-d281568a-27f7-4406-afe5-5928435e83a7.png)

I want to implement an alert when a query returns a result of 0 within 30 minutes.I'm not sure now how I can configure this to work
