### DISCUSSION TITLE
Support multiple telegram_room_id in Alert Telegram

### DISCUSSION THREAD

**Discussion by thangtq710** [jertel/elastalert2#730] [Q&A] [answered]
I want to send 1 rule notify to multiple telegram_room_id in Alert Telegram.

```
# Rule name, must be unique
name: Example frequency rule
alert:
- "telegram"
telegram_bot_token: "XXX"
telegram_room_id:
- "AAA"
- "BBB"
```
Not notify to telegram_room_id: "AAA" and "BBB". Please help.

Thanks !

**Comment by nsano-rururu** [comment, marked as answer]
Please try if you can do it with the following description.
```yaml
alert:
  - "telegram"     
      telegram_room_id: "AAA"
  - "telegram"
      telegram_room_id: "BBB"
telegram_bot_token: "XXX"
```

**Reply by thangtq710** [reply]
Running If I config with 1 telegram_room_id:
```bash
alert:
- "telegram"
telegram_room_id: "AAA"
telegram_bot_token: "XXX"
```
But config with:
```bash
alert:
  - "telegram"
      telegram_room_id: "AAA"
  - "telegram"
      telegram_room_id: "BBB"
telegram_bot_token: "XXX"
```
Error:
```
in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "<unicode string>", line 54, column 3:
      - "telegram"
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 55, column 7:
          telegram_room_id: "AAA"
          ^
```

**Reply by nsano-rururu** [reply]
```yaml
alert:
 - telegram:
      telegram_room_id: "AAA"
 - telegram:
      telegram_room_id: "BBB"
telegram_bot_token: "XXX"
```
