### DISCUSSION TITLE
metric_agg_script is not working

### DISCUSSION THREAD

**Discussion by ogrbavac** [jertel/elastalert2#760] [Q&A] [answered]
Hi Team,

I want to check response time for the maappprd.azure-api.net:443 service, but first I need to divide "span.destination.service.response_time.sum.us" with the "span.destination.service.response_time.count" and if this value is higher than max_threshold (15s) alert need to be triggered. But I have problem with the myScriptedMetric, because this value is always null.
Metric aggregation alert: 

```
import: "../common.yaml"

name: ACS service
description: "maappprd.azure-api.net:443 service is not available"
type: metric_aggregation
index: apm-*

filter:
  - term:
      "metricset.name": service_destination
  - term:
      "span.destination.service.resource": maappprd.azure-api.net:443

timeframe:
  minutes: 5
buffer_time:
  minutes: 5
realert:
  hours: 1

min_doc_count: 1
metric_agg_key: myScriptedMetric
metric_agg_script:
  script: doc['span.destination.service.response_time.sum.us'].value / doc['span.destination.service.response_time.count'].value

metric_agg_type: avg
query_key:
  - service.environment
  - service.name
  - span.destination.service.resource
max_threshold: 15000000

alert_subject: "{0} - {1} - {2} - {3}"
alert_subject_args:
  - name
  - service.environment
  - service.name
  - span.destination.service.resource

alert_text_type: exclude_fields
alert_text: >-
  <h1>{2} on: {1} - {0}</h1>
  <p>Event timestamp: <b>{3}</b></p>
  <p>Service.resource: <b>{4}</b></p>
  <br />
  <h2>Technical details:</h2>

alert_text_args:
  - service.environment
  - service.name
  - description
  - "@timestamp"
  - span.destination.service.resource
```

Log:
```
GET https: //name_of_my_page.com:9200/apm-*/_search?ignore_unavailable=true&size=0 [status:200 request:0.021s]
	2022 - 03 - 07 09: 09: 37, 530 DEBUG elasticsearch > {
		"query": {
			"bool": {
				"filter": {
					"bool": {
						"must": [{
							"range": {
								"@timestamp": {
									"gt": "2022-03-07T09:04:37.509150Z",
									"lte": "2022-03-07T09:09:37.509150Z"
								}
							}
						}, {
							"term": {
								"metricset.name": "service_destination"
							}
						}, {
							"term": {
								"span.destination.service.resource": "maappprd.azure-api.net:443"
							}
						}]
					}
				}
			}
		},
		"aggs": {
			"bucket_aggs": {
				"terms": {
					"field": "service.environment",
					"size": 50,
					"min_doc_count": 1
				},
				"aggs": {
					"bucket_aggs": {
						"terms": {
							"field": "service.name",
							"size": 50,
							"min_doc_count": 1
						},
						"aggs": {
							"bucket_aggs": {
								"terms": {
									"field": "span.destination.service.resource",
									"size": 50,
									"min_doc_count": 1
								},
								"aggs": {
									"metric_myScriptedMetric_avg": {
										"avg": {
											"field": "myScriptedMetric"
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
2022 - 03 - 07 09: 09: 37, 530 DEBUG elasticsearch < {
	"took": 4,
	"timed_out": false,
	"_shards": {
		"total": 24,
		"successful": 24,
		"skipped": 20,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 1,
			"relation": "eq"
		},
		"max_score": null,
		"hits": []
	},
	"aggregations": {
		"bucket_aggs": {
			"doc_count_error_upper_bound": 0,
			"sum_other_doc_count": 0,
			"buckets": [{
				"key": "production",
				"doc_count": 1,
				"bucket_aggs": {
					"doc_count_error_upper_bound": 0,
					"sum_other_doc_count": 0,
					"buckets": [{
						"key": "ESB",
						"doc_count": 1,
						"bucket_aggs": {
							"doc_count_error_upper_bound": 0,
							"sum_other_doc_count": 0,
							"buckets": [{
								"key": "maappprd.azure-api.net:443",
								"doc_count": 1,
								"metric_myScriptedMetric_avg": {
									"value": null
								}
							}]
						}
					}]
				}
			}]
		}
	}
}
2022 - 03 - 07 09: 09: 37, 536 INFO elasticsearch POST https: //name_of_my_page.com:9200/elastalert_status_status/_doc [status:201 request:0.006s]
	2022 - 03 - 07 09: 09: 37, 536 DEBUG elasticsearch > {
		"rule_name": "ACS service",
		"endtime": "2022-03-07T09:09:37.509150Z",
		"starttime": "2022-03-07T09:04:37.509150Z",
		"matches": 0,
		"hits": 1,
		"@timestamp": "2022-03-07T09:09:37.530660Z",
		"time_taken": 0.021494150161743164
	}
2022 - 03 - 07 09: 09: 37, 536 DEBUG elasticsearch < {
	"_index": "elastalert_status_status",
	"_type": "_doc",
	"_id":   "********************",
	"_version": 1,
	"result": "created",
	"_shards": {
		"total": 2,
		"successful": 1,
		"failed": 0
	},
	"_seq_no": 3125534,
	"_primary_term": 9
}
2022 - 03 - 07 09: 09: 37, 537 INFO elastalert Ran ACS service from 2022 - 03 - 07 09: 04 UTC to 2022 - 03 - 07 09: 09 UTC: 1 query hits(0 already seen), 0 matches, 0 alerts sent
2022 - 03 - 07 09: 09: 37, 537 INFO elastalert ACS service range 300
```

For the security reason I hide the name of the page.
I've tried different arithmetic operations but the result is the same.
Also, I've checked previous discussions and try this solution #https://github.com/Yelp/elastalert/issues/2701, but this doesn't work.

Could you please check this issue?
If you need any additional information, I'm at your disposal.

Kind regards
