### DISCUSSION TITLE
Alert for when there is 0 hits in kibana in the last 24 hours

### DISCUSSION THREAD

**Discussion by MohammedHoche1** [jertel/elastalert2#795] [Q&A] [answered]
Hey all, I hope you are well.

I was wondering if anyone has been in this situation where they are creating an alert when there are **0** hits in kibana for a specific query. 

I have currently structured the rules config like this using flatline: 
```   name: Email alert rule for Arrc RMS Connector kakfka connect no file processed in nonprod
    type: flatline
    index: logstash-*
    threshold: 1
    timeframe:
      hours: 23
    realert:
      minutes: 60
    aggregation:
      schedule: '0 21 * * *'
    filter:
      - query:
          query_string:
           query: "kubernetes.container_name: \"kafka-connect\" AND (message: \"Finished processing\")"
    alert:
      - slack
      - sns
    sns_aws_region: eu-west-1
    slack_username_override: ElastAlert
    alert_text_type: exclude_fields
    alert_text: |
      Alert was triggered at {0}.
      Event has id: {1}
      Container name: {2}
      Message: {3}
    alert_text_args:
      - "@timestamp"
      - "_id"
      - "kubernetes.labels.app_kubernetes_io/name"
      - "message"
   ```

This will send an alert if there is **1** hit in kibana  in the last 24 hours **but** not when there are **0** hits in kibana in the last 24 hours. 

I would appreciate it if someone could offer me a better suggestion.

**Comment by jertel** [comment, marked as answer]
Are you using an empty query string as a filter? It looks like that from what you posted, but since you didn't format it according to the project guidelines in #11 I can't be sure. If so, I don't know if that's supported. At a minimum I would at least search for something that you know should exit.

I recommend shortening the timeframe to a minute or few seconds so you can enable debug logs and be better equiped to troubleshoot the problem, using data that you can manipulate in ES.

**Reply by MohammedHoche1** [reply]
@jertel hey , sorry I did not read the project guidelines. I have reformatted the question and included the query string.

**Reply by jertel** [reply]
I used your rule but modified it with the following changes:
- Gave it a name, test-13, to be unique from any other rules that had processed on previous tests
- Changed the timeframe and realert to seconds instead of hours to get faster results for testing
- Changed the aggregation schedule to a minute after my present time so I would get the test slack msg sooner
- Added my Slack webhook URL

```
name: test-13
type: flatline
index: "logstash-*"
threshold: 1
timeframe:
  seconds: 23
realert:
  seconds: 10
aggregation:
  schedule: '32 * * * *'
filter:
  - query:
      query_string:
       query: "kubernetes.container_name: \"kafka-connect\" AND (message: \"Finished processing\")"
alert:
- slack
alert_text_type: exclude_fields
alert_text: |
  Alert was triggered at {0}.
  Event has id: {1}
  Container name: {2}
  Message: {3}
alert_text_args:
  - "@timestamp"
  - "_id"
  - "kubernetes.labels.app_kubernetes_io/name"
  - "message"
slack_webhook_url: https://hooks.slack.com/services/
```

Below is the slack alert:
![image](https://user-images.githubusercontent.com/16639611/161273683-f6e8f40a-6224-4f2f-b5ba-cc787660dde8.png)

Now, obviously I do not have any of the data that your ES has. That means that this rule did in fact fire with 0 hits. So it is working as expected. Also note how the slack message doesn't have any field values. How could it have field values from a document that doesn't exist?

This post proves that the rule and ElastAlert 2 work correctly. It will be up to you to analyze your ES data to understand why you are not getting the expected results. As I do not have access to your ES data there's little I can do beyond what I have provided here.
