### DISCUSSION TITLE
Make a double aggregation query

### DISCUSSION THREAD

**Discussion by defxion13** [jertel/elastalert2#796] [Q&A] [answered]
Good day!
Please advice!
I can not find it in the documentation or examples. I need to make an alert, that triggers if two conditions happens. More details:
I have a fields: @timestamp, ip_address, country, direction and other. I need an alert if the number of unique ip_addresses from a certain country has doubled in the last 5 minutes. Here is what i did:
```
type: spike
threshold_ref: 10
timeframe:
  minutes: 5
spike_height: 2
spike_type: up
use_terms_query: true
query_key: [country, ip_address]
filter:
- term:
     direction: "incoming"
```
But this is wrong. It counts values of each unique pairs of country+ip_address, but I need something like 2 aggregations: first by country, second by ip_address. 
I appreciate any advice!

**Comment by jertel** [comment, marked as answer]
From the [docs](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#spike-aggregation):
![image](https://user-images.githubusercontent.com/16639611/161279391-166445a3-aa90-40c9-b44f-a3e8623e166a.png)


Where are the required `metric_agg_key` and `metric_agg_type` fields in your rule?

**Reply by defxion13** [reply]
Thank you! I'm used "spike" type, instead of "spike_aggregation" which i should.
Now I have following:

```
timeframe:
  minutes: 6
type: spike_aggregation
metric_agg_key: ip_address.keyword
metric_agg_type: cardinality
spike_height: 2
spike_type: up
buffer_time:
  minutes: 5
threshold_ref: 150
query_key: country.keyword

filter:
- term:
    direction: "incoming"

alert_text: "In {1} UTC alert from country {0} in last minutes. Events from last interval: {2}, from current interval: {3}"
alert_text_type: alert_text_only
alert_text_args: ["country.keyword", "@timestamp", "reference_count", "spike_count"]
alert_subject: "[Country alert]"
```

I've done something wrong? Because now I have the following error:
Uncaught exception running rule TEST: cannot unpack non-iterable NoneType object.
Traceback (most recent call last):, File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 1234, in handle_rule_execution, num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime')), File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 850, in run_rule, if not self.run_query(rule, rule['starttime'], tmp_endtime):, File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 614, in run_query, rule_inst.add_aggregation_data(data), File "/usr/local/lib/python3.10/site-packages/elastalert/ruletypes.py", line 1199, in add_aggregation_data, self.unwrap_term_buckets(timestamp, payload_data['bucket_aggs']), File "/usr/local/lib/python3.10/site-packages/elastalert/ruletypes.py", line 1233, in unwrap_term_buckets, self.handle_event(event, agg_value, qk_str), File "/usr/local/lib/python3.10/site-packages/elastalert/ruletypes.py", line 498, in handle_event, ref, cur = self.get_spike_values(qk), TypeError: cannot unpack non-iterable NoneType object
