### DISCUSSION TITLE
Shorten kibana discovery url failed

### DISCUSSION THREAD

**Discussion by defxion13** [jertel/elastalert2#814] [Q&A] [answered]
Good day! Please advice!
Here is my config:

```
~
generate_kibana_discover_url: True
shorten_kibana_discover_url: True
kibana_discover_app_url: "https://estest:5601/app/discover?#/"
kibana_username: test
kibana_password: 123
kibana_discover_version: "7.16"
kibana_discover_index_pattern_id: 4a612d10-af5b-11ec-a75f-77ca2d0eb8fc
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 2

alert_text: "{0} {1}"
alert_text_type: alert_text_only
alert_text_args: ["ip.keyword", "kibana_discover_url"]
~
```

I'm getting the following error:
`Traceback (most recent call last):, File "/usr/local/lib/python3.10/site-packages/elastalert/kibana_external_url_formatter.py", line 79, in format, response = [requests.post](http://requests.post/)(, File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 117, in post, return request('post', url, data=data, json=json, **kwargs), File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request, return session.request(method=method, url=url, **kwargs), File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 515, in request, prep = self.prepare_request(req), File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 443, in prepare_request, p.prepare(, File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 318, in prepare, self.prepare_url(url, params), File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 392, in prepare_url, raise MissingSchema(error), requests.exceptions.MissingSchema: Invalid URL 'api/short_url': No scheme supplied. Perhaps you meant http://api/short_url?, (empty), During handling of the above exception, another exception occurred:, (empty), Traceback (most recent call last):, File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 1298, in alert, return self.send_alert(matches, rule, alert_time=alert_time, retried=retried), File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 1340, in send_alert, matches[0]['kibana_discover_url'] = kb_link_formatter.format(kb_link), File "/usr/local/lib/python3.10/site-packages/elastalert/kibana_external_url_formatter.py", line 90, in format, raise EAException("Failed to invoke Kibana Shorten URL API: %s" % e), elastalert.util.EAException: Failed to invoke Kibana Shorten URL API: Invalid URL 'api/short_url': No scheme supplied. Perhaps you meant http://api/short_url?`

What am I doing wrong? Without link shortening, everything works fine.

**Comment by nsano-rururu** [comment, marked as answer]
```yaml
generate_kibana_discover_url: True
shorten_kibana_discover_url: True
kibana_url: "https://estest:5601/"
kibana_discover_app_url: "app/discover#/"
kibana_username: test
kibana_password: 123
kibana_discover_version: "7.16"
kibana_discover_index_pattern_id: 4a612d10-af5b-11ec-a75f-77ca2d0eb8fc
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 2

alert_text: "{0} {1}"
alert_text_type: alert_text_only
alert_text_args: ["ip.keyword", "kibana_discover_url"]
```
