### DISCUSSION TITLE
related_events field missing from frequency alerts

### DISCUSSION THREAD

**Discussion by jgregmac** [jertel/elastalert2#818] [Q&A] [answered]
I have set up a new "frequency" alert on ElastAlert2 v2.4.0.  The rule matches the query results correctly, but the aggregated hits that are requested by the setting `attach_related`, to be included in the field `related_events`, are not included in the results.  

I use these frequency settings:

```yaml
# Frequency-specific settings:
num_events: 1
timeframe:
  minutes: 5
use_terms_query: True
terms_size: 10
query_key: "source.ip"
attach_related: True
```

The `related_events` are missing in both `debug` and `post2` alert types.

I do have some Python coding experience and would be happy to contribute, but I am at a bit of a loss in how to debug a live running ElastAlert2 container.  Any tips on this?  It's not clear to me how I would, say, run "elastalert-test-rule" under pdb. and set a break point to inspect what is going on at line 260 of ruletypes.py, where this is supposed to happen:

```python
if self.attach_related:
    event['related_events'] = [data[0] for data in self.occurrences[key].data[:-1]]
```
