### DISCUSSION TITLE
using script in alert

### DISCUSSION THREAD

**Discussion by manuvakery1** [jertel/elastalert2#819] [Q&A] [answered]
how do I convert the following query into a rule? Not sure if I can use the script in the alert filter
```
GET /metricbeat/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "metricset.name": {
              "value": "diskio"
            }
          }
        },
        {
          "range": {
            "system.diskio.iostat.await": {
              "gte": 10
            }
          }
        }
      ],
      "filter": {
        "script": {
          "script": "doc['system.diskio.iostat.await'].value > doc['system.diskio.iostat.service_time'].value"
        }
      }
    }
  }
}
```

**Comment by jertel** [comment, marked as answer]
Specify the script as a filter in the rule yaml.

Ex:

```
filter:
 - query:
     query_string:
       query: "\"Women's Clothing\""
 - script:
    script: doc['total_unique_products'].value > 1
```
