### DISCUSSION TITLE
spike alert not triggering

### DISCUSSION THREAD

**Discussion by emmanueltouzery** [jertel/elastalert2#835] [Q&A] [answered]
Hello,

 I'm trying to set up a spike alert with a filter, it doesn't trigger and I don't understand why.

 The rule is the following:

```yaml
name: Backup is performed again
type: spike
index: filebeat-system-*
doc_type: _doc
timeframe:
  days: 1
filter:
  - query:
     query_string:
       query: 'message:"backup_all_sites: completed without errors"'
spike_height: 10
spike_type: up
threshold_cur: 1
use_terms_query: true
query_key: host.name
query_delay:
  minutes: 1
realert:
  minutes: 2
alert_on_new_data: true
alert:
  - "email"
alert_subject: "{0} backups are performed again"
alert_subject_args:
  - host.name
email:
  - "test@test.com"
```

The idea is that when backups are performed successfully, we can find that line in the logs. Then I want an alert when the backups were not performed (another alert, flatline) and when they get performed again (this alert, spike).

To me the YAML looks correct. alert_on_new_data, timeframe day 1, query_key: hostname, threshold_cur: 1.. so if today a backup was done on the server and yesterday it wasn't, it should trigger the alert.

I went to look in the writeback status index, and I see that the query matches at the right time of the day:
```json
      {
        "_index" : ".elastalert_status_status",
        "_type" : "_doc",
        "_id" : "HhqSkYABPyPs3dPtbqpk",
        "_score" : null,
        "_source" : {
          "rule_name" : "Backup is performed again",
          "endtime" : "2022-05-05T00:14:34.492016Z",
          "starttime" : "2022-05-05T00:13:31.962650Z",
          "matches" : 0,
          "hits" : 1,
          "@timestamp" : "2022-05-05T00:15:34.499491Z",
          "time_taken" : 0.007462739944458008
        },
        "sort" : [
          1651709734499
        ]
      },
```

as you can see, hits is 1. Therefore the query did return a hit, and that's correct, at that time the backup was performed. However matches is 0 and I don't understand why, because I can see in the indices that the day before there was no match for that same server (host.name). So I don't understand why this alert isn't triggered?

PS: I'm also curious regarding the answer to https://github.com/Yelp/elastalert/issues/1381 -- How does elastalert use the writeback index to trigger alerts, when those involve a 'query_key': in that case the writeback_index would seem not to have enough information?

Thank you!
