### DISCUSSION TITLE
Some rules stop working after ReadTimeouts

### DISCUSSION THREAD

**Discussion by kschrage** [jertel/elastalert2#837] [Q&A] [answered]
Hi,

we have Elastalert2 up and running with 6 rules in place. From time to time the system seems to be struggling with connection timeouts towards the ELK-Cluster. When this happens particular rules stop being queried completely. Just a restart (via docker redeployment in our case) of Elastalert fixes this. After this restart even `alertRetryLimitMins: 4320` runs without problems in this case and gives us all of the missed alerts.

Here's the error from Elastalerts logs for further reference: `ConnectionTimeout caused by - ReadTimeout(HTTPSConnectionPool(host='some-elk-host', port=9200): Read timed out. (read timeout=20))`

I hope this description helps for solving the issue or mitigation.

Thx
Klemens

**Comment by ferozsalam** [comment]
Could you show us an example of a rule that's creating the timeout issues?

**Reply by kschrage** [reply]
Yeah, for sure. Here's one:
```
---
    name: ...
    type: frequency
    index: kubernetes-filebeat-*
    num_events: 1
    timeframe:
      minutes: 10
    filter:
    - query:
        query_string:
          query: "kubernetes.namespace: vs"
    - query:
        query_string:
          query: "message: (Status AND gesetzt AND beheben)"
    - query:
        query_string:
          query: "level: warn"
    alert: 
    - "email"
    alert_text: |-
      ...
    alert_text_args: 
      - logmessage
    alert_text_type: alert_text_only
    alert_subject: "..."
    email: 
    - mail@example.com
```
