### DISCUSSION TITLE
Generate Kibana Discover Link with specific flow_id from the alert

### DISCUSSION THREAD

**Discussion by ngms17** [jertel/elastalert2#838] [Q&A] [answered]
I want to configure a Kibana Discover Link on my alert text (email) with the specific flow_id from the alert. This way, when i open the link, kibana will show the filtered flow_id from that alert.

**Comment by nsano-rururu** [comment, marked as answer]
example

```yaml
# kibana_discover Setting
generate_kibana_discover_url: true
kibana_discover_app_url: "http://localhost:5601/app/discover#/"
kibana_discover_index_pattern_id: "index pattern id"
kibana_discover_version: "7.13"

alert_text: 'New description works only after hivealert description commented out -  {0}'
alert_text_args: [ kibana_discover_url ]
alert_text_type: alert_text_only
```
