### DISCUSSION TITLE
painless script on spike_aggregation rule

### DISCUSSION THREAD

**Discussion by ernestoalejandrocu** [jertel/elastalert2#846] [Q&A] [answered]
result expected: substract fields(number) (jolokia.jvm.memory.heap_usage.max) and (jolokia.jvm.memory.heap_usage.used),
                 and the result (jvm heap free remaining), alert me when the threshold_ref (100 Mb) have crossed. *sorry for my bad english.
                 
docker image: jertel/elastalert2:2.4.0

config.yaml

```
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: elasticsearch-master-1
es_port: 9200
es_username: "-------------"
es_password: "-------------"
writeback_index: elastalert_status
writeback_alias: elastalert_alerts
alert_time_limit:
  days: 30
```

metricbeat-jvm-heap-rule.yaml

```
name: Alerta - Incremento del consumo de Heap en la JVM
type: spike_aggregation
index: "metricbeat-7.17.1-*"
doc_type: _doc
filter:
- query:
    query_string:
      query: 'event.module:jolokia AND metricset.name:jmx'
metric_agg_type: avg
metric_agg_key: myScriptedMetric
metric_agg_script:
  script: doc['jolokia.jvm.memory.heap_usage.max'].value - doc['jolokia.jvm.memory.heap_usage.used'].value
realert:
  minutes: 5
timeframe:
  minutes: 15
min_doc_count: 1
spike_type: "down"
spike_height: 1
threshold_ref: 314572800
alert:
  - "debug"
alert_text: |
  Alerta - Incremento del consumo de Heap en la JVM: {0}.
  Uso de Heap en la JVM: {1}
  Role del componente: {2}
  Entorno: {3}
alert_text_args: ["fields.instance", "jolokia.jvm.memory.heap_usage.used", "fields.role", "fields.environment"]
alert_text_type: alert_text_only
```

@jertel  any help is aprecciated. I dont know is the rule is the correct choice or if the sintax is right. This is the error, when the elastalert2 start......

![imagen](https://user-images.githubusercontent.com/51173983/168673299-f8fe9204-1b82-427e-9aa3-2847dc45f5b0.png)

Thanks.
