### DISCUSSION TITLE
Filter for field instead of just general query?

### DISCUSSION THREAD

**Discussion by lymanaukuleles** [jertel/elastalert2#847] [Q&A] [answered]
This is what I currently have in my rule file:

```
filter:
- query:
   query_string:
     query: "\"4740\""
```

Instead I want to filter for `event.code: 4740`

So basically `4740` only belonging to the `event.code` field. Is this possible?
