### DISCUSSION TITLE
Emailing to multiple recipients formatting

### DISCUSSION THREAD

**Discussion by lymanaukuleles** [jertel/elastalert2#852] [Q&A] [answered]
This is what I currently have in my rule file. Just wondering if its correct:

```
alert:
 - email:
    from_addr: "relay2@whtasi.org"
    email: "roman@whtasi.org"
    from_addr: "relay2@whtasi.org"
    email: "alvin@whtasi.org"
    from_addr: "relay2@whtasi.org"
    email: "jose@whtasi.org"
    smtp_host: "mail.whtasi.org"
    smtp_port: 587
    smtp_ssl: false
    smtp_auth_file: "/etc/elastalert/smtp_auth_user.yaml"
```

**Comment by nsano-rururu** [comment, marked as answer]
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#email

The default value of smtp_ssl is false, so if it is false, it may not be necessary to describe it.
```yaml
alert:
  - email
from_addr: "relay2@whtasi.org"
email:
  - "roman@whtasi.org"
  - "alvin@whtasi.org"
  - "jose@whtasi.org"
smtp_host: "mail.whtasi.org"
smtp_port: 587
smtp_auth_file: "/etc/elastalert/smtp_auth_user.yaml"
```
