### DISCUSSION TITLE
Best way to filter for multiple terms together

### DISCUSSION THREAD

**Discussion by lymanaukuleles** [jertel/elastalert2#864] [Q&A] [answered]
I want to filter for logs that contain multiple fields. Unfortunately the ElastAlert documentation doesn't seem to show how to do this. I want AND logic not OR log. So for example x AND y AND z must be in the log for the alert to generate. So can you help?

**Comment by nsano-rururu** [comment, marked as answer]
https://elastalert2.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or
https://github.com/Yelp/elastalert/issues/2109

**Reply by lymanaukuleles** [reply]
That’s the example I was referring to in my original post. Unfortunately I don’t understand it, or it’s doing more than I need for my use-case.

**Reply by lymanaukuleles** [reply]
So would it just be this:

```
filter:
- term:
    event.code: 4688
- term:
    winlog.event_data.MandatoryLabel: S-1-16-4096
- term:
    winlog.event_data.MandatoryLabel: S-1-16-0
```
Well actually I want the logic to be :
4688 AND (S-1-16-4096 OR S-1-16-0)

**Comment by iamxeph** [comment]
I don't really understand what you want, but maybe you want this?:

```
filter:
  - query:
      query_string:
        query: "event.code: 4688 AND (winlog.event_data.MandatoryLabel: S-1-16-4096 OR winlog.event_data.MandatoryLabel: S-1-16-0)
```
