### DISCUSSION TITLE
How to fix this parsing error?

### DISCUSSION THREAD

**Discussion by lymanaukuleles** [jertel/elastalert2#867] [Q&A] [answered]
This is the error:
```
2022-05-28 20:55:44,709    ERROR           elastalert Could not load rule /etc/elastalert/elastalert_rules/browser-execution.yaml: Could not parse file /etc/elastalert/elastalert_rules/browser-execution.yaml: while scanning a double-quoted scalar
  in "<unicode string>", line 8, column 40:
     ... log.event_data.NewProcessName: ["C:\Program Files\Mozilla Firefo ...
                                         ^
found unknown escape character 'M'
  in "<unicode string>", line 8, column 58:
     ... ProcessName: ["C:\Program Files\Mozilla Firefox\firefox.exe", "C ...
```
This is the actual rule filter:
```
filter:
- term:
    winlog.event_id: "4688"
- terms:
    winlog.event_data.NewProcessName: ["C:\Program Files\Mozilla Firefox\firefox.exe", "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
```
