### DISCUSSION TITLE
type:cardinality limit_execution timeframe Incorrect time

### DISCUSSION THREAD

**Discussion by Pa55w0rd** [jertel/elastalert2#872] [Q&A] [answered]
My English is poor and I can't describe it clearly

example_rule.yaml：
```yaml
name: test
type: cardinality
index: elk_userlog_*
cardinality_field: candidateid
max_cardinality: 10
ignore_null: true 
query_key: ci_number
limit_execution: "0-5 8 * * *"

buffer_time:
  hours: 10
timeframe:
  hours: 10
filter:
- query:
    query_string:
      query: "event_type: candidate_download"
```
I want to give an alarm at 8:00 every day. The alarm time window is 22:00-8:00

Results the events before 22:00 will also participate in the alarm

example error：alert 14:01 event，before 22:00
