### DISCUSSION TITLE
UTC time when using "@timestamp" field in alert_text

### DISCUSSION THREAD

**Discussion by ngms17** [jertel/elastalert2#885] [Q&A] [answered]
At the moment I use Elastalert to send Suricata alerts to my email.

The body of the email is composed of the most relevant fields from the logs. When adding the field "@timestamp" to the email body, it shows in UTC and not in my local time. On my email body i get:

`Event original: {"timestamp":"2022-06-14T15:50:04.817441+0100","flow_id":346031021360165,"in_iface":"enp3s0f1","event_type":"alert","`

`Timestamp (UTC): 2022-06-14T14:50:04.817Z`

Rule Configuration: 

```
name: Critical Activity Detected

alert_subject: "Alert detected - {0}"
alert_subject_args:
- suricata.eve.alert.signature


# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
# The any rule will match everything. Every hit that the query returns will generate an alert.
type: any

# (Required)
# Index to search, wildcard supported
index: suricata-ids-*

realert:
  minutes: 5

query_timezone: "Europe/Lisbon"

filter:
- query:
    query_string:
      query: "event.severity: 1"

query_key: [source.address]

alert:
- "email"

alert_text: "**** ELASTALERT ****\n\nTimestamp (UTC): {0}\n\nFlow ID: {1}\n\nSignature: {2}\n\nSignature_ID: {3}\n\nCategory: {4}\n\nSource Address: {5}:{6} | Country: {7}\n\nDestination Address: {8}:{9} | Country: {10}\n\nNetwork protocol: {11}\n\nNetwork transport: {12}\n\nBytes: {13}\n\nPackets: {14}\n\nEvent original: {15}"

alert_text_args: ["@timestamp", "suricata.eve.flow_id", "suricata.eve.alert.signature", "rule.id", "rule.category", "source.address", "source.port", "source.geo.country_name", "destination.address", "destination.port", "destination.geo.country_name", "network.protocol", "network.transport", "network.bytes", "network.packets", "event.original"]

alert_text_type: alert_text_only
```
