### DISCUSSION TITLE
Missing keywords for flatline alerts.

### DISCUSSION THREAD

**Discussion by xph8** [jertel/elastalert2#893] [Q&A] [answered]
There are missing keywords/fields sent by flatline alerts. Frequency alerts sent all the keywords.

Flatline rule:
```
name: down-detector
index: logs.*
use_count_query: true
query_key: hostname

type: flatline
threshold: 100

timeframe:
  minutes: 5

filter:
  - query:
      query_string:
        query: "*"

alert:
- "email"

alert_text: "Abnormally low number of events. hostname: {0}, timestamp {1}"
alert_text_type: alert_text_only
alert_text_args: ["hostname", "@timestamp"]

email:
- "me@example.com"
smtp_host: "outbound.example.com"
smtp_port: 25
smtp_ssl: false
from_addr: "elastalert-no-reply@example.com"
```

Email recieved:
```
Abnormally low number of events. hostname: <MISSING VALUE>, timestamp 2022-06-23T10:27:51.110626Z
```

Email recieved after removing `alert_text`:
```
down-detector

An abnormally low number of events occurred around 2022-06-23 05:31 UTC.
Between 2022-06-23 05:26 UTC and 2022-06-23 05:31 UTC, there were less than 100 events.

@timestamp: 2022-06-23T05:31:35.587960Z
count: 9
key: all
num_hits: 0
num_matches: 4
```

I'm looking for `hostname` and some other fields which are available if the alert is of type frequency but not with flatline. These keywords are essential to my alerting system.
