### DISCUSSION TITLE
Filtering for two terms not working

### DISCUSSION THREAD

**Discussion by lymanaukuleles** [jertel/elastalert2#899] [Q&A] [answered]
This is my current filter:

```
num_events: 1
filter:
- term:
    command: "Auth"
- term:
    log.level: "WARN"
```

I want to alert on logs that have both the `command: "Auth"` and `log.level: "WARN"` field values (It has to be BOTH values, not Either/Or). My current filter doesn't seem to be working in this way (I am getting no query hits at all despite getting logs with these field values). So can you help?
