### DISCUSSION TITLE
Flatiline rule with limit_execution not working correctly

### DISCUSSION THREAD

**Discussion by ghost** [jertel/elastalert2#908] [Q&A] [answered]
I have the following rule:

```
name: "my-rule"
type: "flatline"
limit_execution: "0-20 20 * * *"
index: "my-index"
is_enabled: true
threshold: 1
timeframe:
  minutes: 20
realert:
  minutes: 20
timestamp_field: "@timestamp"
timestamp_type: "iso"
use_strftime_index: false
alert_subject: "my-subject"
alert_text: "my-text"
alert_text_type: "alert_text_only"
filter:
  - query_string:
      query: "body.data.updatedOn: * AND body.data.customFields.ConnectionType__c:"
alert:
  - "slack"
  - "email"
slack_webhook_url: "${SLACK_WEBHOOK_URL}"
slack_channel_override: "#my channel"
slack_emoji_override: ":loudspeaker:"
slack_msg_color: "danger"
slack_parse_override: "none"
slack_username_override: "ElastAlert"
email: [${NOTIFICATIONS_RECIPIENTS}]
smtp_host: "${AWS_SMTP_ENDPOINT}"
smtp_port: ${AWS_SMTP_TLS_PORT}
smtp_ssl: true
from_addr: "${SMTP_FROM_ADDR}"
smtp_auth_file: "/opt/elastalert/smtp_auth_file.yaml"
```

Supposedly the rule should run every minute between 20:00 to 20:20 UTC and send an alert at 20:20 if less than 1 record happens to be found in that time frame. This seems to work initially, until the rules starts to "misbehave" and alerts get sent at 20:00 (so as soon as the rule is activated).

The verbose logs show that the rule is actually picking up matches from the time window when it's supposed to be paused instead:

```
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ran my-rule from 2022-07-19 06:20 AEST to 2022-07-20 06:00 AEST: 0 query hits (0 already seen), 95 matches, 2 alerts sent
elastalert           | INFO:elastalert:my-rule range 85190
elastalert           | INFO:elastalert:Queried rule my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 / 0 hits
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ran my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 query hits (0 already seen), 1 matches, 0 alerts sent
elastalert           | INFO:elastalert:my-rule range 900
elastalert           | INFO:elastalert:Queried rule my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 / 0 hits
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ran my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 query hits (0 already seen), 1 matches, 0 alerts sent
elastalert           | INFO:elastalert:my-rule range 900
elastalert           | INFO:elastalert:Queried rule my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 / 0 hits
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ran my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 query hits (0 already seen), 1 matches, 0 alerts sent
elastalert           | INFO:elastalert:my-rule range 900
elastalert           | INFO:elastalert:Queried rule my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 / 0 hits
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ran my-rule from 2022-07-20 05:45 AEST to 2022-07-20 06:00 AEST: 0 query hits (0 already seen), 1 matches, 0 alerts sent
elastalert           | INFO:elastalert:my-rule range 900
elastalert           | INFO:elastalert:Queried rule my-rule from 2022-07-20 05:46 AEST to 2022-07-20 06:01 AEST: 0 / 0 hits
elastalert           | INFO:elastalert:Ignoring match for silenced rule my-rule.all
elastalert           | INFO:elastalert:Ran my-rule from 2022-07-20 05:46 AEST to 2022-07-20 06:01 AEST: 0 query hits (0 already seen), 1 matches, 0 alerts sent
```

So far I've tried to delete elastalert indexes and to add the parameter old_query_limit to the config, but to no avail. For the life of me I can't figure out why this is happening.
Below here the full config file:

```
rules_folder: /opt/elastalert/rules

run_every:
  seconds: 10

buffer_time:
  minutes: 15

es_host: elasticsearch
es_port: 9200

use_ssl: True
ca_certs: /opt/elastalert/tls/elasticsearch-ca.pem

es_username: elastic 

writeback_index: elastalert_status

alert_time_limit:
  days: 2

old_query_limit:
  minutes: 10
```

Any help would be highly appreciated.
