### DISCUSSION TITLE
elasticsearch.exceptions.SSLError when trying to connect to Elasticsearch 8.3.3

### DISCUSSION THREAD

**Discussion by sapkyy** [jertel/elastalert2#933] [Q&A] [answered]
Hello! Just upgrade Elasticsearch node to ver. 8.3.3. Early with ver. 7.15.1 I used Elastalert1 that was directly installed in Elasticsearch node. And it works good. 
After upgrade I can't run elastalert1 and decided to install Elastalert2 in kuberneres deployment.
My configmap:
```
configmap:
  data:
    elastalert_config: |
      ---
      rulesFolder: "/opt/elastalert/rules"
      run_every:
        minutes: 1
      buffer_time:
        minutes: 15
      es_host: elasticsearch-siem.my.host
      es_port: 9200
      es_username: elastalert
      es_password: elastalert
      writeback_index: elastalert
      use_ssl: "True"
      verify_certs: "False"
      alert_time_limit:
        minutes: 2880
```
But I receive:
`elasticsearch.exceptions.SSLError: ConnectionError(HTTPSConnectionPool(host='elasticsearch-siem.my.host', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))) caused by: SSLError(HTTPSConnectionPool(host='elasticsearch-siem.my.host', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))))`

I tried to add certificates to config, but no result.
1) How I can disable verify_certs? I heard that it deprecated now. 
2) If it impossible, how I can generate clientCert, clientKey, caCerts?

At Elastalert1 I used:
```
      use_ssl: "True"
      verify_certs: "False"
```
And it works. Thanks!
