### DISCUSSION TITLE
Trigger alert only if host name exists in text or csv

### DISCUSSION THREAD

**Discussion by pravyn** [jertel/elastalert2#934] [Q&A] [answered]
Hello,

Below is the rule we are using to trigger email for Disk utilisation. 

In the index we have DEV, TEST & PROD virtual machines but we would like to trigger alert only for PROD virtual machines.

So, we would like to maintain a text/csv file and list all PROD vm's. Alert should compare this text/csv file and if VM exists, alert will be triggered. 

Please let me know if we can implement something like this.

Thanks,
Praveen

-------------------------------------------------------------------------------------------------------

name: Disk utilization exceeded threshold of 80%

type: any

use_strftime_index: true
index: metrics-*

buffer_time:
  minutes: 1

realert:
  minutes: 60

filter:
- query:
    query_string:
       query: "system.filesystem.used.pct:(>=0.8) AND system.filesystem.available: <50000000000"

query_key: agent.hostname

smtp_host: "smtp.mailgun.org"
smtp_port: 25
smtp:ssl: true
from_addr: "test@test.com"
smtp_auth_file: '/opt/elastalert2/smtp_auth_file.yaml'

alert_subject: "Disk utilization exceeded threshold of 80% for host: {0}"
alert_subject_args:
 - agent.hostname

alert_text_type: alert_text_only

alert_text: |
        <html>
        <body>

           <ul>
           <li>Available: {3} GB</li>
           <li>Total: {4} GB</li>
           <li>Used: {0:.2%}</li>
           <li>Mount Point {2}</li>
           <li>Host {1}</li>
           </ul>
           <br/>
           <p style="text-align:left;">Regards,</p>
           <p style="text-align:left;">Observability Team</p><br/>
        </body>
        </html>

alert_text_args: ["system.filesystem.used.pct","agent.hostname","system.filesystem.mount_point","system.filesystem.available","system.filesystem.total"]

email_format: "html"
# alert_text: "Disk utilization: {0:.2%}\nHost: {1}\nTimestamp: {2}"
# alert_text_args: ["metric_system.filesystem.used.pct_avg", "agent.hostname", "@timestamp"]

alert:
 - "email"
#Receipients
email: "test@test.com

**Comment by jertel** [comment, marked as answer]
Yes, it's possible. Options:
1. Implement an [enhancement](https://elastalert2.readthedocs.io/en/latest/recipes/adding_enhancements.html) to add the python code to read from your text file
2. Include the prod hostnames directly in the rule filter query,
3. Have an external script generate the rule.yaml file in option 2, using a text file of prod hostnames as input.

In the future, please review #11 and ensure your pasted rule/config snippets are formatted properly.

**Comment by pravyn** [comment]
Thank you so much Jertel. I' am very new to Elastalert so trying to understand various pieces. Let me know if the below works...

Here is my rule...

```
name: Disk utilization exceeded threshold of 80%
type: any
use_strftime_index: true
index: metrics-*
buffer_time:
  minutes: 1
realert:
  minutes: 60
filter:
- query:
    query_string:
       query: "system.filesystem.used.pct:(>=0.8) AND system.filesystem.available: <50000000000"
match_enhancements:
  - "elastalert_modules.hour_range_enhancement.test"
query_key: agent.hostname
smtp_host: "smtp.mailgun.org"
smtp_port: 25
smtp:ssl: true
from_addr: "test@test.com"
smtp_auth_file: '/opt/elastalert2/smtp_auth_file.yaml'
alert_subject: "Disk utilization exceeded threshold of 80% for host: {0}"
alert_subject_args:
 - agent.hostname
alert_text_type: alert_text_only
alert_text: ""
alert_text_args: ["system.filesystem.used.pct","agent.hostname","system.filesystem.mount_point","system.filesystem.available","system.filesystem.total"]
email_format: "html"
alert:
 - "email"
email: "praveen.pandeti@blueyonder.com"

```

Here is my enhancement. Trying to read servers from List but if this works, i will convert the code to read from CSV.

```
from elastalert.enhancements import BaseEnhancement, DropMatchException
class DropIfNotExsistsinList(BaseEnhancement):
    def process(self, match):
        listOfStrings = ['server1' , 'server2']
        if match['query_key'] not in listOfStrings :
            raise DropMatchException()

```
