### DISCUSSION TITLE
Elastalert when running with more than 2000 rules.

### DISCUSSION THREAD

**Discussion by ObroceaCalin** [jertel/elastalert2#948] [Q&A] [answered]
Hello,

I want to run Elastalert using a large number of rules (around 2000 or even more). The problem is that when I try and run it, I get the following: 

`WARNING:apscheduler.executors.default:Run time of job "Rule: RuleName (trigger: interval[1 day, 0:00:00], next run at: 2022-09-16 11:49:13 UTC)" was missed by 0:00:05.016928.
`
I made some research online and found out that the problem is related to the fact that the process is too busy to start the jobs in a timely manner, and the proposed solution was to use the _misfire_grace_time_ parameter, but it did not work for me  ( https://stackoverflow.com/questions/30235604/next-run-time-missed-by-some-seconds-in-job-scheduling-in-apscheuler)

Here are my configurations:

**Rule Config**

```
alert: slack
column_subfield: xxxxxx
doc_type: doc
filter:
- alert_subject: No Data for column {0}
  alert_subject_args:
  - '@column.keyword'
  query:
    query_string:
      query: 'event.keyword: event_name AND column.keyword: column_subfield'
index: xxxxx
max_threads: 16
misfire_grace_time: 60000
name: Alert Name
scan_entire_timeframe: true
timeframe:
  days: 7
timestamp_field: time
type: handcrafted_rules.awesome_rules.AwesomeRule
use_count_query: true
```

**Global Config**

```

rules_folder: rules

run_every:
  days: 1

es_host: xxxxx
es_port: xxxxxx

use_ssl: True

es_username: xxxxxx
es_password: xxxxxxx


```

Need to mention that I am using a custom Rule which I had implemented and which works for a lower number of rules.  Is there any way to deal with this issue, or try to re-run the rules that were not scheduled properly? 

Any help is appreciated. Thank you!
