### DISCUSSION TITLE
Can't assign user in Jira task creation

### DISCUSSION THREAD

**Discussion by jorge-fabric** [jertel/elastalert2#971] [Q&A] [answered]
Hello 👋 

Currently, I am able to create Jira issues, but the `jira_assignee` feature isn't working. 

I've tried three approaches (Username, Account ID and Email) but none is working, so I don't know what can I do to bypass this issue.

```yaml
jira_assignee: "Joe Doe"
jira_assignee: "account_id"
jira_assignee: "joe.doe@mail.com"
```

Can someone help me?

Thanks in advance!
