### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by zsh9527** [jertel/elastalert2#1206]
> I customized part of the aggregate alarm rules, but there were no reports.

## part `config.yaml`
```yaml
# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1
# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  minutes: 0
```

## part `rule.yaml`
```yaml
type: any

index: filebeat-dev-*

aggregation:
  minutes: 2
aggregation_key: 'fields.service'


filter:
- terms:
    fields.level: ["ERROR", "WARN"]

query_key: 'fields.content'
realert:
  minutes: 5
exponential_realert:
  hours: 1
```

## result
It work normal, but never send alert even if arrived in time

## solution
review the config.yaml  
```yaml
alert_time_limit:
  minutes: 2 
# connot set alert_time_limit to zero
```

## problem
- After read the source code,  the aggregation config connot set alert_time_limit to zero.   
- But the document doesn't say anything about that.
- You want to modify the source code or supplement the documentation
