### ISSUE TITLE
How to get the rule_name information in alert?

### ISSUE THREAD

**Issue by mark8s** [jertel/elastalert2#1437]
I have a question: I used the POST api method to obtain the content of the alert, but I found that the request sent by elasticert2 only contained the information in matches, and did not include rule_name and other information.

My rules configuration is:
```
apiVersion: v1
data:
  test.yaml: |-
    name: mark
    type: frequency
    index: biz-*
    num_events: 10
    timeframe:
      minutes: 1
    filter:
    - query:
        query_string:
          query: "ERROR"
    alert:
    - post
    http_post_url: "http://mdar-api.dev-system:8080/logging/alert"
    http_post_all_values: true
```
The request data received by my /logging/alert interface is as follows:

```
{
    "@timestamp": "2024-05-20T09:00:00.858993Z",
    "@version": "1",
    "_id": "F-w6lY8BH038Vnoyqj1I",
    "_index": "biz-2024.05.20",
    "_source_": "stdout",
    "_time_": "2024-05-20T16:59:57.646361283+08:00",
    "cluster": "zce-dev",
    "clusterid": "8",
    "container.image.name": "docker.io/bitnami/kafka:3.6.1-debian-11-r0",
    "k8s.node.ip": "10.31.0.6",
    "k8s.node.name": "node7",
    "kubernetes.container.name": "kafka",
    "kubernetes.namespace": "jaeger",
    "kubernetes.pod.name": "jaeger-kafka-controller-2",
    "message": "[2024-05-20 08:59:57,646] ERROR [RaftManager id=2] Unexpected error INCONSISTENT_CLUSTER_ID in BEGIN_QUORUM_EPOCH response: InboundResponse(correlationId=3230009, data=BeginQuorumEpochResponseData(errorCode=104, topics=[]), sourceId=1) (org.apache.kafka.raft.KafkaRaftClient)",
    "num_hits": 10664,
    "num_matches": 125,
    "time": 1716195598
}
```

But there is no information such as rule_name, but there is it in my es?

![image](https://github.com/jertel/elastalert2/assets/47961301/8835cec2-811a-4826-be69-ba1be839fd4b)

Is there a way to set this via config?
