### ISSUE TITLE
Support count event per query_key

### ISSUE THREAD

**Issue by w-HA** [jertel/elastalert2#158]
Dears,

Good news with this new elastalert2

Is it possible to have the count of event per query_key ( compound_key too )
There is the num_events but not the exact the count ( 20 in my example ) and sometimes not enough

here is my rules with alerta (work fine )
I tried with top_cout_keys but it didn't work with coumpound_key
```
# Index to search, wildcard supported
index: production_logs

# rule name, must be unique
name: ProductionLogs | Erreur java Exception Majeur

# Type of alert
type: frequency
timeframe:
 minutes: 5
num_events: 20

# A list of elasticsearch filters used to find events
filter:
 - query:
     query_string:
           query: tags:as AND javaexception:"java.sql.SQLException"

query_key: ["host","application","applog","doctype","javaclass","javaexception","req_alerta"]

# Anti spam
realert:
  minutes: 5

# Alert is sent when a match is found
alert:
- alerta
alerta_api_url: "http://XXXXXXXXXXXXXXXXXXX/api/alert"
alerta_customer: "%(application)s"
alerta_environment: "%(application)s"
alerta_service: ["%(application)s"]
alerta_resource: "%(applog)s %(doctype)s %(javaexception)s"
alerta_event: "%(req_alerta)s major"
alerta_text: "%(applog)s %(doctype)s %(javaclass)s %(req_alerta)s"
alerta_severity: "major"
alerta_tags: ["%(javaexception)s","exploitation","logs"]
alerta_value: "%(host)s %(javaclass)s %(javaexception)s"
alerta_api_key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'
alerta_timeout: 259200
alerta_use_match_timestamp: true
```
w-HA
