### ISSUE TITLE
Some extraConfigOptions not working in helm chart

### ISSUE THREAD

**Issue by paul-mesnilgrente** [jertel/elastalert2#521]
I have this helm config:

```yaml
elasticsearch:
  extraConfigOptions:
    # Common slack alert settings
    generate_kibana_discover_url: True
    kibana_discover_app_url: "https://kibana.digitalnz.org/app/discover#/"
    kibana_discover_version: "7.14"
    slack_attach_kibana_discover_url: True
```

However the kibana URL is not showing under my alerts.

Putting them in every rules makes the URL to show again.

According to [README](https://github.com/jertel/elastalert2/blob/02b8393de25ccb0a4fcac0163f259ea1f2cfb433/chart/elastalert2/README.md), those extraConfigOptions should be propagated to every rules.

Also it looks like it should work? https://github.com/jertel/elastalert2/blob/02b8393de25ccb0a4fcac0163f259ea1f2cfb433/chart/elastalert2/templates/config.yaml#L46-L47
