### ISSUE TITLE
Jinja template is not updated when using an alert-specific `alert_text`

### ISSUE THREAD

**Issue by thib12** [jertel/elastalert2#653]
To reproduce, in rule.yml add the following parameters:

```yaml
alert_text_type: alert_text_jinja
alert_text: "Test"
alert:
  - slack:
      alert_text_type: alert_text_jinja
      alert_text: |
        An abnormal number ({{spike_count}}) of events occurred.
```
This is done as described in the [documentation](https://elastalert2.readthedocs.io/en/latest/ruletypes.html#alerts)
You will then notice that your alert on Slack will not use the relevant Jinja template when using the `FileRulesLoader`.

The most likely cause is that the Jinja template is not recompiled as in <https://github.com/jertel/elastalert2/blob/master/elastalert/loaders.py#L469>, and therefore a wrong template (the one using the alert_text at the root of the config) is used.
